/**
 * Vite plugin: resolves `@theo/actions` virtual module and emits a typed
 * Proxy facade that calls `theoFetch('/_actions/<name>', body)` against the
 * server-side action handlers.
 *
 * Per plan g3-server-actions-and-useaction v1.2 § Phase 3 / T3.1 + ADR D4.
 * Astro `vite-plugin-actions.ts` modular pattern. Single focused plugin
 * (not monolithic), virtual module + `configureServer` watcher.
 *
 * Module shape emitted on client environment: thin proxy that forwards
 * `actions.<name>(input)` to `POST /_actions/<name>` with JSON or
 * FormData body. On server environment: re-export of the manifest for
 * SSR / module-loader access (T1.3 sub-C consumer).
 *
 * EC-15 (DOCUMENT): HMR uses Vite default invalidation — coarse but
 * correct. Optimization (fine-grained invalidation of only consumers of
 * `@theo/actions`) deferred to G3.1 if dev-server p95 reload > 500ms.
 */
import { existsSync, watch as fsWatch } from 'node:fs'
import { join } from 'node:path'

import type { Plugin, ViteDevServer } from 'vite'

import { scanServerActionsEnriched, type ActionManifestEntry } from '../server/scan/action-scan.js'

const VIRTUAL_ID = '@theo/actions'
const RESOLVED_ID = `\0${VIRTUAL_ID}`

export interface ActionsVirtualModuleOptions {
  /** Path to server directory (where `actions/` lives). */
  serverDir: string
}

export function actionsVirtualModule(opts: ActionsVirtualModuleOptions): Plugin {
  const { serverDir } = opts
  return {
    name: 'theo:actions-virtual-module',
    enforce: 'pre',
    resolveId(id: string) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
      return undefined
    },
    load(id: string) {
      if (id !== RESOLVED_ID) return undefined
      const entries = safeScan(serverDir)
      const ctx = this as unknown as { environment?: { name?: string } } | undefined
      const envName = ctx?.environment?.name
      const isClient = envName === 'client' || envName === undefined
      return isClient ? generateClientFacade(entries) : generateServerManifest(entries)
    },
    configureServer(server: ViteDevServer) {
      const actionsDir = join(serverDir, 'actions')
      // eslint-disable-next-line security/detect-non-literal-fs-filename -- build-time derived path
      if (!existsSync(actionsDir)) return
      // EC-15: coarse invalidation — invalidate ALL modules on actions file change.
      // Optimization deferred per plan ADR D4 note.
      // eslint-disable-next-line security/detect-non-literal-fs-filename -- build-time path
      const watcher = fsWatch(actionsDir, { recursive: true }, () => {
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID)
        if (mod) {
          server.moduleGraph.invalidateModule(mod)
        }
        server.ws.send({ type: 'full-reload' })
      })
      server.httpServer?.once('close', () => {
        watcher.close()
      })
    },
  }
}

function safeScan(serverDir: string): ActionManifestEntry[] {
  try {
    return scanServerActionsEnriched(serverDir)
  } catch {
    // ActionScanError surfaces at build time; for HMR keep an empty manifest
    // so the dev server doesn't crash mid-edit.
    return []
  }
}

/**
 * Client-side module: emits a Proxy facade. For each action `name` in
 * manifest, `actions.<name>(input)` POSTs to `/_actions/<name>` with JSON
 * body (or FormData when input is a FormData instance) and parses the
 * `application/json+devalue` response via the runtime helper.
 */
function generateClientFacade(entries: ActionManifestEntry[]): string {
  const entryLines = entries
    .map((entry) => `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.urlPath)},`)
    .join('\n')

  return `// AUTO-GENERATED by @theo/actions virtual module
/* eslint-disable */
const ACTION_URL_MAP = {
${entryLines}
}

async function callAction(url, input) {
  const isForm = typeof FormData !== 'undefined' && input instanceof FormData
  const headers = { 'x-theo-action': '1' }
  const body = isForm ? input : JSON.stringify(input ?? {})
  if (!isForm) headers['content-type'] = 'application/json'
  const response = await fetch(url, { method: 'POST', headers, body, credentials: 'same-origin' })
  const contentType = response.headers.get('content-type') ?? ''
  if (response.status === 204) return { data: undefined, error: undefined }
  if (contentType.startsWith('application/json+devalue')) {
    const text = await response.text()
    const { parse } = await import('devalue')
    return { data: parse(text, { URL: (h) => new URL(h) }), error: undefined }
  }
  if (contentType.startsWith('application/json')) {
    const json = await response.json()
    if (response.ok) return { data: json, error: undefined }
    return { data: undefined, error: json }
  }
  return { data: undefined, error: { code: 'INTERNAL_SERVER_ERROR', message: await response.text() } }
}

export const actions = new Proxy({}, {
  get(target, prop) {
    if (typeof prop !== 'string') return undefined
    const url = ACTION_URL_MAP[prop]
    if (!url) return undefined
    return (input) => callAction(url, input)
  },
})
`
}

/**
 * Server-side module: re-exports the manifest entries for SSR / module-
 * loader consumption (T1.3 sub-C in action-execute.ts will route requests
 * via this manifest).
 */
function generateServerManifest(entries: ActionManifestEntry[]): string {
  return `// AUTO-GENERATED by @theo/actions virtual module (server env)
/* eslint-disable */
export const manifest = ${JSON.stringify(entries, null, 2)}
export const actions = manifest
`
}
