/* eslint-disable security/detect-non-literal-fs-filename --
 * Codegen-time fs ops: all paths derive from `opts.projectRoot` / `opts.distDir`
 * (vite plugin opts — trusted, set by the framework's CLI). Never serves HTTP input.
 */
/**
 * M2 (theokit-ai-first) — end-to-end typed binding for the `agents/*.ts` convention.
 *
 * Sibling of `app-typed-client.ts` (kept separate so the `@theo/client` output stays
 * byte-unchanged). Two parts:
 *
 * 1. `generateAgentsDts({ manifest, dtsOutPath, projectRoot })` — pure function emitting
 *    `.theokit/agents.d.ts` (the virtual `@theo/agents` module) with `AppAgents` mapping
 *    each scanned agent to `InferAgentInput` of its `defineAgent({ input })` schema, plus a
 *    typed `useAgent` signature — so the client binds to `/api/agents/<name>` with the right
 *    request type and ZERO manual wiring (DoD line 2).
 * 2. `agentsTypedClientPlugin(opts)` — Vite plugin that emits (1), rewrites on `agents/*`
 *    changes, and serves the virtual `@theo/agents` runtime (`useAgent` from `theokit/client`).
 */
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { dirname, posix } from 'node:path'

import type { Plugin, ViteDevServer } from 'vite'

import type { TheoManifest } from '../server/internal-api.js'

const FILE_HEADER = `// AUTO-GENERATED by theokit — do not edit.
// Source: theokit/packages/theo/src/vite-plugin/agents-typed-client.ts (M2).
// To refresh: \`pnpm dev\` or \`pnpm build\` regenerates this on every agents/ change.

/* eslint-disable */
`

/** A safe TS identifier alias for an agent (name may contain path separators). */
function aliasFor(name: string): string {
  return `_agent_${name.replace(/[^\w$]/g, '_')}`
}

/** Relative `import type` path from the .d.ts dir to the agent source (extension stripped). */
function importPath(dtsOutPath: string, projectRoot: string, filePath: string): string {
  const fromDir = dirname(dtsOutPath).replace(/\\/g, '/')
  const abs = posix.join(projectRoot.replace(/\\/g, '/'), filePath.replace(/\\/g, '/'))
  const noExt = abs.replace(/\.[jt]sx?$/, '')
  let rel = posix.relative(fromDir, noExt)
  if (!rel.startsWith('.')) rel = `./${rel}`
  return rel
}

export interface GenerateAgentsDtsOptions {
  manifest: TheoManifest
  /** Absolute path to the .d.ts that will be emitted (drives the import paths). */
  dtsOutPath: string
  /** Absolute project root — agents live at `<projectRoot>/agents`. */
  projectRoot: string
}

export function generateAgentsDts({
  manifest,
  dtsOutPath,
  projectRoot,
}: GenerateAgentsDtsOptions): string {
  const agents = manifest.agents ?? []
  const imports: string[] = []
  const entries: string[] = []
  for (const agent of agents) {
    const alias = aliasFor(agent.name)
    imports.push(
      `  import type ${alias} from '${importPath(dtsOutPath, projectRoot, agent.filePath)}'`,
    )
    entries.push(
      `    '${agent.name}': { input: InferAgentInput<${alias}>; tools: InferAgentToolNames<${alias}> }`,
    )
  }

  const body =
    entries.length > 0
      ? `{\n${entries.join('\n')}\n  }`
      : `{\n    // No agents detected — add \`agents/*.ts\` to populate this binding.\n  }`

  const importBlock = imports.length > 0 ? `${imports.join('\n')}\n` : ''

  return `${FILE_HEADER}
declare module '@theo/agents' {
  import type { InferAgentInput, InferAgentToolNames } from '@theokit/agents'
  import type { UseAgentReturn, AgentTransport } from 'theokit/client'
${importBlock}
  export interface AppAgents ${body}

  // Web (and any HTTP surface): bind by agent name — \`send\` is typed to the agent's \`input\` schema.
  export function useAgent<K extends keyof AppAgents>(
    name: K,
  ): UseAgentReturn<AppAgents[K]['input'], AppAgents[K]['tools']>
  // M41 (ADR-0050) — terminal/desktop (and advanced): bind by an explicit AgentTransport
  // (e.g. InProcessTransport). The SAME hook, one consumption shape across every surface.
  export function useAgent<TInput = unknown>(
    transport: AgentTransport,
  ): UseAgentReturn<TInput>
}
`
}

// ─── Vite plugin ─────────────────────────────────────────────────────────────

const VIRTUAL_AGENTS_ID = '@theo/agents'
const RESOLVED_AGENTS_ID = '\0@theo/agents'

export interface AgentsTypedClientPluginOptions {
  /** Absolute project root (agents live at `<projectRoot>/<agentsDir>`). */
  projectRoot: string
  /** Agents dir name (config `agentsDir`, default "agents"), relative to projectRoot — the watch glob. */
  agentsDir?: string
  /** Absolute `.theokit/` output dir (where `agents.d.ts` lands). */
  distDir: string
  /** Injects the scanned agents; returns the current manifest-shaped agent list. */
  scanManifest: (projectRoot: string) => TheoManifest
}

/** Atomic write via tmp + rename; skips when content is unchanged. */
function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath)) {
    try {
      if (readFileSync(filePath, 'utf-8') === content) return
    } catch {
      /* fall through to write */
    }
  }
  mkdirSync(dirname(filePath), { recursive: true })
  const tmp = `${filePath}.${process.pid}.tmp`
  writeFileSync(tmp, content)
  renameSync(tmp, filePath)
}

function emitAgentsDts(opts: AgentsTypedClientPluginOptions): string {
  const dtsOutPath = posix.join(opts.distDir.replace(/\\/g, '/'), 'agents.d.ts')
  const content = generateAgentsDts({
    manifest: opts.scanManifest(opts.projectRoot),
    dtsOutPath,
    projectRoot: opts.projectRoot,
  })
  writeIfChanged(dtsOutPath, content)
  return dtsOutPath
}

export function agentsTypedClientPlugin(opts: AgentsTypedClientPluginOptions): Plugin {
  let debounce: NodeJS.Timeout | undefined
  let viteServer: ViteDevServer | undefined

  const scheduleEmit = (): void => {
    if (debounce) clearTimeout(debounce)
    debounce = setTimeout(() => {
      try {
        emitAgentsDts(opts)
        if (viteServer) {
          const mod = viteServer.moduleGraph.getModuleById(RESOLVED_AGENTS_ID)
          if (mod) viteServer.moduleGraph.invalidateModule(mod)
        }
      } catch (err) {
        console.error('[theokit:agents-typed-client] codegen error:', err)
      }
    }, 100)
  }

  return {
    name: 'theokit:agents-typed-client',
    enforce: 'post',
    configResolved() {
      try {
        emitAgentsDts(opts)
      } catch (err) {
        console.error('[theokit:agents-typed-client] initial codegen error:', err)
      }
    },
    buildEnd() {
      try {
        emitAgentsDts(opts)
      } catch (err) {
        console.error('[theokit:agents-typed-client] buildEnd codegen error:', err)
      }
    },
    configureServer(server) {
      viteServer = server
      const agentsGlob = posix.join(
        opts.projectRoot.replace(/\\/g, '/'),
        opts.agentsDir ?? 'agents',
      )
      const onFile = (file: string): void => {
        if (file.replace(/\\/g, '/').startsWith(agentsGlob)) scheduleEmit()
      }
      server.watcher.on('add', onFile)
      server.watcher.on('change', onFile)
      server.watcher.on('unlink', onFile)
    },
    resolveId(id) {
      return id === VIRTUAL_AGENTS_ID ? RESOLVED_AGENTS_ID : null
    },
    load(id) {
      if (id === RESOLVED_AGENTS_ID) {
        return `export { useAgent } from 'theokit/client'\n`
      }
      return null
    },
  }
}
