/* eslint-disable security/detect-non-literal-fs-filename --
 * Codegen-time fs ops: all paths derive from `opts.serverDir` / `opts.distDir`
 * (vite plugin opts — trusted, set by the framework's CLI). The plugin only
 * runs at dev/build time, never serves user HTTP input. No path traversal
 * surface here.
 */
/**
 * Phase 2 + Phase 4 of G1 (g1-client-codegen-plan.md):
 *
 * 1. `generateClientDts(manifest, dtsOutPath)` — pure function emitting the
 *    `.theokit/client.d.ts` shape (declared module `@theo/client`).
 * 2. `appTypedClientPlugin(opts)` — Vite plugin wrapper that calls (1),
 *    writes the file atomically, and rewrites on route file changes.
 *
 * Implementation notes:
 *  - Pure (1) is unit-testable without Vite or a filesystem (see G1-P2 tests).
 *  - EC-2: kebab-case segments → camelCase; unsafe chars → bracket-access.
 *  - EC-3: collision between HTTP method name and sub-segment name → method
 *    wins; sub-segment ganha suffix `_` + warning comment.
 *  - EC-6: write é `writeFileSync(tmp) + renameSync(tmp, final)` (POSIX atomic).
 *  - EC-8: imports normalizam `\\` → `/`.
 */

import { mkdirSync, readFileSync, renameSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, isAbsolute, posix, relative, resolve } from 'node:path'

import type { Plugin, ViteDevServer } from 'vite'

import { HTTP_METHODS, type HttpMethod } from '../core/contracts/http-methods.js'
import { generateManifest, type ManifestRoute, type TheoManifest } from '../server/internal-api.js'

import { collectControllerRouteData, type ControllerRouteData } from './controller-client-emit.js'

const FILE_HEADER = `// AUTO-GENERATED by theokit — do not edit.
// Source: theokit/packages/theo/src/vite-plugin/app-typed-client.ts (G1 plan).
// To refresh: \`pnpm dev\` or \`pnpm build\` regenerates this file on every route change.

/* eslint-disable */
`

interface ControllerLeaf {
  /** Import alias of the controller class (`_c0`). */
  classAlias: string
  /** Controller method name backing the route (`findById`). */
  methodName: string
}

interface TreeNode {
  /** sub-namespaces — keyed by segment name (already normalized). */
  children: Map<string, TreeNode>
  /** File-based routes: HTTP method → import alias (`InferResponse<typeof alias>`). */
  methods: Map<HttpMethod, string>
  /** Decorator controllers: HTTP method → class alias + method (`Awaited<ReturnType<...>>`). */
  controllerMethods: Map<HttpMethod, ControllerLeaf>
  /** Whether any descendant declares dynamic params (for params type construction). */
  paramNamesAccumulated: string[]
}

function makeNode(): TreeNode {
  return {
    children: new Map(),
    methods: new Map(),
    controllerMethods: new Map(),
    paramNamesAccumulated: [],
  }
}

/**
 * Normalize a path segment to a valid TS identifier when possible.
 * EC-2: kebab-case → camelCase; pure dynamic (`:name`) → identifier `name`;
 * starts with digit or unsafe char → emit as bracket-access key.
 */
function normalizeSegment(raw: string): { identifier: string; bracket: boolean } {
  // Dynamic segment: leading `:` (e.g. `:id` or `:...slug`).
  let s = raw
  if (s.startsWith(':...')) s = s.slice(4)
  else if (s.startsWith(':')) s = s.slice(1)

  // kebab → camel
  const camel = s.replace(/-([a-z0-9])/gi, (_, c: string) => c.toUpperCase())

  // Valid TS identifier (cannot start with digit, must be [a-zA-Z_$][a-zA-Z0-9_$]*)
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(camel)) {
    return { identifier: camel, bracket: false }
  }
  // Fallback: bracket-access (keep raw form intact for JSON-string key)
  return { identifier: s, bracket: true }
}

function importPathFor(dtsOutPath: string, routeFileAbs: string): string {
  let rel = relative(dirname(dtsOutPath), routeFileAbs)
  // EC-8: normalize Windows path separators.
  rel = rel.replace(/\\/g, '/')
  // Strip extension (`.ts` / `.tsx`); TS module resolution likes extensionless.
  rel = rel.replace(/\.[jt]sx?$/, '')
  if (!rel.startsWith('.') && !rel.startsWith('/')) {
    rel = './' + rel
  }
  return rel
}

/**
 * Convert a route path (e.g. `/api/users/:id/posts`) into the tree segments
 * we want under the `client` root. Strips the `/api/` prefix and splits.
 */
function routePathSegments(routePath: string): string[] {
  let p = routePath
  if (p.startsWith('/api/')) p = p.slice(5)
  else if (p.startsWith('/api')) p = p.slice(4)
  if (p.startsWith('/')) p = p.slice(1)
  if (p === '') return []
  return p.split('/').filter(Boolean)
}

function paramNamesFromRoute(routePath: string): string[] {
  const out: string[] = []
  const re = /:(?:\.\.\.)?([^/]+)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(routePath)) !== null) {
    out.push(m[1])
  }
  return out
}

interface BuildContext {
  root: TreeNode
  /** Sequential index per route file for aliasing imports. */
  aliasCounter: { value: number }
  /** Lines emitted at the top of the declared module (one per route file). */
  importLines: string[]
  /** Diagnostic warnings rendered as block comments inside the declared module. */
  warnings: string[]
  dtsOutPath: string
  serverDir: string
}

function buildOneRoute(route: ManifestRoute, ctx: BuildContext): void {
  if (!route.methods || route.methods.length === 0) return
  // Build alias prefix once per route file (`_r0`, `_r1`, ...).
  const idx = ctx.aliasCounter.value++
  // Resolve absolute path for the route file (manifest stores it relative to serverDir).
  const absRouteFile = isAbsolute(route.filePath)
    ? route.filePath
    : resolve(ctx.serverDir, route.filePath)
  const importPath = importPathFor(ctx.dtsOutPath, absRouteFile)
  const aliases = route.methods
    .filter((m): m is HttpMethod => (HTTP_METHODS as readonly string[]).includes(m))
    .map((method) => ({ method, alias: `_r${idx}_${method}` }))
  if (aliases.length === 0) return
  const importClause = aliases.map((a) => `${a.method} as ${a.alias}`).join(', ')
  ctx.importLines.push(`  import type { ${importClause} } from '${importPath}'`)

  // Walk segments + register methods at the leaf node.
  const segments = routePathSegments(route.routePath)
  let node = ctx.root
  for (const seg of segments) {
    const norm = normalizeSegment(seg)
    let child = node.children.get(norm.identifier)
    if (child === undefined) {
      child = makeNode()
      node.children.set(norm.identifier, child)
    }
    node = child
  }
  // Accumulated param names for typed params (e.g. `{ id: string }`).
  node.paramNamesAccumulated = paramNamesFromRoute(route.routePath)

  // Register each HTTP method (collision detection runs in a post-pass).
  for (const { method, alias } of aliases) {
    if (node.methods.has(method)) {
      ctx.warnings.push(
        `// WARNING: duplicate ${method} export at /${segments.join('/')} (route file declared twice). Keeping last definition.`,
      )
    }
    node.methods.set(method, alias)
  }
}

/**
 * #122 (T2.1) — register one decorator-controller route into the tree. The class
 * import alias is shared across the class's methods (resolved by the caller). A
 * file-based route at the same node+verb WINS (file routes are the default); the
 * controller entry is skipped with a warning to keep the emitted `.d.ts` valid.
 */
function buildOneController(cr: ControllerRouteData, classAlias: string, ctx: BuildContext): void {
  const verb = cr.verb.toUpperCase()
  if (!(HTTP_METHODS as readonly string[]).includes(verb)) return
  const method = verb as HttpMethod

  const segments = routePathSegments(cr.fullPath)
  let node = ctx.root
  for (const seg of segments) {
    const norm = normalizeSegment(seg)
    let child = node.children.get(norm.identifier)
    if (child === undefined) {
      child = makeNode()
      node.children.set(norm.identifier, child)
    }
    node = child
  }
  node.paramNamesAccumulated = paramNamesFromRoute(cr.fullPath)

  if (node.methods.has(method)) {
    ctx.warnings.push(
      `WARNING (#122): controller ${cr.className}.${cr.methodName} (${method} /${segments.join('/')}) collides with a file-based route at the same path; file route wins.`,
    )
    return
  }
  node.controllerMethods.set(method, { classAlias, methodName: cr.methodName })
}

/**
 * EC-3: walk the tree post-build and resolve any node where a method's
 * lowercase name clashes with a child segment. HTTP method wins (more common);
 * the offending child gets a `_` suffix + a warning entry.
 */
function resolveCollisions(node: TreeNode, pathPrefix: string, warnings: string[]): void {
  const methodLowerNames = new Set<string>()
  for (const method of node.methods.keys()) {
    methodLowerNames.add(method.toLowerCase())
  }
  for (const method of node.controllerMethods.keys()) {
    methodLowerNames.add(method.toLowerCase())
  }
  const renames: { from: string; to: string }[] = []
  for (const childName of node.children.keys()) {
    if (methodLowerNames.has(childName)) {
      renames.push({ from: childName, to: `${childName}_` })
    }
  }
  for (const { from, to } of renames) {
    const old = node.children.get(from)
    if (old !== undefined) {
      node.children.delete(from)
      node.children.set(to, old)
      warnings.push(
        `WARNING (EC-3): path collision — method '${from}' clashed with sub-namespace at ${pathPrefix}/${from}; sub-namespace renamed to '${to}'.`,
      )
    }
  }
  // Recurse into all children (including the renamed ones).
  for (const [name, child] of node.children) {
    resolveCollisions(child, `${pathPrefix}/${name}`, warnings)
  }
}

function renderTreeNode(node: TreeNode, indent: string, _isRoot: boolean): string {
  // _isRoot is reserved for callers; current rendering is uniform across roots
  // and children (both open with `{`). Kept in the signature for future overrides.
  const lines: string[] = ['{']
  // Methods first
  for (const [method, alias] of node.methods) {
    const lower = method.toLowerCase()
    // Routes with path params (`:id`, `:name`) emit a `{ params: {...} }` object
    // intersected with TheoFetchOptions. Without the outer `{...}` wrap the
    // generated signature `(opts: params: {...} & ...)` is invalid TS syntax
    // (parser reads `params:` as a parameter label, then `{...}` as type — invalid).
    const paramsList = node.paramNamesAccumulated.map((p) => `${p}: string`).join('; ')
    const paramsField =
      node.paramNamesAccumulated.length > 0 ? `{ params: { ${paramsList} } } & ` : ''
    const optionalMark = node.paramNamesAccumulated.length === 0 ? '?' : ''
    lines.push(
      `${indent}  ${lower}: (opts${optionalMark}: ${paramsField}import('theokit/client').TheoFetchOptions<typeof ${alias}>) => Promise<import('theokit/client').InferResponse<typeof ${alias}>>`,
    )
  }
  // #122 (T2.1) — decorator-controller methods. Response inferred via
  // `Awaited<ReturnType<...>>`; body is `unknown` (ADR-2 checkpoint — @Body types
  // are not recoverable from the class type). params typed from the route pattern.
  for (const [method, leaf] of node.controllerMethods) {
    const lower = method.toLowerCase()
    const paramsList = node.paramNamesAccumulated.map((p) => `${p}: string`).join('; ')
    const paramsField =
      node.paramNamesAccumulated.length > 0 ? `{ params: { ${paramsList} } } & ` : ''
    const optionalMark = node.paramNamesAccumulated.length === 0 ? '?' : ''
    lines.push(
      `${indent}  ${lower}: (opts${optionalMark}: ${paramsField}{ body?: unknown; query?: Record<string, string> }) => Promise<Awaited<ReturnType<InstanceType<typeof ${leaf.classAlias}>['${leaf.methodName}']>>>`,
    )
  }
  // Children
  for (const [name, child] of node.children) {
    const propKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)
      ? name
      : `'${name.replace(/'/g, "\\'")}'`
    lines.push(`${indent}  ${propKey}: ${renderTreeNode(child, indent + '  ', false)}`)
  }
  lines.push(`${indent}}`)
  return lines.join('\n')
}

export interface GenerateClientDtsOptions {
  manifest: TheoManifest
  /** Absolute path to the .d.ts that will be emitted. Used to compute import paths. */
  dtsOutPath: string
  /** Absolute serverDir; manifest's filePath entries are relative to this. */
  serverDir: string
  /**
   * #122 (T2.1) — decorator-controller routes (from `collectControllerRouteData`),
   * merged into the same `client.<ns>.<method>()` tree as file routes. Absent/empty
   * → zero controller output (ADR-5 routes-only byte-identity).
   */
  controllerRoutes?: ControllerRouteData[]
}

export function generateClientDts({
  manifest,
  dtsOutPath,
  serverDir,
  controllerRoutes,
}: GenerateClientDtsOptions): string {
  const ctx: BuildContext = {
    root: makeNode(),
    aliasCounter: { value: 0 },
    importLines: [],
    warnings: [],
    dtsOutPath,
    serverDir,
  }
  for (const route of manifest.routes) {
    buildOneRoute(route, ctx)
  }
  // #122 (T2.1) — merge decorator controllers into the same tree. One import
  // alias per class (shared across its methods), keyed by source file.
  if (controllerRoutes?.length) {
    const classAliases = new Map<string, string>()
    for (const cr of controllerRoutes) {
      let alias = classAliases.get(cr.filePath)
      if (alias === undefined) {
        alias = `_c${classAliases.size}`
        classAliases.set(cr.filePath, alias)
        const importPath = importPathFor(dtsOutPath, cr.filePath)
        ctx.importLines.push(`  import type { ${cr.className} as ${alias} } from '${importPath}'`)
      }
      buildOneController(cr, alias, ctx)
    }
  }
  // EC-3: resolve collisions in a post-build pass (collisions materialize
  // when two routes are both processed, not during a single route's build).
  resolveCollisions(ctx.root, '', ctx.warnings)

  const importsBlock = ctx.importLines.length > 0 ? ctx.importLines.join('\n') + '\n\n' : '\n'
  const warningsBlock =
    ctx.warnings.length > 0 ? '  // ' + ctx.warnings.join('\n  // ') + '\n\n' : ''

  // Empty manifest (no routes with methods) → emit a stub interface so consumers
  // still get `client.X` autocomplete-friendly errors instead of "Module not found".
  const treeBody =
    ctx.root.children.size === 0 &&
    ctx.root.methods.size === 0 &&
    ctx.root.controllerMethods.size === 0
      ? '{\n    // No routes detected — add `server/routes/*.ts` to populate this client.\n  }'
      : renderTreeNode(ctx.root, '  ', /* isRoot */ true)

  return `${FILE_HEADER}
declare module '@theo/client' {
${importsBlock}${warningsBlock}  export interface AppClient ${treeBody}
  export const client: AppClient
}
`
}

// ─────────────────────────────────────────────────────────────────────────────
// Phase 4 — Vite plugin
// ─────────────────────────────────────────────────────────────────────────────

export interface AppTypedClientPluginOptions {
  /** Project root (cwd). */
  cwd: string
  /** Absolute path to the user's `server/` dir. */
  serverDir: string
  /** Absolute path to the `.theokit/` output dir (where `client.d.ts` lands). */
  distDir: string
  /**
   * Additional routes to merge into the typed client alongside file-system routes.
   * Each entry follows ManifestRoute shape (filePath, routePath, methods, paramNames).
   *
   * Used by `@theokit/http` `httpDecoratorsPlugin` to inject
   * decorator-defined routes — zero coupling between theokit core and the
   * decorator package (the walk happens in http-decorators; only data arrives here).
   */
  extraRoutes?: ManifestRoute[]
}

const VIRTUAL_APP_CLIENT_ID = '@theo/client'
const RESOLVED_APP_CLIENT_ID = '\0@theo/client'

/**
 * Should a watcher file event under `routes/` or `controllers/` trigger a client
 * re-emit? Ignores the `.__decorated__.mjs` temp files that `loadControllerWithSwc`
 * writes+unlinks during controller codegen — reacting to them would create a
 * perpetual emit→temp-write→watcher→emit loop (#122 T2.1).
 */
export function shouldReemitForFile(
  file: string,
  routesGlob: string,
  controllersGlob: string,
): boolean {
  const normalized = file.replace(/\\/g, '/')
  if (normalized.includes('.__decorated__.')) return false
  return normalized.startsWith(routesGlob) || normalized.startsWith(controllersGlob)
}

/** Atomic write via tmp + rename (EC-6). Skips when content is unchanged. */
function writeFileIfChanged(filePath: string, content: string): { changed: boolean } {
  if (existsSync(filePath)) {
    try {
      const current = readFileSync(filePath, 'utf-8')
      if (current === content) return { changed: false }
    } catch {
      // fall through to write
    }
  }
  mkdirSync(dirname(filePath), { recursive: true })
  const tmp = `${filePath}.${process.pid}.tmp`
  writeFileSync(tmp, content)
  renameSync(tmp, filePath)
  return { changed: true }
}

async function emitClientDts(
  opts: AppTypedClientPluginOptions,
): Promise<{ changed: boolean; path: string }> {
  if (!existsSync(opts.serverDir)) {
    // No server dir — emit empty stub to avoid "module not found".
    const stubPath = posix.join(opts.distDir.replace(/\\/g, '/'), 'client.d.ts')
    return {
      changed: writeFileIfChanged(
        stubPath,
        generateClientDts({
          manifest: {
            version: 1,
            generatedAt: new Date().toISOString(),
            routes: [],
            actions: [],
            websockets: [],
          },
          dtsOutPath: stubPath,
          serverDir: opts.serverDir,
        }),
      ).changed,
      path: stubPath,
    }
  }
  const manifest = generateManifest(opts.serverDir)

  // Decorator-client-bridge: merge extra routes (from @theokit/http
  // or any other source) into the manifest so generateClientDts() produces a
  // SINGLE typed client covering both file-system routes AND injected routes.
  if (opts.extraRoutes?.length) {
    manifest.routes.push(...opts.extraRoutes)
  }

  // #122 (T2.1) — merge decorator controllers under `<serverDir>/controllers/`
  // into the same typed client. Zero output when the dir is absent/empty (ADR-5).
  const controllersDir = resolve(opts.serverDir, 'controllers')
  const controllerRoutes = existsSync(controllersDir)
    ? await collectControllerRouteData({ controllersDir })
    : []

  const dtsOutPath = posix.join(opts.distDir.replace(/\\/g, '/'), 'client.d.ts')
  const content = generateClientDts({
    manifest,
    dtsOutPath,
    serverDir: opts.serverDir,
    controllerRoutes,
  })
  const { changed } = writeFileIfChanged(dtsOutPath, content)
  return { changed, path: dtsOutPath }
}

export function appTypedClientPlugin(opts: AppTypedClientPluginOptions): Plugin {
  let debounceTimer: NodeJS.Timeout | undefined
  let viteServer: ViteDevServer | undefined

  function scheduleEmit(): void {
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      void (async () => {
        try {
          await emitClientDts(opts)
          // Invalidate the virtual module so re-imports pick up potential new shape.
          if (viteServer) {
            const mod = viteServer.moduleGraph.getModuleById(RESOLVED_APP_CLIENT_ID)
            if (mod) viteServer.moduleGraph.invalidateModule(mod)
          }
        } catch (err) {
          // Surface but don't crash dev server.
          console.error('[theokit:app-typed-client] codegen error:', err)
        }
      })()
    }, 100)
  }

  return {
    name: 'theokit:app-typed-client',
    enforce: 'post',
    async configResolved() {
      try {
        await emitClientDts(opts)
      } catch (err) {
        console.error('[theokit:app-typed-client] initial codegen error:', err)
      }
    },
    async buildEnd() {
      try {
        await emitClientDts(opts)
      } catch (err) {
        console.error('[theokit:app-typed-client] buildEnd codegen error:', err)
      }
    },
    configureServer(server) {
      viteServer = server
      const routesGlob = posix.join(opts.serverDir.replace(/\\/g, '/'), 'routes')
      const controllersGlob = posix.join(opts.serverDir.replace(/\\/g, '/'), 'controllers')
      const onFile = (file: string): void => {
        if (shouldReemitForFile(file, routesGlob, controllersGlob)) scheduleEmit()
      }
      server.watcher.on('add', onFile)
      server.watcher.on('change', onFile)
      server.watcher.on('unlink', onFile)
    },
    resolveId(id) {
      if (id === VIRTUAL_APP_CLIENT_ID) return RESOLVED_APP_CLIENT_ID
      return null
    },
    load(id) {
      if (id === RESOLVED_APP_CLIENT_ID) {
        return [
          `import { createAppClient } from 'theokit/client'`,
          `export const client = createAppClient()`,
          `export default client`,
          ``,
        ].join('\n')
      }
      return null
    },
  }
}

export { VIRTUAL_APP_CLIENT_ID, RESOLVED_APP_CLIENT_ID, emitClientDts }
