/**
 * Virtual modules resolveId + load extraction (T2.6 / M6).
 *
 * Pure structural split — every branch identity preserved from the
 * original inline body in `theoPlugin()`. The dispatcher is purely
 * synchronous; effects (broadcast, transformer wiring) keep their
 * original ordering so EC-10 (Vite hook ordering side effects) is
 * honored.
 */

import { broadcastRouteManifest } from '../devtools/server-side/route-manifest.js'
import { generateEntryServer } from '../router/entry-server.js'
import { generateEntryClient } from '../router/entry.js'
import { generateRouteManifest } from '../router/generate.js'
import { scanRoutes } from '../router/scan.js'
import type { TheoTransformer } from '../server/transformer.js'

import { DEVTOOLS_RESOLVED_ID, DEVTOOLS_VIRTUAL_ID } from './inject-devtools.js'
import type { TheoUiDetectResult } from './theoui-detect.js'

export interface VirtualModuleIds {
  VIRTUAL_ENTRY_ID: string
  RESOLVED_ENTRY_ID: string
  VIRTUAL_MANIFEST_ID: string
  RESOLVED_MANIFEST_ID: string
  VIRTUAL_ENTRY_SERVER_ID: string
  RESOLVED_ENTRY_SERVER_ID: string
  VIRTUAL_RUNTIME_CONFIG_ID: string
  RESOLVED_RUNTIME_CONFIG_ID: string
}

interface VirtualModulesCtx {
  ids: VirtualModuleIds
  appDir: string
  ssrEnabled: boolean
  streamingEnabled: boolean
  theoUi: TheoUiDetectResult | undefined
  transformer: TheoTransformer | undefined
}

export function resolveVirtualModuleId(id: string, ids: VirtualModuleIds): string | undefined {
  if (id === ids.VIRTUAL_ENTRY_ID) return ids.RESOLVED_ENTRY_ID
  if (id === ids.VIRTUAL_MANIFEST_ID) return ids.RESOLVED_MANIFEST_ID
  if (id === ids.VIRTUAL_ENTRY_SERVER_ID) return ids.RESOLVED_ENTRY_SERVER_ID
  if (id === ids.VIRTUAL_RUNTIME_CONFIG_ID) return ids.RESOLVED_RUNTIME_CONFIG_ID
  // T1.2 — devtools virtual module. Only resolves in dev; build mode
  // never serves it because transformIndexHtml never injects the tag.
  if (id === DEVTOOLS_VIRTUAL_ID) return DEVTOOLS_RESOLVED_ID
  return undefined
}

export function loadVirtualModule(id: string, ctx: VirtualModulesCtx): string | undefined {
  if (id === ctx.ids.RESOLVED_ENTRY_ID) {
    return generateEntryClient(ctx.ssrEnabled, {
      theoUi: ctx.theoUi?.enabled
        ? { fonts: ctx.theoUi.config.fonts, theme: ctx.theoUi.config.theme }
        : undefined,
    })
  }
  if (id === ctx.ids.RESOLVED_MANIFEST_ID) {
    const tree = scanRoutes(ctx.appDir)
    // T3.1 — also broadcast a devtools-shaped manifest to the overlay
    // (no-op in prod / when no dev server is attached).
    broadcastRouteManifest(tree)
    return generateRouteManifest(tree)
  }
  if (id === ctx.ids.RESOLVED_ENTRY_SERVER_ID) {
    // SSR tree MUST mirror client tree shape — pass theoUi through so
    // <TheoUIProvider> wraps in both. Without this, React detects a
    // hydration mismatch and silently falls back to client-only
    // render — onClick handlers never get attached.
    return generateEntryServer({
      streaming: ctx.streamingEnabled,
      theoUi: ctx.theoUi?.enabled ? { theme: ctx.theoUi.config.theme } : undefined,
    })
  }
  if (id === ctx.ids.RESOLVED_RUNTIME_CONFIG_ID) {
    // T1.3 — set globalThis.__THEO_TRANSFORMER__ so theoFetch picks it up
    const tName = ctx.transformer?.name ?? 'json'
    return [
      `// Generated by Theo Vite plugin`,
      `;(globalThis).__THEO_TRANSFORMER__ = ${JSON.stringify(tName)}`,
      `export const TRANSFORMER_NAME = ${JSON.stringify(tName)}`,
    ].join('\n')
  }
  if (id === DEVTOOLS_RESOLVED_ID) {
    // T1.2 — virtual module re-exports the real entry from theokit's devtools subpath.
    return [
      `// Theo devtools — virtual entry (DEV only)`,
      `import('theokit/devtools/entry').catch((e) => console.error('[theo devtools] mount failed', e))`,
    ].join('\n')
  }
  return undefined
}
