// M58 — `@theokit/agents/interactive`: pass-through of the SDK's already-OO interactive surface
// (`InteractiveBackend` contract + `StartInteractiveOptions` / `StartInteractiveResult`). Re-export,
// never a wrapper (parsimony-ladder Rung 9): the backend interface is already the seam to depend on.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 9 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  InteractiveBackend,
  InteractiveUnavailableError,
  NoSuchSessionError,
  resolveInteractive,
} from '@theokit/sdk/interactive'

export type {
  InteractiveProvider,
  StartInteractiveOptions,
  StartInteractiveResult,
  WriteStdinOptions,
  WriteStdinResult,
} from '@theokit/sdk/interactive'
