// M58 — `@theokit/agents/persistence`: pass-through of the SDK's pure persistence helpers
// (`transcriptPath`, `encodeProjectDir`, `atomicWriteText`, `SessionRecord`). These are stateless
// path/IO helpers — wrapping a pure free function in a class would be the ceremony parsimony refuses
// (Rung 5). Re-export only (Rung 9); the consumer imports them from the Theokit layer.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 29 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`: enriching
// never reduces. If a symbol is ever deliberately withheld, the reason comes written here, as there.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  acquireSessionWriter,
  appendJsonl,
  applyWalWithFallback,
  atomicWriteJson,
  atomicWriteText,
  encodeProjectDir,
  forkTranscript,
  isCorruptionError,
  JsonlParseError,
  LiveSessionError,
  loadJsonl,
  openSqliteResilient,
  PersistenceSchema,
  readJsonlIds,
  readJsonlTail,
  replaceFileAtomic,
  sanitizeFts5Query,
  SessionBusyError,
  // M95 — queries without taking the lock; asking by taking it creates the contention it meant to
  // detect. Renamed from its Portuguese original in `@theokit/sdk@4.39.0`.
  sessionHasWriter,
  transcriptPath,
  // M67 — landed upstream in 4.41.0 and reached us with the floor bump. `classifySessionArtifact`
  // answers "what is this file in a project directory" — the exact question a transcript collector
  // must answer before deleting anything, and the one the roadmap's M72 was about to re-implement.
  // Crossing it here is what makes that re-implementation unnecessary (parsimony ladder, rung 2).
  atomicWriteTempTarget,
  classifySessionArtifact,
  // M94 — the root of the transcript state. The consumer duplicated it across THREE files, and all
  // three copies ignored `THEOKIT_HOME` along with the original.
  transcriptRoot,
  withCwdMutex,
  withFileLock,
} from '@theokit/sdk/persistence'

export type {
  AtomicWriteJsonOptions,
  // M67 — the return type of `classifySessionArtifact`. Without it the consumer can call the
  // function and cannot NAME what it returns, so it redeclares the union by hand — a half surface,
  // which is the exact defect the M78 `coverage: 'total'` rule exists to prevent.
  SessionArtifact,
  FileLockOptions,
  ForkTranscriptOptions,
  OpenSqliteResilientOptions,
  ReadJsonlTailOptions,
  ResilientSqliteDb,
  SessionWriterLease,
  WalApplyResult,
  // M94 — the record shape stops being `Record<string, unknown>`.
  TranscriptBlock,
  TranscriptMessage,
} from '@theokit/sdk/persistence'
