// M58 — `@theokit/agents/persistence`: pass-through of the SDK's pure persistence helpers
// (`transcriptPath`, `encodeProjectDir`, `atomicWriteText`, `SessionRecord`). These are stateless
// path/IO helpers — wrapping a pure free function in a class would be the ceremony parsimony refuses
// (Rung 5). Re-export only (Rung 9); the consumer imports them from the Theokit layer.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 29 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`: enriching
// never reduces. If a symbol is ever deliberately withheld, the reason comes written here, as there.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

// B-029 — the floor moved past 4.x, and the note below is what it unblocked.
//
// This file used to withhold `LiveTranscriptError` with its reason written in place: "It does not
// exist in the 4.x half of the range this package supports, so re-exporting it unconditionally
// fails the DTS build against 4.52.1 (measured) ... revisit when the floor moves past 4.x." The
// declared range is now `^5.0.0`, so the condition that note named is gone and the name crosses.
//
// Six more arrived with it — `legacyTranscriptPath`, `listSessions`, `ListSessionsOptions`,
// `SessionIdSource`, `SessionListing`, `sessionUuidFor` — plus `atomicWriteTempTarget`,
// `classifySessionArtifact`, `sanitizeFts5Query`, `SessionBusyError`, `sessionHasWriter` and their
// types. None of them were WITHHELD: they were unreachable, because the workspace resolved 4.52.1
// and the surface was generated from what that copy exported. A barrel generated against the
// bottom of a range is a barrel that ships the bottom of the range.

export {
  acquireSessionWriter,
  appendJsonl,
  applyWalWithFallback,
  atomicWriteJson,
  atomicWriteTempTarget,
  atomicWriteText,
  classifySessionArtifact,
  encodeProjectDir,
  forkTranscript,
  isCorruptionError,
  JsonlParseError,
  legacyTranscriptPath,
  listSessions,
  LiveSessionError,
  LiveTranscriptError,
  loadJsonl,
  openSqliteResilient,
  PersistenceSchema,
  readJsonlIds,
  readJsonlTail,
  replaceFileAtomic,
  sanitizeFts5Query,
  SessionBusyError,
  sessionHasWriter,
  sessionUuidFor,
  transcriptPath,
  transcriptRoot,
  withCwdMutex,
  withFileLock,
} from '@theokit/sdk/persistence'
export type {
  AtomicWriteJsonOptions,
  FileLockOptions,
  ForkTranscriptOptions,
  ListSessionsOptions,
  OpenSqliteResilientOptions,
  ReadJsonlTailOptions,
  ResilientSqliteDb,
  SessionArtifact,
  SessionIdSource,
  SessionListing,
  SessionWriterLease,
  TranscriptBlock,
  TranscriptMessage,
  WalApplyResult,
} from '@theokit/sdk/persistence'
