// M58 — `@theokit/agents/pty`: pass-through of `@theokit/sdk-pty`'s already-OO `PtyInteractiveBackend`
// (the PTY implementation of the `InteractiveBackend` contract). Re-export, never a wrapper
// (parsimony-ladder Rung 9). This is the one M58 domain that pulls a SEPARATE package, so `@theokit/
// sdk-pty` is declared a dependency of `@theokit/agents` — the consumer no longer depends on it directly.
// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 6 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  clampYield,
  MaxSessionsError,
  PtyInteractiveBackend,
  YIELD_MAX_MS,
  YIELD_MIN_MS,
} from '@theokit/sdk-pty'

export type { PtyInteractiveBackendOptions } from '@theokit/sdk-pty'
