// M58 — `@theokit/agents/pty`: pass-through of `@theokit/sdk-pty`'s already-OO `PtyInteractiveBackend`
// (the PTY implementation of the `InteractiveBackend` contract). Re-export, never a wrapper
// (parsimony-ladder Rung 9). This is the one M58 domain that pulls a SEPARATE package, so `@theokit/
// sdk-pty` is declared a dependency of `@theokit/agents` — the consumer no longer depends on it directly.
// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 6 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// **This entry is what makes every web application compile a terminal (B-025).** `@theokit/sdk-pty`
// is a hard `dependency` of `@theokit/agents`, and it declares
// `"install": "node scripts/prebuild.js || node-gyp rebuild"` — a native step that downloads a
// prebuild or falls back to a C++ compile. Measured on 2026-08-20: installing `@theokit/agents`
// alone takes **6.7 s** with it and **1.4 s** without, and in a scaffolded app the difference is the
// whole of the benchmark's fourth metric — 30.40 +/- 7.50 s to first green run against Next.js's
// 14.93 +/- 0.91 s, with our BUILD faster and our dependency tree SMALLER. It is what retracted J9's
// win.
//
// Moving it to an optional peer was tried on 2026-08-20 and **reverted**, because
// `tests/unit/dependency-direction.test.ts` refuses it for a reason that survives the measurement:
// `@theokit/agents` once had zero dependencies and six peers, and a peer means "the host provides
// it" — while the host is forbidden by `agents/gates/m63-boundary.test.ts` to import `@theokit/sdk*`
// at all. Asking a consumer to declare a package it may not import is the inversion M79 fixed.
//
// So the two rules genuinely conflict, and neither is wrong: one says an implementation the consumer
// cannot import must not be a peer; the other says an application should not compile a terminal it
// will never open. Resolving it needs a third shape — most likely a separate package that owns this
// subpath and its dependency — and that is a decision, not a fix. Registered as B-025.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  clampYield,
  MaxSessionsError,
  PtyInteractiveBackend,
  YIELD_MAX_MS,
  YIELD_MIN_MS,
} from '@theokit/sdk-pty'

export type { PtyInteractiveBackendOptions } from '@theokit/sdk-pty'
