// M58 — `@theokit/agents/sandbox`: pass-through of the SDK's already-OO sandbox surface
// (`LocalSandbox` class + `SandboxBackend` contract + `SandboxConfig`). The consumer imports its
// sandbox primitives from the Theokit layer, not from `@theokit/sdk/sandbox` directly. Re-export,
// never a wrapper (parsimony-ladder Rung 9): `SandboxBackend` is already the interface to depend on.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 36 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// Generated by; pinned by `tests/unit/subpath-surface.test.ts`.

// B-070 — `sandbox` here is NOT the Claude Code CLI's `sandbox.*` settings block.
//
// The two share an enforcement MECHANISM and almost nothing else. Both confine a shell command with
// bubblewrap + seccomp on Linux; what they expose above it is a different kind of thing:
//
//   this surface   an EXECUTION BACKEND an agent's tools run commands through. `SandboxBackend`
//                  with `execute`/`uploadFile`, `LocalSandbox` (no isolation) and `LinuxSandbox`
//                  (kernel confinement), selected by `createSandboxBackend`. Its policy is three
//                  modes — `read-only` | `workspace-write` | `danger-full-access` — plus
//                  `SandboxConfig` (`workDir`, `timeoutMs`, `maxOutputBytes`, `env`).
//
//   `sandbox.*`    a SETTINGS POLICY for the CLI's own Bash tool: 38 keys across network
//                  (`allowedDomains`, `deniedDomains`, `strictAllowlist`, proxy ports, TLS
//                  termination, Unix sockets), filesystem (`allowRead`/`denyRead`/`allowWrite`/
//                  `denyWrite` per path), and credentials (env-var and file masking, AWS SigV4
//                  handling). Enumerated with a per-key verdict in
//                  `docs/surfaces/sandbox-vocabulary.md`.
//
// The gap that matters is NETWORK. This surface has no network policy at all — no domain allowlist,
// no proxy, no per-path read/write lists. A checklist that greps for `sandbox`, finds this module
// and stops has just reported a network and filesystem policy that does not exist here.
//
// Stated at both ends, as the three earlier same-word collisions are: `checkpoint` (B-059),
// `MEMORY.md` (B-054), `plugins` (B-055).

// B-029 — `resetInteractiveWarnLatch` and `resetSandboxWarnLatch` are marked deprecated upstream
// ("Test seam, never intended as API. Removed in the next major; no replacement"). The deprecation
// is type-aware, so it was invisible while the workspace resolved 4.52.1 and only surfaced when the
// declared range was narrowed to `^5.0.0`.
//
// They keep crossing. M73's rule is that this layer enriches the SDK and never reduces it, and
// dropping a name a consumer may already import — to pre-empt a removal upstream has announced and
// not performed — would break them earlier than the SDK does, for nothing. When the SDK removes
// them the generator stops emitting them, the surface count moves, and `subpath-surface.test.ts`
// records the reason like every other change to that number.
//
// The suppression sits HERE rather than on the two lines, because the block below is regenerated by
// `scripts/generate-reexports.mts` and an inline comment inside it is erased on the next run — a
// suppression that deletes itself is worse than none, since it comes back as a mystery.
/* eslint-disable @typescript-eslint/no-deprecated -- upstream test seams kept for surface parity; see the note above */
export {
  allowlistedEnv,
  buildBwrapArgv,
  buildSeccompFilter,
  createSandboxBackend,
  detectBwrap,
  detectBwrapMemoized,
  interactiveWrapCommand,
  LinuxSandbox,
  LocalSandbox,
  provisionRepo,
  realProbeCount,
  realProbes,
  RepoProvisionError,
  resetBwrapMemo,
  resetInteractiveWarnLatch,
  resetSandboxWarnLatch,
  resolveSandbox,
  resolveSandboxPosture,
  restrictedSeccompPath,
  SandboxBackend,
  SandboxNotAvailableError,
  SandboxSecurityError,
  seccompPathForArch,
  wrapCommandForSandbox,
  // M67 — surfaced by the 4.49 floor bump. It states which roots a posture actually permits writing
  // to; a consumer deriving that by hand re-derives the confinement policy, which is how an
  // unconfined write becomes representable by accident.
  writableRootsFor,
} from '@theokit/sdk/sandbox'
/* eslint-enable @typescript-eslint/no-deprecated */

export type {
  BwrapArgvOptions,
  BwrapDetection,
  BwrapProbes,
  CreateSandboxBackendOptions,
  ExecuteResult,
  InteractiveWrapOptions,
  ProvisionRepoOptions,
  SandboxConfig,
  SandboxMode,
  SandboxPosture,
  SandboxProvider,
  SeccompOptions,
} from '@theokit/sdk/sandbox'
