// M58 — `@theokit/agents/sandbox`: pass-through of the SDK's already-OO sandbox surface
// (`LocalSandbox` class + `SandboxBackend` contract + `SandboxConfig`). The consumer imports its
// sandbox primitives from the Theokit layer, not from `@theokit/sdk/sandbox` directly. Re-export,
// never a wrapper (parsimony-ladder Rung 9): `SandboxBackend` is already the interface to depend on.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 36 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// Generated by `scripts/generate-reexports.mts`; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  allowlistedEnv,
  buildBwrapArgv,
  buildSeccompFilter,
  createSandboxBackend,
  detectBwrap,
  detectBwrapMemoized,
  interactiveWrapCommand,
  LinuxSandbox,
  LocalSandbox,
  provisionRepo,
  realProbeCount,
  realProbes,
  RepoProvisionError,
  resetBwrapMemo,
  resetInteractiveWarnLatch,
  resetSandboxWarnLatch,
  resolveSandbox,
  resolveSandboxPosture,
  restrictedSeccompPath,
  SandboxBackend,
  SandboxNotAvailableError,
  SandboxSecurityError,
  seccompPathForArch,
  wrapCommandForSandbox,
} from '@theokit/sdk/sandbox'

export type {
  BwrapArgvOptions,
  BwrapDetection,
  BwrapProbes,
  CreateSandboxBackendOptions,
  ExecuteResult,
  InteractiveWrapOptions,
  ProvisionRepoOptions,
  SandboxConfig,
  SandboxMode,
  SandboxPosture,
  SandboxProvider,
  SeccompOptions,
} from '@theokit/sdk/sandbox'
