// M62 — `@theokit/agents/tools`: pass-through of `@theokit/sdk-tools`'s ready-made tool factories
// (`createReadFileTool`, `createShellTool`, … + `withName`/`withDescription`). These are stateless
// third-party factories — enriching them would be reinventing the SDK-tools' own sugar (blueprint Q5),
// so this is a pure re-export (parsimony Rung 9). The consumer imports its built-in tools from the
// Theokit layer, not from `@theokit/sdk-tools` directly. `@theokit/sdk-tools` is an OPTIONAL peer —
// only consumers of this subpath need it installed.

// M90 — the list is NAMED, not `export *`.
//
// The decision not to wrap (rung 9, above) still holds: enumerating is not wrapping. What changes is
// something else — with `export *`, a symbol removed upstream simply stops existing on the surface
// and THIS layer's build passes; the consumer finds out at a call site. With explicit names, `tsc`
// points at the line. It is the property `auth-entry.ts` already had and these five did not.
//
// The surface is preserved WHOLE (measured: 93 symbols, parity identical to the source). Reducing it
// would be breaking for other consumers, and M73 already wrote the rule in `auth-entry.ts`:
// enriching never reduces. If a symbol is ever deliberately withheld, the reason comes written here.
//
// Generated by `scripts/generate-reexports.mts`; pinned by `tests/unit/subpath-surface.test.ts`.

export {
  buildEnvContext,
  buildRepoMap,
  CatastrophicCommandError,
  catastrophicShellReason,
  commandDenialReason,
  ContextMatchError,
  createApplyPatchTool,
  createBraveWebSearchAdapter,
  createCurrentTimeTool,
  createEditFileTool,
  createGenericHttpSearchAdapter,
  createGitDiffTool,
  createGitStatusTool,
  createGlobTool,
  createInteractiveShellTool,
  createListDirTool,
  createPlanModeTool,
  createQuestionTool,
  createReadFileTool,
  createRunVitestTool,
  createSearchTextTool,
  createSessionArtifactStore,
  createShellTool,
  createTodolistTool,
  createUpdatePlanTool,
  createWebFetchTool,
  createWebSearchTool,
  createWriteFileTool,
  createWriteStdinTool,
  DEFAULT_TOOL_GUIDANCE,
  denyCatastrophicCommands,
  formatCode,
  formatDiff,
  formatError,
  formatFileList,
  injectGuidance,
  isBlockedIp,
  isCommandAllowed,
  ReadTracker,
  ReasoningTools,
  RedirectBlockedError,
  renderToolList,
  replaceUnique,
  resolveAndScreen,
  screenedFetch,
  SsrfBlockedError,
  todoItemsToPlanNodes,
  truncateOutput,
  withDefaultGuidance,
  withDescription,
  withName,
  withShellExitGuidance,
  withToolResultGuidance,
} from '@theokit/sdk-tools'

export type {
  CommandPolicy,
  ContextMatchReason,
  CreateApplyPatchToolOptions,
  CreateBraveWebSearchAdapterOptions,
  CreateCurrentTimeToolOptions,
  CreateEditFileToolOptions,
  CreateGenericHttpSearchAdapterOptions,
  CreateGitDiffToolOptions,
  CreateGitStatusToolOptions,
  CreateGlobToolOptions,
  CreateInteractiveShellToolOptions,
  CreateListDirToolOptions,
  CreateReadFileToolOptions,
  CreateRunVitestToolOptions,
  CreateSearchTextToolOptions,
  CreateShellToolOptions,
  CreateWebFetchToolOptions,
  CreateWebSearchToolOptions,
  CreateWriteFileToolOptions,
  EnvContextOptions,
  PlanModeTool,
  PlanModeToolOptions,
  PlanModeToolWithStore,
  PlanNode,
  QuestionTool,
  QuestionToolOptions,
  RepoMapOptions,
  ResolveAndScreenOptions,
  ScreenedFetchOptions,
  SessionArtifactStore,
  SessionArtifactStoreOptions,
  TodoItem,
  TodolistTool,
  ToolGuidanceMap,
  TruncationMode,
  TruncationOptions,
  TruncationResult,
  VitestSummary,
  WebSearchCallback,
  WebSearchResult,
} from '@theokit/sdk-tools'
