export function generateEntryServer(): string {
  return [
    `import React from 'react'`,
    `import { renderToPipeableStream } from 'react-dom/server'`,
    `import { createStaticHandler, createStaticRouter, StaticRouterProvider } from 'react-router'`,
    `import { PassThrough } from 'node:stream'`,
    `import { routes } from '/@theo/route-manifest'`,
    ``,
    `export async function render(url) {`,
    `  const handler = createStaticHandler(routes)`,
    `  const request = new Request('http://localhost' + url)`,
    `  const context = await handler.query(request)`,
    ``,
    `  if (context instanceof Response) {`,
    `    return { redirect: context }`,
    `  }`,
    ``,
    `  const router = createStaticRouter(handler.dataRoutes, context)`,
    `  const app = React.createElement(StaticRouterProvider, { router, context })`,
    ``,
    `  return new Promise((resolve, reject) => {`,
    `    let html = ''`,
    `    const passthrough = new PassThrough()`,
    `    passthrough.on('data', (chunk) => { html += chunk.toString() })`,
    `    passthrough.on('end', () => { resolve(html) })`,
    `    passthrough.on('error', reject)`,
    ``,
    `    const { pipe } = renderToPipeableStream(app, {`,
    `      onAllReady() { pipe(passthrough) },`,
    `      onShellError(err) { reject(err) },`,
    `      onError(err) { console.error('[SSR Error]', err) },`,
    `    })`,
    `  })`,
    `}`,
  ].join('\n')
}
