export interface EntryServerOptions {
  /** When true, emit a streaming entry using onShellReady + signal cleanup.
   *  When false (default), emit the legacy single-shot onAllReady entry. */
  streaming?: boolean
}

export function generateEntryServer(options: EntryServerOptions = {}): string {
  if (options.streaming) {
    return generateStreamingEntry()
  }
  return generateSingleShotEntry()
}

function generateSingleShotEntry(): string {
  return [
    `import React from 'react'`,
    `import { renderToPipeableStream } from 'react-dom/server'`,
    `import { createStaticHandler, createStaticRouter, StaticRouterProvider } from 'react-router'`,
    `import { PassThrough } from 'node:stream'`,
    `import { routes } from '/@theo/route-manifest'`,
    ``,
    `export async function render(url, options = {}) {`,
    `  const handler = createStaticHandler(routes)`,
    `  const request = new Request('http://localhost' + url)`,
    `  const context = await handler.query(request)`,
    ``,
    `  if (context instanceof Response) {`,
    `    return { redirect: context }`,
    `  }`,
    ``,
    `  const router = createStaticRouter(handler.dataRoutes, context)`,
    `  const app = React.createElement(StaticRouterProvider, { router, context })`,
    ``,
    `  return new Promise((resolve, reject) => {`,
    `    let html = ''`,
    `    const passthrough = new PassThrough()`,
    `    passthrough.on('data', (chunk) => { html += chunk.toString() })`,
    `    passthrough.on('end', () => { resolve(html) })`,
    `    passthrough.on('error', reject)`,
    ``,
    `    const { pipe } = renderToPipeableStream(app, {`,
    `      onAllReady() { pipe(passthrough) },`,
    `      onShellError(err) { reject(err) },`,
    `      onError(err) { console.error('[SSR Error]', err) },`,
    `    })`,
    `  })`,
    `}`,
  ].join('\n')
}

function generateStreamingEntry(): string {
  return [
    `import React from 'react'`,
    `import { renderToPipeableStream, renderToReadableStream } from 'react-dom/server'`,
    `import { createStaticHandler, createStaticRouter, StaticRouterProvider } from 'react-router'`,
    `import { routes } from '/@theo/route-manifest'`,
    ``,
    `// T2.3 — Web Standards streaming entry for edge runtimes (Cloudflare,`,
    `// Bun, Deno, Vercel Edge). Uses renderToReadableStream and returns a`,
    `// Response with the stream as body. Honors request.signal for client`,
    `// disconnect cleanup.`,
    `export async function renderStreamingWeb(request, options = {}) {`,
    `  const handler = createStaticHandler(routes)`,
    `  const url = new URL(request.url)`,
    `  const context = await handler.query(request)`,
    ``,
    `  if (context instanceof Response) {`,
    `    return context`,
    `  }`,
    ``,
    `  const router = createStaticRouter(handler.dataRoutes, context)`,
    `  const app = React.createElement(StaticRouterProvider, { router, context })`,
    ``,
    `  const stream = await renderToReadableStream(app, {`,
    `    signal: request.signal,`,
    `    onError(err) { console.error('[SSR Web Stream Error]', err) },`,
    `  })`,
    `  return new Response(stream, {`,
    `    status: 200,`,
    `    headers: {`,
    `      'Content-Type': 'text/html; charset=utf-8',`,
    `      'Transfer-Encoding': 'chunked',`,
    `    },`,
    `  })`,
    `}`,
    ``,
    `// T6.1 — Node streaming SSR entry (opt-in via theo.config.ts > ssrStreaming: true)`,
    `// Flushes the shell as soon as it's ready, then streams Suspense boundaries.`,
    `// EC-11: respects request.signal for client-disconnect cleanup.`,
    `export async function renderStreaming(url, response, options = {}) {`,
    `  const handler = createStaticHandler(routes)`,
    `  const request = new Request('http://localhost' + url, { signal: options.signal })`,
    `  const context = await handler.query(request)`,
    ``,
    `  if (context instanceof Response) {`,
    `    return { redirect: context }`,
    `  }`,
    ``,
    `  const router = createStaticRouter(handler.dataRoutes, context)`,
    `  const app = React.createElement(StaticRouterProvider, { router, context })`,
    ``,
    `  return new Promise((resolve, reject) => {`,
    `    let didError = false`,
    `    const stream = renderToPipeableStream(app, {`,
    `      onShellReady() {`,
    `        // Flush shell immediately; Suspense boundaries stream after.`,
    `        response.statusCode = didError ? 500 : 200`,
    `        response.setHeader('Content-Type', 'text/html; charset=utf-8')`,
    `        response.setHeader('Transfer-Encoding', 'chunked')`,
    `        stream.pipe(response)`,
    `        resolve({ streaming: true })`,
    `      },`,
    `      onShellError(err) {`,
    `        // Error before shell — fall back to 500 and reject so caller can`,
    `        // emit a synchronous error response.`,
    `        reject(err)`,
    `      },`,
    `      onError(err) {`,
    `        didError = true`,
    `        console.error('[SSR Stream Error]', err)`,
    `      },`,
    `    })`,
    ``,
    `    // EC-11: client disconnect cleanup`,
    `    if (options.signal) {`,
    `      options.signal.addEventListener('abort', () => {`,
    `        stream.abort()`,
    `      })`,
    `    }`,
    `  })`,
    `}`,
    ``,
    `// Backward compatibility: keep the single-shot render export available so`,
    `// callers that always used 'render()' don't break when streaming is on.`,
    `export async function render(url, options = {}) {`,
    `  const handler = createStaticHandler(routes)`,
    `  const request = new Request('http://localhost' + url)`,
    `  const context = await handler.query(request)`,
    ``,
    `  if (context instanceof Response) {`,
    `    return { redirect: context }`,
    `  }`,
    ``,
    `  const router = createStaticRouter(handler.dataRoutes, context)`,
    `  const app = React.createElement(StaticRouterProvider, { router, context })`,
    ``,
    `  const { PassThrough } = await import('node:stream')`,
    `  return new Promise((resolve, reject) => {`,
    `    let html = ''`,
    `    const passthrough = new PassThrough()`,
    `    passthrough.on('data', (chunk) => { html += chunk.toString() })`,
    `    passthrough.on('end', () => { resolve(html) })`,
    `    passthrough.on('error', reject)`,
    ``,
    `    const { pipe } = renderToPipeableStream(app, {`,
    `      onAllReady() { pipe(passthrough) },`,
    `      onShellError(err) { reject(err) },`,
    `      onError(err) { console.error('[SSR Error]', err) },`,
    `    })`,
    `  })`,
    `}`,
  ].join('\n')
}
