import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { describe, expect, it } from 'vitest'

/**
 * The coverage policy, extended to the axis that had none: the SDK's PACKAGE FAMILY.
 *
 * ## The hole this file closes
 *
 * `subpath-coverage.test.ts` demands an `in`/`out` verdict with a written reason for each of the 34
 * subpaths `@theokit/sdk` publishes, and its header explains why a verdict beats an allowlist:
 * without one, "nobody has decided yet" is indistinguishable from "we decided it stays out".
 * `root-bar-coverage.test.ts` did the same for the root bar after nine consecutive minors added
 * symbols there with no signal (ADR 0005).
 *
 * Both stop at `@theokit/sdk`. The workspace publishes a FAMILY, and a sibling package can appear,
 * grow a public surface and never once be considered here — which is the same defect one axis out.
 *
 * Measured 2026-09-18 from the capability map this package already installs: 1228 public symbols
 * across the family, of which this layer consumes three packages. Eight are referenced zero times,
 * and until this file existed not one of the eight had a verdict anywhere.
 *
 * ## The enumeration source is the SDK's own generated manifest
 *
 * `@theokit/sdk` ships `docs/harness-capability-map.md`, generated by `tools/generate-capability-map.mjs`
 * in the SDK repository, and every package in the family is a `## ` heading in it. Reading it here
 * means the list cannot silently fall behind: a newly published sibling appears in the map on the
 * next SDK bump and breaks this test ONCE.
 *
 * A hand-kept copy was the alternative and it is the one thing that cannot work — a list maintained
 * beside the thing it describes drifts from it, which is what this whole family of tests exists to
 * catch.
 */

const require_ = createRequire(import.meta.url)

/** In: the layer consumes it, and something here imports it. */
interface Inside {
  readonly verdict: 'in'
  /** Where the consumption is, for a reader tracing the decision back to code. */
  readonly via: string
}

/** Out: the layer does not re-expose it, and the reason is written down. */
interface Fora {
  readonly verdict: 'out'
  readonly reason: string
}

type Decision = Inside | Fora

/**
 * The decision list. Every package the capability map names appears here.
 *
 * Adding a package to the family and not to this list breaks
 * `test_every_sdk_family_package_has_a_verdict` — deliberately.
 *
 * ## Where these twelve verdicts came from, stated rather than implied
 *
 * They were written on 2026-09-18, in one pass, from the measurement: three packages are imported by
 * name in this layer and nine are referenced zero times. Each `out` reason is the reading of what the
 * package IS plus that measurement — not a decision recovered from a prior document, because there
 * was none.
 *
 * That makes every one of them open to revision, and it is the whole gain: before this file, changing
 * the answer for `@theokit/sdk-cache` meant nothing, because no answer was recorded. Now it is a
 * visible edit to a line that states a reason, which is the difference between a decision and an
 * absence.
 */
const DECISIONS: Record<string, Decision> = {
  // ── IN. Three packages, and each one is imported by name somewhere in this layer.
  '@theokit/sdk': {
    verdict: 'in',
    via: 'the root bar, `src/index.ts` — 422 symbols upstream, governed by `root-bar-coverage.test.ts`',
  },
  '@theokit/sdk-tools': {
    verdict: 'in',
    via: '`src/tools-entry.ts`, which imports from it by name',
  },
  '@theokit/sdk-pty': {
    verdict: 'in',
    via: '`src/pty-entry.ts` — a separate entry point precisely so a web consumer does not pay the native build (ADR 0004)',
  },

  // ── OUT. Nine, and the reason each one is out is different. That difference is the point of
  // recording decisions rather than keeping an allowlist.
  '@theokit/acp': {
    verdict: 'out',
    reason:
      'An Agent Client Protocol server is a process an operator runs, not a capability a web framework re-exposes. Re-exporting its options types would put a transport this layer never speaks into the surface a consumer reads.',
  },
  '@theokit/cli': {
    verdict: 'out',
    reason:
      "The evaluation CLI's own surface — `CLI_VERSION`, `EvalConfig`, `DatasetEntry`. A framework re-exporting another tool's CLI types would make its own boundary a directory of everything the workspace happens to publish.",
  },
  '@theokit/memory-honcho': {
    verdict: 'out',
    reason:
      "A vendor-specific memory adapter. Re-exposing one adapter through the framework picks the vendor on the consumer's behalf; a consumer that wants Honcho installs Honcho, and the seam it plugs into is the SDK's, not this layer's.",
  },
  '@theokit/memory-mem0': {
    verdict: 'out',
    reason:
      'Same reasoning as `memory-honcho`, and it is worth writing twice rather than referring: three vendor adapters exist, and a reader deciding about one should not have to find the decision under another.',
  },
  '@theokit/memory-supermemory': {
    verdict: 'out',
    reason:
      'Same reasoning as `memory-honcho`. Out because the choice of memory vendor belongs to whoever runs the agent, and this layer would be making it for them by re-exporting.',
  },
  '@theokit/sdk-budget': {
    verdict: 'out',
    reason:
      "Cost accounting for a running agent — `charge`, `chargeAndCheckThresholds`, `BUILTIN_PRICING`. It belongs to whoever runs the loop and pays for it, and nothing in this layer runs one on a consumer's behalf.",
  },
  '@theokit/sdk-cache': {
    verdict: 'out',
    reason:
      'An embedding cache. This framework already ships a cache engine of its own (`packages/theo/src/cache/engine-singleton.ts`), and re-exposing a second cache vocabulary through the same layer would give a consumer two answers to one question.',
  },
  '@theokit/sdk-handoff': {
    verdict: 'out',
    reason:
      'Agent-to-agent handoff. This layer exposes delegation through its own subagent surface; carrying a second handoff vocabulary would put two ways to do one thing in front of a consumer.',
  },
  '@theokit/sdk-memory': {
    verdict: 'out',
    reason:
      "The memory STORE implementation, 164 symbols. What a consumer of this layer reaches is the `memory:` declaration on a subagent, which `config/agent-memory.ts` resolves — the store behind it is the SDK's concern and re-exporting it would make an implementation detail part of this boundary.",
  },
}

/** Every `## \`@theokit/...\`` heading in the shipped capability map. */
function familyFromCapabilityMap(): string[] {
  const mapPath = join(
    dirname(require_.resolve('@theokit/sdk/package.json')),
    'docs',
    'harness-capability-map.md',
  )
  const text = readFileSync(mapPath, 'utf8')
  return [...text.matchAll(/^## `(@theokit\/[a-z0-9-]+)`/gm)].map((m) => m[1])
}

const FAMILY = familyFromCapabilityMap()

describe('the coverage policy reaches the package axis, not only the subpath axis', () => {
  it('test_the_capability_map_was_read_at_all', () => {
    // COUNTERPROOF. A map that moved, or a regex that stopped matching, would empty FAMILY and make
    // every assertion below vacuously true — an empty result is about the query, not the subject.
    expect(
      FAMILY.length,
      'the capability map produced no package headings; the check below would pass over nothing',
    ).toBeGreaterThan(5)
  })

  it('test_every_sdk_family_package_has_a_verdict', () => {
    const withoutDecision = FAMILY.filter((p) => DECISIONS[p] === undefined)

    expect(
      withoutDecision,
      `package(s) in the @theokit family with no verdict: ${withoutDecision.join(', ')}.\n` +
        'This is intentional: a new sibling package breaks this test ONCE, and the fix is writing the ' +
        'decision into DECISIONS — including `out` with a reason. Without it, "nobody decided" and ' +
        '"decided out" are the same absence.',
    ).toEqual([])
  })

  it('test_the_list_does_not_reference_a_NONEXISTENT_package', () => {
    const stale = Object.keys(DECISIONS).filter((p) => !FAMILY.includes(p))
    expect(
      stale,
      `decision(s) for package(s) the capability map no longer names: ${stale.join(', ')}`,
    ).toEqual([])
  })

  it('test_every_OUT_verdict_has_a_non_empty_reason', () => {
    // Without this, an `out` with no reason becomes the silent allowlist the format exists to
    // prevent, and nobody revisits the decision.
    const withoutReason = Object.entries(DECISIONS)
      .filter(([, d]) => d.verdict === 'out' && (d as Fora).reason.trim().length < 20)
      .map(([p]) => p)
    expect(
      withoutReason,
      `\`out\` verdict with no written reason: ${withoutReason.join(', ')}`,
    ).toEqual([])
  })

  it('test_every_IN_verdict_names_where_it_crosses', () => {
    const withoutVia = Object.entries(DECISIONS)
      .filter(([, d]) => d.verdict === 'in' && (d as Inside).via.trim().length < 10)
      .map(([p]) => p)
    expect(
      withoutVia,
      `\`in\` verdict naming no consumption site: ${withoutVia.join(', ')}`,
    ).toEqual([])
  })
})
