/* eslint-disable security/detect-non-literal-fs-filename --
 * AWS Lambda adapter. Writes to `cwd/.theokit/lambda/`. Build-time tool.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { nodeAdapter } from './node.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

export interface AwsLambdaBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeEntry?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
}

export interface RequestShape {
  method: string
  path: string
  headers: Record<string, string>
  body?: string
}

export interface LambdaResultV2 {
  statusCode: number
  headers: Record<string, string>
  body: string
  isBase64Encoded: boolean
}

const BINARY_CONTENT_TYPES = [
  'application/octet-stream',
  'application/pdf',
  'application/zip',
  'image/',
  'audio/',
  'video/',
]

function isBinaryContentType(contentType: string | undefined): boolean {
  if (!contentType) return false
  const ct = contentType.toLowerCase()
  return BINARY_CONTENT_TYPES.some((prefix) => ct.startsWith(prefix))
}

interface APIGatewayProxyEventV2 {
  version: string
  requestContext: {
    http: { method: string; path: string }
  }
  headers?: Record<string, string | undefined>
  body?: string
  isBase64Encoded?: boolean
}

export function eventV2ToRequestShape(event: APIGatewayProxyEventV2): RequestShape {
  const headers: Record<string, string> = {}
  for (const [k, v] of Object.entries(event.headers ?? {})) {
    if (v !== undefined) headers[k] = v
  }
  let body: string | undefined = event.body
  if (body !== undefined && event.isBase64Encoded) {
    body = Buffer.from(body, 'base64').toString('utf-8')
  }
  return {
    method: event.requestContext.http.method,
    path: event.requestContext.http.path,
    headers,
    body,
  }
}

export function responseToLambdaResultV2(
  statusCode: number,
  headers: Record<string, string>,
  body: string,
): LambdaResultV2 {
  const isBinary = isBinaryContentType(headers['content-type'])
  return {
    statusCode,
    headers,
    body: isBinary ? Buffer.from(body, 'binary').toString('base64') : body,
    isBase64Encoded: isBinary,
  }
}

export function renderAwsLambdaEntry(): string {
  return [
    `// Generated by Theo — AWS Lambda Adapter`,
    `// Use with API Gateway HTTP API v2 (default).`,
    ``,
    `import { resolve } from 'node:path'`,
    `import { randomUUID } from 'node:crypto'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    ``,
    `const cwd = process.cwd()`,
    `const serverDir = resolve(cwd, 'server')`,
    `let routesCache = null`,
    `let loaderCache = null`,
    ``,
    `function eventV2ToRequest(event) {`,
    `  const method = event.requestContext?.http?.method ?? 'GET'`,
    `  const path = event.requestContext?.http?.path ?? '/'`,
    `  const host = event.headers?.host ?? 'lambda'`,
    `  const qs = event.rawQueryString ? '?' + event.rawQueryString : ''`,
    `  const url = 'https://' + host + path + qs`,
    `  const headers = new Headers()`,
    `  for (const [k, v] of Object.entries(event.headers ?? {})) {`,
    `    if (v !== undefined) headers.set(k, String(v))`,
    `  }`,
    `  let body = event.body`,
    `  if (body && event.isBase64Encoded) {`,
    `    body = Buffer.from(body, 'base64')`,
    `  }`,
    `  return new Request(url, {`,
    `    method,`,
    `    headers,`,
    `    body: method === 'GET' || method === 'HEAD' ? undefined : body,`,
    `  })`,
    `}`,
    ``,
    `// #382 — this target is DELISTED for response streaming, by construction.`,
    `// The Lambda v2 result object below carries \`body\` as a string, so the`,
    `// response cannot exist until the run has finished, no matter how the`,
    `// framework's shim writes it. Streaming here would require`,
    `// \`awslambda.streamifyResponse\` plus a Function URL in RESPONSE_STREAM`,
    `// invoke mode — neither of which this adapter emits, and which would break`,
    `// every API Gateway deployment of it. Rather than degrade in silence, a`,
    `// response that is unambiguously a stream is named in the logs below.`,
    `async function responseToV2Result(response, routePath) {`,
    `  const headers = {}`,
    `  response.headers.forEach((v, k) => { headers[k] = v })`,
    `  const ct = headers['content-type'] ?? ''`,
    `  if (ct.includes('text/event-stream')) {`,
    `    console.warn(`,
    `      '[theo][aws-lambda] ' + routePath + ' returned a streaming response (' + ct + '), ' +`,
    `      'but the aws-lambda target buffers it whole and delivers it when the run ends. ' +`,
    `      'This target is delisted for streaming (theokit#382). Deploy streaming routes to ' +`,
    `      'cloudflare, vercel, netlify, bun, deno-deploy or node.'`,
    `    )`,
    `  }`,
    `  const isBinary = /^application\\/(octet-stream|pdf|zip)|^(image|audio|video)\\//.test(ct)`,
    `  if (isBinary) {`,
    `    const buf = Buffer.from(await response.arrayBuffer())`,
    `    return {`,
    `      statusCode: response.status,`,
    `      headers,`,
    `      body: buf.toString('base64'),`,
    `      isBase64Encoded: true,`,
    `    }`,
    `  }`,
    `  return {`,
    `    statusCode: response.status,`,
    `    headers,`,
    `    body: await response.text(),`,
    `    isBase64Encoded: false,`,
    `  }`,
    `}`,
    ``,
    `export const handler = async (event) => {`,
    `  const path = event.requestContext?.http?.path ?? '/'`,
    ``,
    `  if (!path.startsWith('/api/')) {`,
    `    return {`,
    `      statusCode: 404,`,
    `      headers: { 'content-type': 'text/plain' },`,
    `      body: 'Static assets must be served from CloudFront or a separate static host.',`,
    `      isBase64Encoded: false,`,
    `    }`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `  const match = matchRoute(path, routesCache)`,
    `  if (!match) {`,
    `    return {`,
    `      statusCode: 404,`,
    `      headers: { 'content-type': 'application/json' },`,
    `      body: JSON.stringify({ error: { code: 'NOT_FOUND' } }),`,
    `      isBase64Encoded: false,`,
    `    }`,
    `  }`,
    ``,
    `  const request = eventV2ToRequest(event)`,
    `  const { req, res, toResponse } = createWebShim(request)`,
    `  const requestId = randomUUID()`,
    `  const method = request.method.toUpperCase()`,
    `  const response = await toResponse(executeRoute({ route: match.route, method, params: match.params, req, res, loadModule: loaderCache, serverDir, requestId }))`,
    `  return responseToV2Result(response, path)`,
    `}`,
  ].join('\n')
}

export async function buildAwsLambda(
  config: TheoConfig,
  cwd: string,
  deps: AwsLambdaBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('aws-lambda', readManifest(cwd))

  // #382 — refuse by name rather than build something that cannot do what was
  // asked. `ssrStreaming` is the config's declaration that responses stream,
  // and this target is delisted for that (see `awsLambdaAdapter.streamsResponses`).
  if (config.ssrStreaming) {
    throw new Error(
      '[adapter-aws-lambda] ssrStreaming is on, but the aws-lambda target does not stream ' +
        'responses: the Lambda v2 result object carries the body as a string, so nothing can ' +
        'leave the function before the run ends. Response streaming would need ' +
        'awslambda.streamifyResponse plus a Function URL in RESPONSE_STREAM invoke mode, which ' +
        'this adapter does not emit. Build a streaming target instead (cloudflare, vercel, ' +
        'netlify, bun, deno-deploy, node), or set ssrStreaming: false in theo.config.ts.',
    )
  }

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const outputDir = resolve(cwd, '.theokit/aws')
  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  ensureDir(outputDir)

  const entry = renderAwsLambdaEntry()
  const write =
    deps.writeEntry ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  write(resolve(outputDir, 'handler.mjs'), entry)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ AWS Lambda output → .theokit/aws/handler.mjs\n')
}

export const awsLambdaAdapter: DeployAdapter = {
  name: 'aws-lambda',
  // #382 — delisted for streaming, deliberately. See DeployAdapter.
  streamsResponses: false,
  build(config, cwd, ctx) {
    return buildAwsLambda(config, cwd, {}, ctx)
  },
}
