/* eslint-disable security/detect-non-literal-fs-filename --
 * Bun deploy adapter. Writes to `cwd/.theo/bun/`. Build-time.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { nodeAdapter } from './node.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

export interface BunBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeEntry?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
}

export function renderBunEntry(port: number, opts: { ssrStreaming?: boolean } = {}): string {
  const streamingComment = opts.ssrStreaming
    ? `// T2.3 — ssrStreaming on; renderStreamingWeb may be consumed by app code`
    : `// (ssrStreaming off)`
  return [
    `// Generated by Theo — Bun Adapter`,
    `// Run: bun run .theo/bun/server.mjs`,
    `// Requires Bun >= 1.1`,
    streamingComment,
    ``,
    `// EC-1: dev-mode guard`,
    `if (process.env.NODE_ENV !== 'production') {`,
    `  console.error('TheoBunAdapter is production-only. Use \\'theokit dev\\' (Node) for development.')`,
    `  process.exit(1)`,
    `}`,
    ``,
    `// Version check: Bun >= 1.1`,
    `if (typeof Bun === 'undefined') {`,
    `  console.error('TheoBunAdapter must run inside Bun. Got Node.js or unknown runtime.')`,
    `  process.exit(1)`,
    `}`,
    `{`,
    `  const [maj, min] = (Bun.version ?? '0.0').split('.').map(Number)`,
    `  if (maj < 1 || (maj === 1 && min < 1)) {`,
    `    console.error('TheoBunAdapter requires Bun >= 1.1; got ' + Bun.version)`,
    `    process.exit(1)`,
    `  }`,
    `}`,
    ``,
    `import { resolve, join } from 'node:path'`,
    `import { existsSync } from 'node:fs'`,
    `import { randomUUID } from 'node:crypto'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    `// T3.2 — WS bridge for Bun runtime`,
    `import { createBunWsBridge } from 'theokit/adapters/ws-shim'`,
    `import { scanWebSocketRoutes } from 'theokit/server'`,
    ``,
    `const cwd = process.cwd()`,
    `const clientDir = resolve(cwd, '.theo/client')`,
    `const serverDir = resolve(cwd, 'server')`,
    `const port = process.env.PORT ? Number(process.env.PORT) : ${port}`,
    ``,
    `const routes = existsSync(serverDir) ? scanServerRoutes(serverDir) : []`,
    `const wsRoutes = existsSync(serverDir) ? scanWebSocketRoutes(serverDir) : []`,
    `const loadModule = createProductionLoader()`,
    ``,
    `// Bun WebSocket config — single handler dispatches to first ws route,`,
    `// or a default no-op when none declared. Per-route routing happens above`,
    `// (the upgrade decision is made in fetch handler before Bun.serve hands off).`,
    `const wsBridge = wsRoutes.length > 0`,
    `  ? createBunWsBridge({`,
    `      onOpen: () => {},`,
    `      onMessage: (ws, data) => { ws.send(data) },`,
    `      onClose: () => {},`,
    `    })`,
    `  : { open: () => {}, message: () => {}, close: () => {} }`,
    ``,
    `function notFoundResponse() {`,
    `  return new Response(JSON.stringify({ error: { code: 'NOT_FOUND', message: 'Route not found' } }), {`,
    `    status: 404,`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `  })`,
    `}`,
    ``,
    `Bun.serve({`,
    `  port,`,
    `  websocket: wsBridge,`,
    `  async fetch(request, server) {`,
    `    const url = new URL(request.url)`,
    `    const pathname = url.pathname`,
    ``,
    `    // 1) Static assets`,
    `    const staticPath = pathname === '/' ? '/index.html' : pathname`,
    `    const fullStatic = join(clientDir, staticPath)`,
    `    if (existsSync(fullStatic)) {`,
    `      const file = Bun.file(fullStatic)`,
    `      if (await file.exists()) return new Response(file)`,
    `    }`,
    ``,
    `    // 2) API routes through the full executeRoute pipeline via the shim`,
    `    if (pathname.startsWith('/api/')) {`,
    `      const match = matchRoute(pathname, routes)`,
    `      if (!match) return notFoundResponse()`,
    `      const { req, res, toResponse } = createWebShim(request)`,
    `      const requestId = randomUUID()`,
    `      const method = request.method.toUpperCase()`,
    `      await executeRoute({ route: match.route, method, params: match.params, req, res, loadModule, serverDir, requestId })`,
    `      return toResponse()`,
    `    }`,
    ``,
    `    // 3) SPA fallback`,
    `    const indexPath = join(clientDir, 'index.html')`,
    `    if (existsSync(indexPath)) return new Response(Bun.file(indexPath))`,
    ``,
    `    return notFoundResponse()`,
    `  },`,
    `})`,
    ``,
    `console.log('Theo (Bun) listening on http://localhost:' + port)`,
  ].join('\n')
}

export async function buildBun(
  config: TheoConfig,
  cwd: string,
  deps: BunBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('bun', readManifest(cwd))

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const outputDir = resolve(cwd, '.theo/bun')
  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  ensureDir(outputDir)

  const entry = renderBunEntry(config.port, { ssrStreaming: config.ssrStreaming })
  const write =
    deps.writeEntry ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  write(resolve(outputDir, 'server.mjs'), entry)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ Bun output → .theo/bun/server.mjs\n')
}

export const bunAdapter: DeployAdapter = {
  name: 'bun',
  build(config, cwd, ctx) {
    return buildBun(config, cwd, {}, ctx)
  },
}
