/* eslint-disable security/detect-non-literal-fs-filename --
 * Bun deploy adapter. Writes to `cwd/.theokit/bun/`. Build-time.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import type { SecurityHeadersConfig } from '../core/contracts/security-headers.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { deployedCorsFragment, type DeployedCorsOptions } from './deployed-cors.js'
import { deployedCsrfFragment, type DeployedCsrfOptions } from './deployed-csrf.js'
import { planDeployedPlugins } from './deployed-plugins-module.js'
import {
  deployedRuntimeConfigFragment,
  type DeployedRuntimeConfigOptions,
} from './deployed-runtime-config.js'
import { deployedTraceFragment } from './deployed-trace.js'
import { nodeAdapter } from './node.js'
import {
  describeDeployedSecurityHeaders,
  renderSecurityHeadersConfigLiteral,
} from './security-headers.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

export interface BunBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeEntry?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
}

export function renderBunEntry(
  port: number,
  opts: {
    ssrStreaming?: boolean
    securityHeaders?: SecurityHeadersConfig
  } & DeployedCsrfOptions &
    DeployedRuntimeConfigOptions &
    DeployedCorsOptions = {},
): string {
  const streamingComment = opts.ssrStreaming
    ? `// T2.3 — ssrStreaming on; renderStreamingWeb may be consumed by app code`
    : `// (ssrStreaming off)`
  const runtimeConfig = deployedRuntimeConfigFragment(opts)
  return [
    `// Generated by Theo — Bun Adapter`,
    `// Run: bun run .theokit/bun/server.mjs`,
    `// Requires Bun >= 1.1`,
    streamingComment,
    ``,
    `// EC-1: dev-mode guard`,
    `if (process.env.NODE_ENV !== 'production') {`,
    `  console.error('TheoBunAdapter is production-only. Use \\'theokit dev\\' (Node) for development.')`,
    `  process.exit(1)`,
    `}`,
    ``,
    `// Version check: Bun >= 1.1`,
    `if (typeof Bun === 'undefined') {`,
    `  console.error('TheoBunAdapter must run inside Bun. Got Node.js or unknown runtime.')`,
    `  process.exit(1)`,
    `}`,
    `{`,
    `  const [maj, min] = (Bun.version ?? '0.0').split('.').map(Number)`,
    `  if (maj < 1 || (maj === 1 && min < 1)) {`,
    `    console.error('TheoBunAdapter requires Bun >= 1.1; got ' + Bun.version)`,
    `    process.exit(1)`,
    `  }`,
    `}`,
    ``,
    `import { resolve, join } from 'node:path'`,
    `import { existsSync } from 'node:fs'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader, extractTraceIdFromRequest, TRACE_HEADER, createCorsWebHandler } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    `import { buildSecurityHeaders, withSecurityHeaders } from 'theokit/adapters/security-headers'`,
    `// T3.2 — WS bridge for Bun runtime`,
    `import { createBunWsBridge } from 'theokit/adapters/ws-shim'`,
    `import { scanWebSocketRoutes } from 'theokit/server'`,
    ``,
    `const cwd = process.cwd()`,
    `const clientDir = resolve(cwd, '.theokit/client')`,
    `const serverDir = resolve(cwd, 'server')`,
    `const port = process.env.PORT ? Number(process.env.PORT) : ${port}`,
    ``,
    `// #410 — the security baseline \`theokit start\` puts on every response,`,
    `// carried here as a literal because the deployed process has no`,
    `// theo.config.ts to read. Bun is the one Web target whose own handler serves`,
    `// the HTML document (static file + SPA fallback below), so the document gets`,
    `// these headers too -- with a nonce-less CSP, because that HTML was written`,
    `// at build time and carries no nonce on its script tags (EC-4).`,
    `const SECURITY_HEADERS_CONFIG = ${renderSecurityHeadersConfigLiteral(opts.securityHeaders)}`,
    `const SECURITY_HEADERS = buildSecurityHeaders(SECURITY_HEADERS_CONFIG, { production: true })`,
    ``,
    ...runtimeConfig.imports,
    ...runtimeConfig.declarations,
    ...deployedCsrfFragment(opts),
    ``,
    ...deployedCorsFragment(opts.cors, 'bun'),
    ``,
    `const routes = existsSync(serverDir) ? scanServerRoutes(serverDir) : []`,
    `const wsRoutes = existsSync(serverDir) ? scanWebSocketRoutes(serverDir) : []`,
    `const loadModule = createProductionLoader()`,
    ``,
    `// Bun WebSocket config — single handler dispatches to first ws route,`,
    `// or a default no-op when none declared. Per-route routing happens above`,
    `// (the upgrade decision is made in fetch handler before Bun.serve hands off).`,
    `const wsBridge = wsRoutes.length > 0`,
    `  ? createBunWsBridge({`,
    `      onOpen: () => {},`,
    `      onMessage: (ws, data) => { ws.send(data) },`,
    `      onClose: () => {},`,
    `    })`,
    `  : { open: () => {}, message: () => {}, close: () => {} }`,
    ``,
    `function notFoundResponse() {`,
    `  return new Response(JSON.stringify({ error: { code: 'NOT_FOUND', message: 'Route not found' } }), {`,
    `    status: 404,`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `  })`,
    `}`,
    ``,
    `Bun.serve({`,
    `  port,`,
    `  websocket: wsBridge,`,
    `  async fetch(request, server) {`,
    `    // #409 — the preflight is answered BEFORE anything routes: an OPTIONS the router`,
    `    // handles is an OPTIONS the browser never gets a CORS answer to.`,
    `    const preflight = corsPreflight(request)`,
    `    if (preflight !== null) return withSecurityHeaders(preflight, SECURITY_HEADERS)`,
    `    return withCors(request, withSecurityHeaders(await handleRequest(request), SECURITY_HEADERS))`,
    `  },`,
    `})`,
    ``,
    ...bunHandleRequestFragment(runtimeConfig.executeRouteSpread),
  ].join('\n')
}

/**
 * The request handler, as generated source.
 *
 * Extracted for the reason `vercel.ts` extracts its own fragments: the emitter is one array
 * literal, so every line the entry gains counts against `max-lines-per-function`, and #410 added
 * the CSRF literal to an emitter that was already sitting exactly at the ceiling.
 */
function bunHandleRequestFragment(runtimeSpread: string): string[] {
  return [
    `async function handleRequest(request) {`,
    `    const url = new URL(request.url)`,
    `    const pathname = url.pathname`,
    ``,
    `    // 1) Static assets`,
    `    const staticPath = pathname === '/' ? '/index.html' : pathname`,
    `    const fullStatic = join(clientDir, staticPath)`,
    `    if (existsSync(fullStatic)) {`,
    `      const file = Bun.file(fullStatic)`,
    `      if (await file.exists()) return new Response(file)`,
    `    }`,
    ``,
    `    // 2) API routes through the full executeRoute pipeline via the shim`,
    `    if (pathname.startsWith('/api/')) {`,
    `      const match = matchRoute(pathname, routes)`,
    `      if (!match) return notFoundResponse()`,
    `      const { req, res, toResponse } = createWebShim(request)`,
    ...deployedTraceFragment('request', '      '),
    `      const method = request.method.toUpperCase()`,
    `      // #382 — not awaited: toResponse() settles at the headers and carries`,
    `      // a live body, so Bun.serve streams while the handler writes.`,
    `      return toResponse(executeRoute({ route: match.route, method, params: match.params, req, res, loadModule, serverDir, requestId, ...CSRF_CONFIG, ${runtimeSpread} }))`,
    `    }`,
    ``,
    `    // 3) SPA fallback`,
    `    const indexPath = join(clientDir, 'index.html')`,
    `    if (existsSync(indexPath)) return new Response(Bun.file(indexPath))`,
    ``,
    `    return notFoundResponse()`,
    `}`,
    ``,
    `console.log('Theo (Bun) listening on http://localhost:' + port)`,
  ]
}

export async function buildBun(
  config: TheoConfig,
  cwd: string,
  deps: BunBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('bun', readManifest(cwd))

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const outputDir = resolve(cwd, '.theokit/bun')
  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  ensureDir(outputDir)

  const pluginsPlan = planDeployedPlugins(config.plugins, 'bun')
  const entry = renderBunEntry(config.port, {
    ssrStreaming: config.ssrStreaming,
    securityHeaders: config.security?.headers,
    csrf: config.security?.csrf,
    disallowed: config.security?.disallowed,
    cors: config.security?.cors,
    // #425 — a selector, not a transformer, so it rides as a literal like the values above.
    serialization: config.serialization,
    // #425 — the ONE concern that is not a literal. A closure cannot be baked, so a plugin
    // declared by module specifier is imported by the emitted module instead; a constructed one
    // is refused by name at build time rather than dropped in silence.
    runtimeConfigModule: pluginsPlan?.moduleSpecifier,
  })
  const write =
    deps.writeEntry ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  if (pluginsPlan !== undefined) {
    // Beside the entry, so the emitted import is a sibling. Written through the same seam as
    // the entry so a test that captures one captures both (#425).
    write(resolve(outputDir, 'theo.plugins.mjs'), pluginsPlan.source)
  }
  write(resolve(outputDir, 'server.mjs'), entry)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ Bun output → .theokit/bun/server.mjs')
  // eslint-disable-next-line no-console -- CLI build progress
  console.log(
    `${describeDeployedSecurityHeaders({
      target: 'bun',
      securityHeaders: config.security?.headers,
      // No deploy target other than the streamed Cloudflare worker renders HTML
      // at request time, so none of the rest can mint a nonce.
      mintsNonce: false,
      // Bun serves `.theokit/client` itself, so the document DOES pass through
      // the handler these headers are attached to.
      documentServedByPlatform: false,
    })}\n`,
  )
}

export const bunAdapter: DeployAdapter = {
  name: 'bun',
  streamsResponses: true,
  // #409 / #410 — the generated entry calls `executeRoute` with routes, loader
  // and serverDir only. CSRF, route policy, file middleware and Zod validation
  // still run because they live inside `executeRoute`; none of the remaining
  // configurable concerns reach it. Declared explicitly rather than omitted so
  // the gap is a statement in the source and not an absence.
  //
  // `securityHeaders` IS applied: the entry carries `security.headers` as a
  // literal and puts the built baseline on every response, the served document
  // included.
  appliesConfig: ['securityHeaders', 'csrf', 'disallowed', 'cors', 'serialization', 'plugins'],
  build(config, cwd, ctx) {
    return buildBun(config, cwd, {}, ctx)
  },
}
