/* eslint-disable security/detect-non-literal-fs-filename --
 * Cloudflare deploy adapter. All write paths are under `cwd/.theokit/cloudflare/`
 * and `cwd/wrangler.toml`. Build-time tool — no HTTP input.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import { findRootDiv } from '../core/contracts/find-root-div.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { nodeAdapter } from './node.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

/**
 * T2.1 — Cloudflare adapter rewritten to consume `theokit/adapters/web-shim`
 * instead of emitting an inline plain-object Request/Response shim. Reduces
 * template from ~50 lines to ~25 and centralizes maintenance.
 */

/**
 * The built `index.html` split into the part before `<div id="root">` and the
 * part after it.
 *
 * Refuses by name when streaming is on and the template is missing, rather than
 * emitting a worker that serves a headless document. A build that cannot produce
 * a correct artifact should say so at build time; the alternative is a deploy
 * that looks successful and serves pages with no stylesheet.
 */
function readDocumentShell(
  cwd: string,
  streaming: boolean,
): { htmlHead?: string; htmlTail?: string } {
  if (!streaming) return {}

  const indexPath = resolve(cwd, '.theokit/client/index.html')
  if (!existsSync(indexPath)) {
    throw new Error(
      `[adapter-cloudflare] ssrStreaming is on but ${indexPath} does not exist, so the worker ` +
        `would serve a document with no <head> and no client entry. Run the client build first, ` +
        `or set ssrStreaming: false in theo.config.ts.`,
    )
  }

  const indexHtml = readFileSync(indexPath, 'utf-8')
  const rootDiv = findRootDiv(indexHtml)
  if (rootDiv === undefined) {
    throw new Error(
      `[adapter-cloudflare] ${indexPath} has no <div id="root">, so the streamed document has ` +
        `nowhere to put the app. Add one, or set ssrStreaming: false in theo.config.ts.`,
    )
  }

  return {
    htmlHead: indexHtml.slice(0, rootDiv.insertAt),
    htmlTail: indexHtml.slice(rootDiv.insertAt),
  }
}

export function renderCloudflareWorkerEntry(
  opts: { ssrStreaming?: boolean; htmlHead?: string; htmlTail?: string } = {},
): string {
  const streamingImport = opts.ssrStreaming
    ? `import { renderStreamingWeb } from '/@theo/entry-server'`
    : `// (ssrStreaming off: renderStreamingWeb not imported)`
  // #343 — the document shell is inlined as a build-time literal because a Worker
  // has no filesystem to read `index.html` from at request time. Without it,
  // `renderStreamingWeb` falls back to its empty-string defaults and the response
  // is React output with no `<html>`, no `<head>`, no stylesheet and no client
  // entry — hydration data for a page that cannot hydrate. The streaming
  // assembly was fixed in the generated entry and this, its only caller, was
  // left passing nothing.
  //
  // `JSON.stringify` and not a template literal: the shell contains quotes,
  // angle brackets and a `</script>`, and embedding it naively produces a worker
  // that fails to parse at deploy time rather than here.
  const nonApiBranch = opts.ssrStreaming
    ? [
        `      // T2.3 — streaming SSR for non-API routes`,
        `      return renderStreamingWeb(request, {`,
        `        htmlHead: ${JSON.stringify(opts.htmlHead ?? '')},`,
        `        htmlTail: ${JSON.stringify(opts.htmlTail ?? '')},`,
        `      })`,
      ].join('\n')
    : `      return notFoundResponse()`
  // CR-006: Workers lack `process.cwd()` and the `node:*` import surface
  // is brittle even under `nodejs_compat`. We use the Web Crypto
  // `crypto.randomUUID()` instead of `node:crypto.randomUUID`, and embed
  // the server directory as a build-time literal instead of resolving via
  // `node:path` at runtime.
  return [
    `// Generated by Theo — Cloudflare Workers Adapter`,
    `//`,
    `// REQUIREMENTS (EC-3):`,
    `//   - wrangler.toml MUST include compatibility_flags = ["nodejs_compat"]`,
    `//     (still required for transitive theokit/server deps, e.g. busboy)`,
    `//   - package.json MUST list "theokit" in dependencies (not devDependencies)`,
    `//     so Wrangler bundles theokit and its transitive deps`,
    `//   - Deploy: wrangler deploy`,
    ``,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader, scanWebSocketRoutes } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    `// T3.4 — WS bridge for Cloudflare Workers`,
    `import { createCloudflareWsBridge } from 'theokit/adapters/ws-shim'`,
    streamingImport,
    ``,
    `// Cold-start cache (avoid scanning routes on every request)`,
    `let routesCache = null`,
    `let wsRoutesCache = null`,
    `let loaderCache = null`,
    `// CR-006: server directory is a build-time literal — Workers cannot`,
    `// call process.cwd() and resolving paths at runtime returned '/server'.`,
    `const serverDir = 'server'`,
    ``,
    `function notFoundResponse() {`,
    `  return new Response(`,
    `    JSON.stringify({ error: { code: 'NOT_FOUND', message: 'Route not found' } }),`,
    `    { status: 404, headers: { 'Content-Type': 'application/json' } },`,
    `  )`,
    `}`,
    ``,
    `export default {`,
    `  async fetch(request, env, ctx) {`,
    `    const url = new URL(request.url)`,
    ``,
    `    // T3.4 — Detect WebSocket upgrade and delegate to the CF bridge`,
    `    if (request.headers.get('upgrade')?.toLowerCase() === 'websocket') {`,
    `      if (!wsRoutesCache) wsRoutesCache = scanWebSocketRoutes(serverDir)`,
    `      if (wsRoutesCache.length === 0) return notFoundResponse()`,
    `      const cfWs = createCloudflareWsBridge({`,
    `        onOpen: () => {},`,
    `        onMessage: (ws, data) => { ws.send(data) },`,
    `        onClose: () => {},`,
    `      })`,
    `      return cfWs.handle(request)`,
    `    }`,
    ``,
    `    if (!url.pathname.startsWith('/api/')) {`,
    nonApiBranch,
    `    }`,
    ``,
    `    if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `    if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `    const match = matchRoute(url.pathname, routesCache)`,
    `    if (!match) return notFoundResponse()`,
    ``,
    `    const { req, res, toResponse } = createWebShim(request, { trustedProxy: 'platform' })`,
    `    const requestId = crypto.randomUUID()`,
    `    const method = request.method.toUpperCase()`,
    `    await executeRoute({`,
    `      route: match.route, method, params: match.params,`,
    `      req, res, loadModule: loaderCache, serverDir, requestId,`,
    `    })`,
    `    return toResponse()`,
    `  },`,
    `}`,
  ].join('\n')
}

export function renderWranglerToml(): string {
  return [
    `# Generated by Theo — Cloudflare Workers`,
    `name = "theo-app"`,
    `main = ".theokit/cloudflare/worker.mjs"`,
    `compatibility_date = "2025-09-01"`,
    `compatibility_flags = ["nodejs_compat"]`,
    ``,
    `[site]`,
    `bucket = ".theokit/client"`,
    ``,
    `# Environment variables are set via wrangler secret or dashboard`,
    `# Example: wrangler secret put DATABASE_URL`,
  ].join('\n')
}

export const cloudflareAdapter: DeployAdapter = {
  name: 'cloudflare',

  async build(config: TheoConfig, cwd: string, ctx?: AdapterBuildContext): Promise<void> {
    // Wave 2 (T2.2) — reject polyglot services on this adapter.
    assertServicesUnsupported('cloudflare', readManifest(cwd))

    // 1. Run the standard Node build first (ctx forwarded so nodeAdapter has makeVitePlugins)
    await nodeAdapter.build(config, cwd, ctx)

    const outputDir = resolve(cwd, '.theokit/cloudflare')
    mkdirSync(outputDir, { recursive: true })

    // 2. Emit Worker entry (now uses the shared web-shim)
    //
    // The document shell is read HERE, after the Node build produced
    // `.theokit/client/index.html`, and inlined into the worker: a Worker has no
    // filesystem at request time. Split on the root div with the same helper the
    // Node server uses (`ssr-setup.ts`), so the two paths cannot disagree about
    // where the shell ends (#343).
    const shell = readDocumentShell(cwd, config.ssrStreaming)
    writeFileSync(
      resolve(outputDir, 'worker.mjs'),
      renderCloudflareWorkerEntry({ ssrStreaming: config.ssrStreaming, ...shell }),
    )

    // 3. Emit wrangler.toml (with nodejs_compat enforced)
    writeFileSync(resolve(cwd, 'wrangler.toml'), renderWranglerToml())

    // eslint-disable-next-line no-console -- CLI build progress
    console.log('\n  ✓ Cloudflare output → .theokit/cloudflare/ + wrangler.toml\n')
  },
}
