import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { DeployAdapter } from './types.js'
import type { TheoConfig } from '../config/schema.js'
import { nodeAdapter } from './node.js'

export const cloudflareAdapter: DeployAdapter = {
  name: 'cloudflare',

  async build(config: TheoConfig, cwd: string): Promise<void> {
    // 1. Run the standard Node build first
    await nodeAdapter.build(config, cwd)

    const outputDir = resolve(cwd, '.theo/cloudflare')
    mkdirSync(outputDir, { recursive: true })

    // 2. Generate Worker entry
    const workerEntry = [
      `// Generated by Theo — Cloudflare Workers Adapter`,
      `// Requires nodejs_compat and compatibility_date >= 2025-09-01`,
      `// NOTE: WebSocket requires Cloudflare native WS, not 'ws' package`,
      `// NOTE: In-memory rate limiting does not persist between invocations`,
      `import { createServer } from 'node:http';`,
      ``,
      `export default {`,
      `  async fetch(request, env, ctx) {`,
      `    return new Promise((resolve) => {`,
      `      const url = new URL(request.url);`,
      `      const headers = {};`,
      `      request.headers.forEach((v, k) => { headers[k] = v; });`,
      ``,
      `      const req = {`,
      `        method: request.method,`,
      `        url: url.pathname + url.search,`,
      `        headers,`,
      `        socket: { remoteAddress: headers['cf-connecting-ip'] || '0.0.0.0' },`,
      `        on: (event, cb) => {`,
      `          if (event === 'data') request.body?.pipeTo(new WritableStream({ write(chunk) { cb(chunk); } }));`,
      `          if (event === 'end') request.body ? request.body.pipeTo(new WritableStream({ close() { cb(); } })) : cb();`,
      `        },`,
      `      };`,
      ``,
      `      const chunks = [];`,
      `      const res = {`,
      `        statusCode: 200,`,
      `        _headers: {},`,
      `        writeHead(status, hdrs) { this.statusCode = status; Object.assign(this._headers, hdrs); },`,
      `        setHeader(k, v) { this._headers[k] = v; },`,
      `        getHeader(k) { return this._headers[k]; },`,
      `        write(chunk) { chunks.push(chunk); return true; },`,
      `        end(body) {`,
      `          if (body) chunks.push(typeof body === 'string' ? new TextEncoder().encode(body) : body);`,
      `          resolve(new Response(new Blob(chunks), { status: this.statusCode, headers: this._headers }));`,
      `        },`,
      `        headersSent: false,`,
      `        writableEnded: false,`,
      `      };`,
      ``,
      `      // Import and run Theo handler`,
      `      import('./handler.js').then(mod => mod.default(req, res)).catch(() => {`,
      `        resolve(new Response('Internal Server Error', { status: 500 }));`,
      `      });`,
      `    });`,
      `  },`,
      `};`,
    ].join('\n')

    writeFileSync(resolve(outputDir, 'worker.mjs'), workerEntry)

    // 3. Generate wrangler.toml
    const wranglerToml = [
      `# Generated by Theo — Cloudflare Workers`,
      `name = "theo-app"`,
      `main = ".theo/cloudflare/worker.mjs"`,
      `compatibility_date = "2025-09-01"`,
      `compatibility_flags = ["nodejs_compat"]`,
      ``,
      `[site]`,
      `bucket = ".theo/client"`,
      ``,
      `# Environment variables are set via wrangler secret or dashboard`,
      `# Example: wrangler secret put DATABASE_URL`,
    ].join('\n')

    writeFileSync(resolve(cwd, 'wrangler.toml'), wranglerToml)

    console.log('\n  ✓ Cloudflare output → .theo/cloudflare/ + wrangler.toml\n')
  },
}
