/* eslint-disable security/detect-non-literal-fs-filename --
 * Deno Deploy adapter. Writes to `cwd/.theo/deno-deploy/`. Build-time.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'

import { nodeAdapter } from './node.js'
import type { DeployAdapter } from './types.js'

export interface DenoBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string) => Promise<void>
  writeEntry?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
}

export function renderDenoEntry(port: number): string {
  return [
    `// Generated by Theo — Deno Deploy Adapter`,
    `// Deploy: deployctl deploy --project=<name> .theo/deno/server.ts`,
    `// Requires Deno >= 1.40 (Deno.serve + npm: specifier support)`,
    ``,
    `// Runtime guard`,
    `if (typeof Deno === 'undefined') {`,
    `  throw new Error('TheoDenoDeployAdapter must run inside Deno.')`,
    `}`,
    ``,
    `// Use npm: specifier so Deno resolves theokit from the user's package.json`,
    `// equivalent (works in both local 'deno run' and Deno Deploy).`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader, scanWebSocketRoutes } from 'npm:theokit/server'`,
    `import { createWebShim } from 'npm:theokit/adapters/web-shim'`,
    `// T3.3 — WS bridge for Deno runtime`,
    `import { createDenoWsBridge } from 'npm:theokit/adapters/ws-shim'`,
    ``,
    `const port = Number(Deno.env.get('PORT') ?? '${port}')`,
    `const cwd = Deno.cwd()`,
    `const serverDir = cwd + '/server'`,
    `let routesCache = null`,
    `let wsRoutesCache = null`,
    `let loaderCache = null`,
    ``,
    `function notFound() {`,
    `  return new Response(JSON.stringify({ error: { code: 'NOT_FOUND' } }), {`,
    `    status: 404,`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `  })`,
    `}`,
    ``,
    `Deno.serve({ port }, async (request) => {`,
    `  const url = new URL(request.url)`,
    ``,
    `  // T3.3 — Detect WebSocket upgrade and delegate to the Deno bridge`,
    `  if (request.headers.get('upgrade')?.toLowerCase() === 'websocket') {`,
    `    if (!wsRoutesCache) wsRoutesCache = scanWebSocketRoutes(serverDir)`,
    `    if (wsRoutesCache.length === 0) return notFound()`,
    `    const denoWs = createDenoWsBridge({`,
    `      onOpen: () => {},`,
    `      onMessage: (ws, data) => { ws.send(data) },`,
    `      onClose: () => {},`,
    `    }, Deno)`,
    `    return denoWs.handle(request)`,
    `  }`,
    ``,
    `  if (!url.pathname.startsWith('/api/')) {`,
    `    // Static + SPA fallback are served by Deno Deploy's static asset handler.`,
    `    return notFound()`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `  const match = matchRoute(url.pathname, routesCache)`,
    `  if (!match) return notFound()`,
    ``,
    `  const { req, res, toResponse } = createWebShim(request)`,
    `  const requestId = crypto.randomUUID()`,
    `  const method = request.method.toUpperCase()`,
    `  await executeRoute(match.route, method, match.params, req, res, loaderCache, serverDir, requestId)`,
    `  return toResponse()`,
    `})`,
    ``,
    `console.log('Theo (Deno Deploy) listening on :' + port)`,
  ].join('\n')
}

export async function buildDeno(
  config: TheoConfig,
  cwd: string,
  deps: DenoBuildDeps = {},
): Promise<void> {
  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd)

  const outputDir = resolve(cwd, '.theo/deno')
  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  ensureDir(outputDir)

  const entry = renderDenoEntry(config.port)
  const write =
    deps.writeEntry ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  write(resolve(outputDir, 'server.ts'), entry)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ Deno Deploy output → .theo/deno/server.ts\n')
}

export const denoDeployAdapter: DeployAdapter = {
  name: 'deno-deploy',
  build(config, cwd) {
    return buildDeno(config, cwd)
  },
}
