/* eslint-disable security/detect-non-literal-fs-filename --
 * Deno Deploy adapter. Writes to `cwd/.theokit/deno-deploy/`. Build-time.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { deployedAgentsFragment, scannedFromLoaderCache } from './deployed-agents.js'
import { planDeployedPlugins } from './deployed-plugins-module.js'
import { deployedEntryPreamble } from './deployed-preamble.js'
import { deployedRateLimitFragment, rateLimitCheckFragment } from './deployed-rate-limit.js'
import {
  agentsDirLiteral,
  deployedRuntimeConfigFragment,
  serverDirLiteral,
} from './deployed-runtime-config.js'
import { deployedTraceFragment } from './deployed-trace.js'
import { nodeAdapter } from './node.js'
import { describeDeployedSecurityHeaders } from './security-headers.js'
import type { AdapterBuildContext, DeployAdapter, DeployedEntryOptions } from './types.js'

export interface DenoBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeEntry?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
  /** The project's own source texts, whose bare imports the emitted map has to resolve. */
  readProjectSources?: (cwd: string, config: TheoConfig) => string[]
  /** The Deno config already on disk, merged rather than replaced. */
  readDenoConfig?: (cwd: string) => DenoConfig | undefined
}

/**
 * The framework imports this entry opens with, as `npm:` specifiers.
 *
 * Extracted from `renderDenoEntry` when adding the configured-directory literal pushed it past the
 * per-function line budget. A cohesive block — every line is one import of the same package family
 * — so lifting it keeps the budget a signal about the renderer rather than about its preamble.
 */
const FRAMEWORK_IMPORTS: readonly string[] = [
  `// Use npm: specifier so Deno resolves theokit from the user's package.json`,
  `// equivalent (works in both local 'deno run' and Deno Deploy).`,
  // Sub-paths, not the umbrella. `theokit/server` is DEPRECATED by the framework itself with a
  // REMOVAL scheduled, so this entry would stop loading on that release, before a request exists —
  // measured on Deno 2.9.5, where the warning printed on every start. This was the only adapter still
  // on the umbrella; the split below is the mapping four siblings already use and Bun proves by
  // running.
  `import { scanServerRoutes, matchRoute, createProductionLoader, scanWebSocketRoutes } from 'npm:theokit/server/scan'`,
  `import { executeRoute, extractTraceIdFromRequest, TRACE_HEADER, createCorsWebHandler } from 'npm:theokit/server/http'`,
  `import { createWebShim } from 'npm:theokit/adapters/web-shim'`,
  `import { buildSecurityHeaders, withSecurityHeaders } from 'npm:theokit/adapters/security-headers'`,
  `// T3.3 — WS bridge for Deno runtime`,
  `import { createDenoWsBridge } from 'npm:theokit/adapters/ws-shim'`,
]

/** The target's name, in the five places that spell it. Adding a sixth tripped the duplicate-literal gate. */
/* The name in the places a gate does NOT read. `assertServicesUnsupported` keeps the literal:
 * `services-other-adapters-reject.test.ts:30` requires each adapter to name ITSELF there, so a
 * copy-paste carrying another adapter's name cannot hide behind a constant. */
const TARGET = 'deno-deploy'

export function renderDenoEntry(port: number, opts: DeployedEntryOptions = {}): string {
  const runtimeConfig = deployedRuntimeConfigFragment(opts)
  const agentsFragment = deployedAgentsFragment(scannedFromLoaderCache(agentsDirLiteral(opts)), {
    notFound: 'notFound()',
    importPrefix: 'npm:',
    // B-185 — bound only when the runtime-config fragment declared the const, which is
    // exactly when a plugins module was emitted. Referencing it otherwise would emit an
    // identifier the entry never declares.
    pluginRunnerExpr:
      opts.runtimeConfigModule === undefined ? undefined : 'await THEO_PLUGIN_RUNNER',
  })
  return [
    `// Generated by Theo — Deno Deploy Adapter`,
    `// Deploy from the project root, so the entry finds its own src/server tree:`,
    `//   deno deploy --org <org> --app <name> --prod --ignore node_modules`,
    `// pnpm's node_modules is a symlink farm the upload cannot carry, and this entry`,
    `// reaches the framework through npm: specifiers, so it needs none of it.`,
    `// Requires Deno >= 1.40 (Deno.serve + npm: specifier support)`,
    ``,
    `// Runtime guard`,
    `if (typeof Deno === 'undefined') {`,
    `  throw new Error('TheoDenoDeployAdapter must run inside Deno.')`,
    `}`,
    ``,
    ...FRAMEWORK_IMPORTS,
    ``,
    `const port = Number(Deno.env.get('PORT') ?? '${port}')`,
    `const cwd = Deno.cwd()`,
    `const serverDir = cwd + '/' + ${serverDirLiteral(opts)}`,
    `let routesCache = null`,
    `let wsRoutesCache = null`,
    `let loaderCache = null`,
    ``,
    `// #410 — the security baseline \`theokit start\` puts on every response,`,
    `// carried here as a literal because the deployed isolate has no`,
    `// theo.config.ts to read. Non-API paths 404 here and are served by Deno`,
    `// Deploy's static asset handler, so this covers the API and not the`,
    `// document (usetheokit/theokit#412).`,
    ...deployedEntryPreamble(runtimeConfig, agentsFragment, opts, TARGET),
    ``,
    `function notFound() {`,
    `  return new Response(JSON.stringify({ error: { code: 'NOT_FOUND' } }), {`,
    `    status: 404,`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `  })`,
    `}`,
    ``,
    // B-027 — `npm:`, like every other specifier this target emits (`:37-43`). A bare one does
    // not resolve on Deno Deploy, and the harness asserts the prefix is here before rewriting it.
    ...(opts.rateLimit === undefined
      ? []
      : [
          `import { createRateLimiterWeb } from 'npm:theokit/server/rate-limit'`,
          `import { resolveClientIpFromRequest } from 'npm:theokit/server/rate-limit'`,
          ``,
        ]),
    ...deployedRateLimitFragment(
      opts.rateLimit,
      TARGET,
      // `info.remoteAddr` is the runtime's own answer. A `UnixAddr` has no `hostname`, so the
      // optional chain is what keeps the read from throwing there rather than a guess.
      `info?.remoteAddr?.hostname ?? resolveClientIpFromRequest(request, TRUST_PROXY)`,
      'request, info',
      // B-257 — `npm:`, like every other specifier this target emits. A bare one does not resolve
      // on Deno Deploy, and the durable limiter's import is emitted by the fragment rather than
      // here, so the prefix has to travel with it.
      'npm:',
    ),
    ``,
    // The serve handler's SECOND parameter is bound here for the first time: `Deno.serve` has
    // always passed it and the emitted entry discarded it.
    `Deno.serve({ port }, async (request, info) => {`,
    `  // #409 — the preflight is answered BEFORE anything routes: an OPTIONS the router`,
    `  // handles is an OPTIONS the browser never gets a CORS answer to.`,
    `  const preflight = corsPreflight(request)`,
    `  if (preflight !== null) return withSecurityHeaders(preflight, SECURITY_HEADERS)`,
    ...rateLimitCheckFragment(opts.rateLimit, '  ', 'request, info'),
    ``,
    `  // LCR0103 — the upgrade branch sits BELOW the limiter, and the order is the point.`,
    `  // It used to sit above, under the comment "a 101 carries no document and no script,`,
    `  // so the security baseline does not apply to it". That is true of the security`,
    `  // HEADERS — a document concern — and false of the limiter, which is a resource`,
    `  // concern: a long-lived socket is the most expensive thing this entry hands out, so`,
    `  // the upgrade is the path that most needs a budget, not the one that may skip it.`,
    `  // T3.3 — Detect WebSocket upgrade and delegate to the Deno bridge.`,
    `  // A 101 carries no document and no script, so the security baseline does`,
    `  // not apply to it.`,
    `  if (request.headers.get('upgrade')?.toLowerCase() === 'websocket') {`,
    `    if (!wsRoutesCache) wsRoutesCache = scanWebSocketRoutes(serverDir)`,
    `    if (wsRoutesCache.length === 0) return notFound()`,
    `    const denoWs = createDenoWsBridge({`,
    `      onOpen: () => {},`,
    `      onMessage: (ws, data) => { ws.send(data) },`,
    `      onClose: () => {},`,
    `    }, Deno)`,
    `    return denoWs.handle(request)`,
    `  }`,
    `  return withCors(request, withSecurityHeaders(await handleRequest(request), SECURITY_HEADERS))`,
    `})`,
    ``,
    `async function handleRequest(request) {`,
    `  const url = new URL(request.url)`,
    ``,
    `  if (!url.pathname.startsWith('/api/')${agentsFragment.hostBypass}) {`,
    `    // Static + SPA fallback are served by Deno Deploy's static asset handler.`,
    `    return notFound()`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    ...agentsFragment.branch,
    ``,
    `  const match = matchRoute(url.pathname, routesCache)`,
    `  if (!match) return notFound()`,
    ``,
    `  const { req, res, toResponse } = createWebShim(request)`,
    ...deployedTraceFragment('request', '  '),
    `  const method = request.method.toUpperCase()`,
    `  // #382 — not awaited: toResponse() settles at the headers and carries a`,
    `  // live body, so Deno.serve streams while the handler writes.`,
    `  return toResponse(executeRoute({ route: match.route, method, params: match.params, req, res, loadModule: loaderCache, serverDir, requestId, ...CSRF_CONFIG, ${runtimeConfig.executeRouteSpread} }))`,
    `}`,
    ``,
    `console.log('Theo (Deno Deploy) listening on :' + port)`,
  ].join('\n')
}

export async function buildDeno(
  config: TheoConfig,
  cwd: string,
  deps: DenoBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('deno-deploy', readManifest(cwd))

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const outputDir = resolve(cwd, DENO_DEPLOY_ENTRY_PATH, '..')
  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  ensureDir(outputDir)

  const pluginsPlan = planDeployedPlugins(config.plugins, denoDeployAdapter.name)
  const entry = renderDenoEntry(config.port, {
    securityHeaders: config.security?.headers,
    csrf: config.security?.csrf,
    disallowed: config.security?.disallowed,
    cors: config.security?.cors,
    // #425 — a selector, not a transformer, so it rides as a literal like the values above.
    serialization: config.serialization,
    // #425 — the ONE concern that is not a literal. A closure cannot be baked, so a plugin
    // declared by module specifier is imported by the emitted module instead; a constructed one
    // is refused by name at build time rather than dropped in silence.
    runtimeConfigModule: pluginsPlan?.moduleSpecifier,
    // #95 — the configured directories, which `build.ts:210` already threads into the Vite
    // plugins. Without these two lines the literals above fall to their defaults and a project
    // with a custom dir deploys an entry that resolves a directory it does not have.
    serverDir: config.serverDir,
    agentsDir: config.agentsDir,
  })
  const write =
    deps.writeEntry ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  if (pluginsPlan !== undefined) {
    // Beside the entry, so the emitted import is a sibling. Written through the same seam as
    // the entry so a test that captures one captures both (#425).
    write(resolve(outputDir, 'theo.plugins.mjs'), pluginsPlan.source)
  }
  write(resolve(cwd, DENO_DEPLOY_ENTRY_PATH), entry)

  // The import map and `sloppy-imports`, at the upload root. Measured on the platform: a
  // config in a subdirectory failed the revision, so this path is not a preference.
  const readSources = deps.readProjectSources ?? readProjectSourcesFromDisk
  const readConfig = deps.readDenoConfig ?? readDenoConfigFromDisk
  const denoConfig = renderDenoConfig({
    specifiers: bareSpecifiersOf(readSources(cwd, config)),
    existing: readConfig(cwd),
  })
  write(resolve(cwd, DENO_DEPLOY_CONFIG_PATH), `${JSON.stringify(denoConfig, undefined, 2)}\n`)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log(
    `\n  ✓ Deno Deploy output → ${DENO_DEPLOY_ENTRY_PATH} + ${DENO_DEPLOY_CONFIG_PATH} (${
      Object.keys(denoConfig.imports ?? {}).length
    } specifiers mapped)`,
  )
  // eslint-disable-next-line no-console -- CLI build progress
  console.log(
    `${describeDeployedSecurityHeaders({
      target: TARGET,
      securityHeaders: config.security?.headers,
      mintsNonce: false,
      documentHeaders: 'platform-unmanaged',
    })}\n`,
  )
}

/**
 * Where the entry is written, relative to the project root.
 *
 * NOT under `.theokit/`, and that is the whole point: measured against the real platform on
 * 2026-09-30, a dot directory is never uploaded. `./.theokit/deno/probe.ts` failed the
 * revision while the byte-identical file at `./visible/probe.ts` served HTTP 200. An entry
 * the upload cannot see is an entry that cannot run, and the build reported success either
 * way — so nothing short of a deploy could find this.
 *
 * One directory deep, because the upload root has to stay the PROJECT root: the entry scans
 * `<cwd>/src/server` for the project's own route modules, so a deploy rooted anywhere else
 * finds no routes and answers 404 on every path.
 */
export const DENO_DEPLOY_ENTRY_PATH = 'theokit-deploy/server.ts'

/** Where the Deno config is written. The upload root, and nowhere else — see below. */
export const DENO_DEPLOY_CONFIG_PATH = 'deno.json'

/**
 * The bare specifiers a set of source texts import — the ones needing a registry, in the
 * order they will be emitted.
 *
 * Derived from the project's own sources rather than from `package.json`, because what has
 * to resolve is what is actually imported: a declared dependency nobody imports needs no
 * entry, and a subpath like `theokit/server/define` appears in no manifest at all.
 */
export function bareSpecifiersOf(sources: Iterable<string>): string[] {
  const found = new Set<string>()
  for (const source of sources) {
    for (const match of source.matchAll(/(?:from|import)\s+['"]([^'"]+)['"]/gu)) {
      // `match[1]` and not a guarded read: the capture group is not optional in this pattern,
      // so it participates in every match the loop yields.
      const specifier = match[1]
      // A relative or absolute path resolves on its own; a specifier that already names its
      // registry is not ours to map.
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- a regex group's type is wider than this pattern
      if (specifier === undefined) continue
      if (/^(?:[./]|npm:|jsr:|node:|data:|https?:)/u.test(specifier)) continue
      found.add(specifier)
    }
  }
  // An explicit comparator: the emitted map is read in diffs, so its order has to be the
  // same on every machine rather than whatever the default collation is.
  return [...found].sort((a, b) => a.localeCompare(b, 'en'))
}

/** The shape this adapter reads and writes. Anything else in the file is carried through. */
export interface DenoConfig {
  imports?: Record<string, string>
  unstable?: string[]
  [key: string]: unknown
}

/**
 * The Deno config the platform needs, merged onto whatever the project already wrote.
 *
 * Two measured facts decide its whole content:
 *
 * **Each specifier is mapped exactly, never as a prefix.** The emitted entry imports
 * `npm:theokit/...`; the project's own modules import the bare `theokit/server/define`. A
 * trailing-slash prefix cannot bridge them — Deno refuses `"theokit/": "npm:theokit/"` with
 * *"its after-prefix portion could not be URL-parsed relative to the URL prefix"*, because
 * the part after the prefix is not joinable onto an `npm:` URL. Exact entries resolve; the
 * prefix form fails at the first import, at runtime, with a 500.
 *
 * **`sloppy-imports` is declared.** A generated project's own agent modules import siblings
 * with a `.js` extension against files on disk ending `.ts` — six of them in the default
 * template. Deno refuses that pairing and says so: *"Maybe change the extension to '.ts' or
 * run with --sloppy-imports"*.
 */
export function renderDenoConfig(opts: {
  specifiers: readonly string[]
  existing?: DenoConfig
}): DenoConfig {
  const config: DenoConfig = { ...(opts.existing ?? {}) }
  const imports: Record<string, string> = { ...(config.imports ?? {}) }
  for (const specifier of opts.specifiers) imports[specifier] = `npm:${specifier}`
  config.imports = imports
  const unstable = [...(config.unstable ?? [])]
  if (!unstable.includes('sloppy-imports')) unstable.push('sloppy-imports')
  config.unstable = unstable
  return config
}

/**
 * The project's own TypeScript sources, from the directories the entry scans at runtime.
 *
 * Scoped to those directories plus the config file rather than the whole tree: what the map
 * must resolve is what the DEPLOYED code imports, and a specifier reachable only from a test
 * or a build script never runs on the platform.
 */
function readProjectSourcesFromDisk(cwd: string, config: TheoConfig): string[] {
  // No fallback: `config/schema.ts` gives both a zod `.default()`, so a parsed config always
  // carries them — and the defaults are `server`/`agents`, so the `src/`-prefixed guesses this
  // line used to hold would have read the wrong directories on any project that took them.
  const roots = [config.serverDir, config.agentsDir]
  const texts: string[] = []
  for (const root of roots) {
    const dir = resolve(cwd, root)
    if (!existsSync(dir)) continue
    for (const entry of readdirSync(dir, { recursive: true, withFileTypes: true })) {
      if (!entry.isFile()) continue
      if (!/\.(?:ts|tsx|mts)$/u.test(entry.name)) continue
      if (/\.(?:test|spec)\./u.test(entry.name)) continue
      texts.push(readFileSync(resolve(entry.parentPath, entry.name), 'utf8'))
    }
  }
  const themeConfig = resolve(cwd, 'theo.config.ts')
  if (existsSync(themeConfig)) texts.push(readFileSync(themeConfig, 'utf8'))
  return texts
}

function readDenoConfigFromDisk(cwd: string): DenoConfig | undefined {
  const file = resolve(cwd, DENO_DEPLOY_CONFIG_PATH)
  if (!existsSync(file)) return undefined
  try {
    return JSON.parse(readFileSync(file, 'utf8')) as DenoConfig
  } catch {
    // A config we cannot parse is one we must not overwrite blind: returning undefined would
    // replace whatever the project wrote. Refusing here surfaces it at the write site instead.
    throw new Error(
      `${DENO_DEPLOY_CONFIG_PATH} exists and is not valid JSON. Fix or remove it before building for deno-deploy.`,
    )
  }
}

export const denoDeployAdapter: DeployAdapter = {
  // Same as `bun`, plus the runtime compiles the TypeScript it finds — which is why a scan that
  // answered `SyntaxError` on netlify is legitimate here. The last runtime scanner in the fleet.
  readsSourceAtRunTime: true,
  specifiersResolvedBy: 'the-project-at-run-time',
  name: 'deno-deploy',
  streamsResponses: true,
  // #409 / #410 — the generated entry calls `executeRoute` with routes, loader
  // and serverDir only. CSRF, route policy, file middleware and Zod validation
  // still run because they live inside `executeRoute`; none of the remaining
  // configurable concerns reach it. Declared explicitly rather than omitted so
  // the gap is a statement in the source and not an absence.
  //
  // `securityHeaders` IS applied -- to every response this isolate returns. The
  // document comes from Deno Deploy's static asset handler and does not pass
  // through it (usetheokit/theokit#412).
  servesAgents: true,
  appliesConfig: ['securityHeaders', 'csrf', 'disallowed', 'cors', 'serialization', 'plugins'],
  // B-257 — per-invocation: an in-process counter does not survive, so a declared limit needs a durable store.
  enforcesRateLimit: 'with-a-store',
  build(config, cwd, ctx) {
    return buildDeno(config, cwd, {}, ctx)
  },
}
