/**
 * The plugins module a build writes beside a deployed entry (usetheokit/theokit#425).
 *
 * ## What it is for
 *
 * `config.plugins` used to reach no deployed target at all, so `onRequest`, `preHandler`,
 * `onResponse` and `onError` were dead on every Web-standards deployment while firing locally. The
 * reason was never the hook loop — `executeRoute` has always run it — but that a constructed
 * plugin closes over state, and there is no literal for a closure.
 *
 * A plugin declared as a module SPECIFIER can be carried, because the build can emit a static
 * import for it. That is the road `renderBakedRoutes` already takes for route modules (#369):
 * resolve on the build machine, emit a static specifier, let the target's bundler see through it.
 *
 * ## Why the specifier is `../../`
 *
 * Every target that can carry plugins writes its entry two levels below the project root —
 * `.theokit/cloudflare/`, `.theokit/bun/`, `.theokit/deno/` — and a declared specifier is relative
 * to that root. The same arithmetic `renderBakedRoutes` does for routes, for the same reason.
 *
 * ## Which targets can carry them at all
 *
 * Only the ones whose output is BUNDLED from the project: Cloudflare (wrangler), Bun and Deno all
 * resolve the emitted import against the app's own source tree. Vercel, Netlify and AWS Lambda
 * receive a standalone function directory and never see the app's modules, so for them a named
 * refusal — which `findUnappliedConfig` already prints — remains the honest answer, and this module
 * is not called.
 */

/**
 * A plugin the build was asked to carry and cannot.
 *
 * Its own type because the alternative is the defect this whole issue is: hooks that do not fire
 * and nothing that says so. A target that CAN carry a named module but was handed a closure has
 * something actionable to say, so it says it at build time rather than at the first request
 * (`rules/three-target-parity.md` § 3 — refuse by name).
 */
export class UnbakeablePluginError extends Error {
  constructor(index: number, name: string, target: string) {
    super(
      `plugins[${index}] ("${name}") cannot be carried to the ${target} target: it is a constructed ` +
        `plugin, and a closure has no literal a generated entry could hold. Declare it by module ` +
        `specifier instead — plugins: ['./src/plugins/${name}.ts'] — so the build can emit a ` +
        `static import for it. Both forms work locally; only the specifier survives a deploy.`,
    )
    this.name = 'UnbakeablePluginError'
  }
}

export interface DeployedPluginsPlan {
  /** The module source to write beside the entry. */
  readonly source: string
  /** What the entry imports it as — a sibling, because both are written to the same directory. */
  readonly moduleSpecifier: string
  /** The declared specifiers, in order, for the build to report. */
  readonly specifiers: readonly string[]
}

const MODULE_FILENAME = 'theo.plugins.mjs'

/**
 * Plan the plugins module for a target that can carry one.
 *
 * @param plugins - the raw `config.plugins` array.
 * @param target - the deploy target, named in the refusal so the message says where it applies.
 * @returns `undefined` when the app declares no plugins, so an app carrying none emits nothing.
 * @throws UnbakeablePluginError when an entry is a constructed plugin rather than a specifier.
 */
export function planDeployedPlugins(
  plugins: readonly unknown[] | undefined,
  target: string,
): DeployedPluginsPlan | undefined {
  if (plugins === undefined || plugins.length === 0) return undefined

  const specifiers = plugins.map((entry, index) => {
    if (typeof entry === 'string') return entry
    throw new UnbakeablePluginError(index, nameOf(entry), target)
  })

  const vars = specifiers.map((_, i) => `__theoPlugin${String(i)}`)

  return {
    moduleSpecifier: `./${MODULE_FILENAME}`,
    specifiers,
    source: [
      `// Generated by Theo — the plugins the deployed entry registers (usetheokit/theokit#425).`,
      `//`,
      `// Static imports, resolved on the build machine. A constructed plugin has no literal, which`,
      `// is why the config declares these by module specifier and why this file can exist at all.`,
      ...specifiers.map((s, i) => `import ${vars[i]} from '${entrySpecifier(s)}'`),
      ``,
      `// Order is DECLARED order, because plugin order is hook order.`,
      `export default { plugins: [${vars.join(', ')}] }`,
      ``,
    ].join('\n'),
  }
}

/**
 * How the emitted module names a declared specifier.
 *
 * A RELATIVE specifier is relative to the project root, and the module sits two levels below it, so
 * it is re-based — the arithmetic `renderBakedRoutes` does for routes. A BARE specifier is a package
 * and must be left alone: `../../my-plugin-pkg` is a path that does not exist, where
 * `my-plugin-pkg` is a dependency the target's bundler resolves from `node_modules` like any other.
 */
function entrySpecifier(specifier: string): string {
  if (!specifier.startsWith('.')) return specifier
  return `../../${specifier.replace(/^\.\/+/, '')}`
}

/** The plugin's own name when it has one, so the refusal names the thing the author wrote. */
function nameOf(entry: unknown): string {
  if (entry != null && typeof entry === 'object') {
    const named = (entry as { name?: unknown }).name
    if (typeof named === 'string' && named.length > 0) return named
  }
  return 'unnamed'
}
