/* eslint-disable security/detect-non-literal-fs-filename --
 * Netlify deploy adapter. All paths derived from `cwd` and a fixed
 * `.theokit/netlify/` output layout. Build-time tool — no HTTP input.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import type { SecurityHeadersConfig } from '../core/contracts/security-headers.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import {
  deployedAgentsFragment,
  JSON_NOT_FOUND_RESPONSE,
  scannedFromLoaderCache,
} from './deployed-agents.js'
import { renderBakedRoutes, routeRuntimeLines, type BakedRoute } from './deployed-baked-routes.js'
import { type DeployedCorsOptions } from './deployed-cors.js'
import { type DeployedCsrfOptions } from './deployed-csrf.js'
import { deployedEntryPreamble } from './deployed-preamble.js'
import { deployedRateLimitFragment, rateLimitCheckFragment } from './deployed-rate-limit.js'
import type { DeployedRateLimitOptions } from './deployed-rate-limit.js'
import {
  agentsDirLiteral,
  type DeployedAgentsDirOptions,
  deployedRuntimeConfigFragment,
  type DeployedRuntimeConfigOptions,
  serverDirLiteral,
  type DeployedServerDirOptions,
} from './deployed-runtime-config.js'
import { deployedTraceFragment } from './deployed-trace.js'
import { nodeAdapter } from './node.js'
import { buildSecurityHeaders, describeDeployedSecurityHeaders } from './security-headers.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

export class NetlifyConflictError extends Error {
  constructor(path: string, currentTo: string) {
    super(
      `netlify.toml has a conflicting redirect: "${path}" → "${currentTo}". ` +
        `Remove it manually or edit it to point to "/.netlify/functions/theo" ` +
        `before running the Netlify adapter again.`,
    )
    this.name = 'NetlifyConflictError'
  }
}

export interface NetlifyBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeFile?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
  readTomlIfExists?: () => string | null
}

export function renderNetlifyFunction(
  opts: { securityHeaders?: SecurityHeadersConfig } & DeployedAgentsDirOptions &
    DeployedCsrfOptions &
    DeployedRuntimeConfigOptions &
    DeployedCorsOptions &
    DeployedRateLimitOptions &
    DeployedServerDirOptions & { routes?: readonly BakedRoute[] } = {},
): string {
  // B-338 — the routes are baked, not scanned. The scan was a `readdirSync` over the server directory,
  // and on the Netlify emulator it FOUND `src/server/routes/health.ts` and answered 500
  // `SyntaxError: Unexpected token ')'` — a TypeScript source a plain JS runtime cannot compile. On a real
  // deploy it finds nothing at all, because Netlify uploads the bundled function. The fix B-319 made for
  // Vercel and #369 for Cloudflare, on the fourth target; the emitter is shared and its own docblock says
  // "the target only supplies what its own error message says".
  const { routeImports, routeModuleEntries, routeTableEntries } = renderBakedRoutes(
    opts.routes ?? [],
  )
  const runtimeConfig = deployedRuntimeConfigFragment(opts)
  // B-235. Netlify's handler is `(request, context)` and already RECEIVES a Web `Request`, which
  // is the shape this branch needs — the item filed against it counted `new Request` occurrences
  // and concluded the opposite, measuring how the entry OBTAINS a request rather than whether it
  // has one. Deno is the model: same `loaderCache`, same filesystem `serverDir`, same guard.
  const agentsFragment = deployedAgentsFragment(scannedFromLoaderCache(agentsDirLiteral(opts)), {
    // Netlify answers its own 404 inline rather than through a helper, so the fragment is given
    // the expression instead of a call it would have to declare.
    notFound: `new Response('Not Found', { status: 404 })`,
  })
  return [
    `// Generated by Theo — Netlify Functions adapter`,
    `import { resolve } from 'node:path'`,
    `import { matchRoute, compilePattern } from 'theokit/server/scan'\nimport { executeRoute, extractTraceIdFromRequest, TRACE_HEADER, createCorsWebHandler } from 'theokit/server/http'`,
    ...routeImports,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    `import { buildSecurityHeaders, withSecurityHeaders } from 'theokit/adapters/security-headers'`,
    ``,
    `const cwd = process.cwd()`,
    // B-338 — was `resolve(cwd, 'server')`, a literal. A project declaring `src/server` got a function
    // scanning a directory that does not exist, and every `/api/*` answered 404 — measured on the Netlify
    // emulator. The FOURTH target with this shape: B-185 (bun, deno), B-235 (agentsDir here), B-315
    // (vercel, aws-lambda, cloudflare), and this file's own call site already names two of them.
    `const serverDir = resolve(cwd, ${serverDirLiteral(opts)})`,
    ...routeRuntimeLines(routeModuleEntries, routeTableEntries, 'netlify'),
    ``,
    `// #410 — the security baseline \`theokit start\` puts on every response,`,
    `// carried here as a literal because the deployed function has no`,
    `// theo.config.ts to read. The netlify.toml redirect routes only /api/* here,`,
    `// so this covers the API and not the document Netlify's static host serves`,
    `// (usetheokit/theokit#412).`,
    ...deployedEntryPreamble(runtimeConfig, agentsFragment, opts, 'netlify'),
    ``,
    // B-027 — emitted only when a limit is declared.
    ...(opts.rateLimit === undefined
      ? []
      : [
          // B-338 — the sub-path, not the umbrella. The umbrella re-exports the whole server half and
          // @swc/core's native .node addon is down that graph; the guard against it could not see this
          // adapter, because the shared comment stripper read this file's "/*" redirect glob as a
          // comment opener and deleted 36% of it before the sweep looked.
          `import { createRateLimiterWeb } from 'theokit/server/rate-limit'`,
          `import { resolveClientIpFromRequest } from 'theokit/server/rate-limit'`,
          ``,
        ]),
    ...deployedRateLimitFragment(
      opts.rateLimit,
      'netlify',
      // `context.ip` is the platform's own answer, read from the handler context Netlify passes.
      // The forwarded fallback covers a function shape that carries no context, and returns
      // `undefined` unless a `trustProxy` was declared — which is the named 503, not a shared key.
      `context?.ip ?? resolveClientIpFromRequest(request, TRUST_PROXY)`,
      // Both names are bound in the OUTER handler, which is where the check runs. Threading
      // `context` into `handleRequest` — which the plan called for — buys nothing: the limiter
      // never runs in there.
      'request, context',
    ),
    ``,
    `export default async (request, context) => {`,
    `  // #409 — the preflight is answered BEFORE anything routes: an OPTIONS the router`,
    `  // handles is an OPTIONS the browser never gets a CORS answer to.`,
    `  const preflight = corsPreflight(request)`,
    `  if (preflight !== null) return withSecurityHeaders(preflight, SECURITY_HEADERS)`,
    ...rateLimitCheckFragment(opts.rateLimit, '  ', 'request, context'),
    `  return withCors(request, withSecurityHeaders(await handleRequest(request), SECURITY_HEADERS))`,
    `}`,
    ``,
    `async function handleRequest(request) {`,
    `  const url = new URL(request.url)`,
    `  if (!url.pathname.startsWith('/api/')${agentsFragment.hostBypass}) {`,
    `    return new Response('Not Found', { status: 404 })`,
    `  }`,
    ``,

    ``,
    ...agentsFragment.branch,
    ``,
    `  const match = matchRoute(url.pathname, routes)`,
    `  if (!match) return ${JSON_NOT_FOUND_RESPONSE}`,
    ``,
    `  const { req, res, toResponse } = createWebShim(request)`,
    ...deployedTraceFragment('request', '  '),
    `  const method = request.method.toUpperCase()`,
    `  // #382 — the run is not awaited: toResponse() settles at the headers and`,
    `  // carries a live body, so Netlify streams while the handler writes.`,
    `  return toResponse(executeRoute({ route: match.route, method, params: match.params, req, res, loadModule, serverDir, requestId, ...CSRF_CONFIG, ${runtimeConfig.executeRouteSpread} }))`,
    `}`,
  ].join('\n')
}

const THEO_REDIRECT_FROM = '/api/*'
const THEO_REDIRECT_TO = '/.netlify/functions/theo'

/**
 * TOML merge (EC-2) — non-destructive.
 *
 * We avoid adding a TOML parser dependency by working at the line level. The
 * supported subset is sufficient for the Netlify use case:
 *   - detect existing `[[redirects]]` blocks
 *   - find a block whose `from = "..."` matches our target
 *   - error if such a block points elsewhere
 *   - otherwise append our block
 *
 * Unknown sections (e.g. `[build]`, `[[headers]]`, `[context.production.environment]`)
 * are preserved as-is.
 */
interface NetlifyRedirectBlock {
  startLine: number
  endLine: number
  from?: string
  to?: string
}

function parseRedirectBlocks(lines: readonly string[]): NetlifyRedirectBlock[] {
  const blocks: NetlifyRedirectBlock[] = []
  let current: NetlifyRedirectBlock | null = null

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim()
    if (trimmed === '[[redirects]]') {
      if (current) {
        current.endLine = i - 1
        blocks.push(current)
      }
      current = { startLine: i, endLine: i }
      continue
    }
    if (current && /^\[(\[|[^[])/.test(trimmed)) {
      // Entering another section — close current.
      current.endLine = i - 1
      blocks.push(current)
      current = null
    }
    if (current) {
      const fromMatch = /^from\s*=\s*"([^"]+)"/.exec(trimmed)
      if (fromMatch) current.from = fromMatch[1]
      const toMatch = /^to\s*=\s*"([^"]+)"/.exec(trimmed)
      if (toMatch) current.to = toMatch[1]
      current.endLine = i
    }
  }
  if (current) blocks.push(current)
  return blocks
}

const THEO_REDIRECT_TARGET = [
  '[[redirects]]',
  '  from = "/api/*"',
  '  to = "/.netlify/functions/theo"',
  '  status = 200',
  '  force = true',
].join('\n')

/**
 * Marks the block this build owns, so it can be REGENERATED rather than merely not duplicated.
 *
 * Idempotence alone would be the wrong contract here: the block carries configuration, so a
 * `security.headers` change has to reach the file. Leaving an existing block in place — which is
 * what the redirect above correctly does, because its content is fixed — would silently pin the
 * baseline to whatever the first build emitted.
 */
const THEO_HEADERS_MARKER = '# Generated by Theo — security baseline (usetheokit/theokit#412)'

/**
 * The `[[headers]]` block telling Netlify's static host the baseline.
 *
 * The emitted function applies these to every response IT returns, and it never returns the HTML
 * document: the `[[redirects]]` block routes only `/api/*`, so the page comes from Netlify's static
 * host and carried none of them. The values come from `buildSecurityHeaders` — the same function
 * the handler calls — rather than being written out here, because two lists of headers that must
 * agree are two lists that eventually do not.
 */
function renderHeadersBlock(securityHeaders: SecurityHeadersConfig | undefined): string {
  const values = buildSecurityHeaders(securityHeaders ?? {}, { production: true })
  return [
    THEO_HEADERS_MARKER,
    '[[headers]]',
    '  for = "/*"',
    '  [headers.values]',
    ...Object.entries(values).map(([k, v]) => `    ${k} = ${JSON.stringify(v)}`),
  ].join('\n')
}

/**
 * Drop a previously generated block, so the next one replaces it.
 *
 * Bounded by the marker and the next top-level section at column 0 (or EOF) — the shape TOML gives
 * a block. A user's own `[[headers]]` is untouched because it does not carry the marker: their
 * file, their rules, and Netlify applies both.
 */
function withoutGeneratedHeaders(source: string): string {
  const lines = source.split(/\r?\n/)
  const start = lines.indexOf(THEO_HEADERS_MARKER)
  if (start < 0) return source

  const opensSection = (line: string | undefined): boolean => (line ?? '').startsWith('[')

  let end = start + 1
  while (end < lines.length && !opensSection(lines[end])) end += 1
  // The marker line itself opens the block, so `end` now sits on the NEXT section — but the block's
  // own `[[headers]]` is the first `[` after the marker, so step past it before scanning again.
  end += 1
  while (end < lines.length && !opensSection(lines[end])) end += 1

  return [...lines.slice(0, start), ...lines.slice(end)].join('\n').replace(/\n{3,}/gu, '\n\n')
}

export function mergeNetlifyToml(
  existing: string | null,
  securityHeaders?: SecurityHeadersConfig,
): string {
  const headersBlock = renderHeadersBlock(securityHeaders)

  if (existing === null || existing.trim().length === 0) {
    return `${THEO_REDIRECT_TARGET}\n\n${headersBlock}\n`
  }

  existing = withoutGeneratedHeaders(existing)

  const blocks = parseRedirectBlocks(existing.split(/\r?\n/))

  // Detect conflict: every `/api/*` block must point at our function.
  for (const b of blocks) {
    if (b.from !== THEO_REDIRECT_FROM) continue
    if (b.to === THEO_REDIRECT_TO) {
      // The redirect is already there. The headers block is regenerated regardless, because it
      // carries configuration and the redirect does not.
      const sep = existing.endsWith('\n') ? '' : '\n'
      return `${existing}${sep}\n${headersBlock}\n`
    }
    throw new NetlifyConflictError(b.from, b.to ?? '(unknown)')
  }

  // No conflict — append target block.
  const sep = existing.endsWith('\n') ? '' : '\n'
  return `${existing}${sep}\n${THEO_REDIRECT_TARGET}\n\n${headersBlock}\n`
}

export async function buildNetlify(
  config: TheoConfig,
  cwd: string,
  deps: NetlifyBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('netlify', readManifest(cwd))

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  const writeFile =
    deps.writeFile ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  const readTomlIfExists =
    deps.readTomlIfExists ??
    (() => {
      const p = resolve(cwd, 'netlify.toml')
      return existsSync(p) ? readFileSync(p, 'utf-8') : null
    })

  // B-338 — scanned on the BUILD machine, like cloudflare and vercel. An absent scanner emits a
  // function with NO routes rather than falling back to a runtime scan: cloudflare's own comment says
  // it, and this adapter was the fallback.
  const scanned = ctx?.scanRoutes?.(config.serverDir)

  const fnDir = resolve(cwd, '.netlify/functions')
  ensureDir(fnDir)
  writeFile(
    resolve(fnDir, 'theo.mjs'),
    renderNetlifyFunction({
      routes: scanned?.routes,
      securityHeaders: config.security?.headers,
      // B-235 — pillar (a): the option existed and no build passed it, so a project with a
      // configured agents directory got the default `agents` on this target. Same defect
      // B-185 fixed for bun and deno, one target over.
      agentsDir: config.agentsDir,
      // B-338 — the same pillar as the comment above, one option over. The sweep in
      // `every-deployed-entry-is-told-its-server-dir.test.ts` could not see this adapter: its
      // population was the adapters that CALL `serverDirLiteral(opts)`, so the one that never
      // adopted it was outside the population the case iterates.
      serverDir: config.serverDir,
      csrf: config.security?.csrf,
      disallowed: config.security?.disallowed,
      cors: config.security?.cors,
      // #425 — a selector, not a transformer, so it rides as a literal like the values above.
      serialization: config.serialization,
    }),
  )

  const existingToml = readTomlIfExists()
  const merged = mergeNetlifyToml(existingToml, config.security?.headers)
  writeFile(resolve(cwd, 'netlify.toml'), merged)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ Netlify output → .netlify/functions/theo.mjs + netlify.toml')
  // eslint-disable-next-line no-console -- CLI build progress
  console.log(
    `${describeDeployedSecurityHeaders({
      target: 'netlify',
      securityHeaders: config.security?.headers,
      mintsNonce: false,
      documentHeaders: 'platform-configured',
    })}\n`,
  )
}

export const netlifyAdapter: DeployAdapter = {
  name: 'netlify',
  streamsResponses: true,
  // #409 / #410 — the generated entry calls `executeRoute` with routes, loader
  // and serverDir only. CSRF, route policy, file middleware and Zod validation
  // still run because they live inside `executeRoute`; none of the remaining
  // configurable concerns reach it. Declared explicitly rather than omitted so
  // the gap is a statement in the source and not an absence.
  //
  // `securityHeaders` IS applied -- to every response this function returns.
  // The document is served by Netlify's static host and does not pass through
  // it (usetheokit/theokit#412).
  appliesConfig: ['securityHeaders', 'csrf', 'disallowed', 'cors', 'serialization'],
  // B-257 — per-invocation: an in-process counter does not survive, so a declared limit needs a durable store.
  enforcesRateLimit: 'with-a-store',
  build(config, cwd, ctx) {
    return buildNetlify(config, cwd, {}, ctx)
  },
}
