/* eslint-disable security/detect-non-literal-fs-filename --
 * Netlify deploy adapter. All paths derived from `cwd` and a fixed
 * `.theokit/netlify/` output layout. Build-time tool — no HTTP input.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'
import type { SecurityHeadersConfig } from '../core/contracts/security-headers.js'
import { assertServicesUnsupported, readManifest } from '../services/index.js'

import { deployedCorsFragment, type DeployedCorsOptions } from './deployed-cors.js'
import { deployedCsrfFragment, type DeployedCsrfOptions } from './deployed-csrf.js'
import { deployedTraceFragment } from './deployed-trace.js'
import { nodeAdapter } from './node.js'
import {
  buildSecurityHeaders,
  describeDeployedSecurityHeaders,
  renderSecurityHeadersConfigLiteral,
} from './security-headers.js'
import type { AdapterBuildContext, DeployAdapter } from './types.js'

export class NetlifyConflictError extends Error {
  constructor(path: string, currentTo: string) {
    super(
      `netlify.toml has a conflicting redirect: "${path}" → "${currentTo}". ` +
        `Remove it manually or edit it to point to "/.netlify/functions/theo" ` +
        `before running the Netlify adapter again.`,
    )
    this.name = 'NetlifyConflictError'
  }
}

export interface NetlifyBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string, ctx?: AdapterBuildContext) => Promise<void>
  writeFile?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
  readTomlIfExists?: () => string | null
}

export function renderNetlifyFunction(
  opts: { securityHeaders?: SecurityHeadersConfig } & DeployedCsrfOptions &
    DeployedCorsOptions = {},
): string {
  return [
    `// Generated by Theo — Netlify Functions adapter`,
    `import { resolve } from 'node:path'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader, extractTraceIdFromRequest, TRACE_HEADER, createCorsWebHandler } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    `import { buildSecurityHeaders, withSecurityHeaders } from 'theokit/adapters/security-headers'`,
    ``,
    `const cwd = process.cwd()`,
    `const serverDir = resolve(cwd, 'server')`,
    `let routesCache = null`,
    `let loaderCache = null`,
    ``,
    `// #410 — the security baseline \`theokit start\` puts on every response,`,
    `// carried here as a literal because the deployed function has no`,
    `// theo.config.ts to read. The netlify.toml redirect routes only /api/* here,`,
    `// so this covers the API and not the document Netlify's static host serves`,
    `// (usetheokit/theokit#412).`,
    `const SECURITY_HEADERS_CONFIG = ${renderSecurityHeadersConfigLiteral(opts.securityHeaders)}`,
    `const SECURITY_HEADERS = buildSecurityHeaders(SECURITY_HEADERS_CONFIG, { production: true })`,
    ``,
    ...deployedCsrfFragment(opts),
    ``,
    ...deployedCorsFragment(opts.cors, 'netlify'),
    ``,
    `export default async (request, context) => {`,
    `  // #409 — the preflight is answered BEFORE anything routes: an OPTIONS the router`,
    `  // handles is an OPTIONS the browser never gets a CORS answer to.`,
    `  const preflight = corsPreflight(request)`,
    `  if (preflight !== null) return withSecurityHeaders(preflight, SECURITY_HEADERS)`,
    `  return withCors(request, withSecurityHeaders(await handleRequest(request), SECURITY_HEADERS))`,
    `}`,
    ``,
    `async function handleRequest(request) {`,
    `  const url = new URL(request.url)`,
    `  if (!url.pathname.startsWith('/api/')) {`,
    `    return new Response('Not Found', { status: 404 })`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `  const match = matchRoute(url.pathname, routesCache)`,
    `  if (!match) {`,
    `    return new Response(JSON.stringify({ error: { code: 'NOT_FOUND' } }), {`,
    `      status: 404,`,
    `      headers: { 'content-type': 'application/json' },`,
    `    })`,
    `  }`,
    ``,
    `  const { req, res, toResponse } = createWebShim(request)`,
    ...deployedTraceFragment('request', '  '),
    `  const method = request.method.toUpperCase()`,
    `  // #382 — the run is not awaited: toResponse() settles at the headers and`,
    `  // carries a live body, so Netlify streams while the handler writes.`,
    `  return toResponse(executeRoute({ route: match.route, method, params: match.params, req, res, loadModule: loaderCache, serverDir, requestId, ...CSRF_CONFIG }))`,
    `}`,
  ].join('\n')
}

const THEO_REDIRECT_FROM = '/api/*'
const THEO_REDIRECT_TO = '/.netlify/functions/theo'

/**
 * TOML merge (EC-2) — non-destructive.
 *
 * We avoid adding a TOML parser dependency by working at the line level. The
 * supported subset is sufficient for the Netlify use case:
 *   - detect existing `[[redirects]]` blocks
 *   - find a block whose `from = "..."` matches our target
 *   - error if such a block points elsewhere
 *   - otherwise append our block
 *
 * Unknown sections (e.g. `[build]`, `[[headers]]`, `[context.production.environment]`)
 * are preserved as-is.
 */
interface NetlifyRedirectBlock {
  startLine: number
  endLine: number
  from?: string
  to?: string
}

function parseRedirectBlocks(lines: readonly string[]): NetlifyRedirectBlock[] {
  const blocks: NetlifyRedirectBlock[] = []
  let current: NetlifyRedirectBlock | null = null

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim()
    if (trimmed === '[[redirects]]') {
      if (current) {
        current.endLine = i - 1
        blocks.push(current)
      }
      current = { startLine: i, endLine: i }
      continue
    }
    if (current && /^\[(\[|[^[])/.test(trimmed)) {
      // Entering another section — close current.
      current.endLine = i - 1
      blocks.push(current)
      current = null
    }
    if (current) {
      const fromMatch = /^from\s*=\s*"([^"]+)"/.exec(trimmed)
      if (fromMatch) current.from = fromMatch[1]
      const toMatch = /^to\s*=\s*"([^"]+)"/.exec(trimmed)
      if (toMatch) current.to = toMatch[1]
      current.endLine = i
    }
  }
  if (current) blocks.push(current)
  return blocks
}

const THEO_REDIRECT_TARGET = [
  '[[redirects]]',
  '  from = "/api/*"',
  '  to = "/.netlify/functions/theo"',
  '  status = 200',
  '  force = true',
].join('\n')

/**
 * Marks the block this build owns, so it can be REGENERATED rather than merely not duplicated.
 *
 * Idempotence alone would be the wrong contract here: the block carries configuration, so a
 * `security.headers` change has to reach the file. Leaving an existing block in place — which is
 * what the redirect above correctly does, because its content is fixed — would silently pin the
 * baseline to whatever the first build emitted.
 */
const THEO_HEADERS_MARKER = '# Generated by Theo — security baseline (usetheokit/theokit#412)'

/**
 * The `[[headers]]` block telling Netlify's static host the baseline.
 *
 * The emitted function applies these to every response IT returns, and it never returns the HTML
 * document: the `[[redirects]]` block routes only `/api/*`, so the page comes from Netlify's static
 * host and carried none of them. The values come from `buildSecurityHeaders` — the same function
 * the handler calls — rather than being written out here, because two lists of headers that must
 * agree are two lists that eventually do not.
 */
function renderHeadersBlock(securityHeaders: SecurityHeadersConfig | undefined): string {
  const values = buildSecurityHeaders(securityHeaders ?? {}, { production: true })
  return [
    THEO_HEADERS_MARKER,
    '[[headers]]',
    '  for = "/*"',
    '  [headers.values]',
    ...Object.entries(values).map(([k, v]) => `    ${k} = ${JSON.stringify(v)}`),
  ].join('\n')
}

/**
 * Drop a previously generated block, so the next one replaces it.
 *
 * Bounded by the marker and the next top-level section at column 0 (or EOF) — the shape TOML gives
 * a block. A user's own `[[headers]]` is untouched because it does not carry the marker: their
 * file, their rules, and Netlify applies both.
 */
function withoutGeneratedHeaders(source: string): string {
  const lines = source.split(/\r?\n/)
  const start = lines.indexOf(THEO_HEADERS_MARKER)
  if (start < 0) return source

  const opensSection = (line: string | undefined): boolean => (line ?? '').startsWith('[')

  let end = start + 1
  while (end < lines.length && !opensSection(lines[end])) end += 1
  // The marker line itself opens the block, so `end` now sits on the NEXT section — but the block's
  // own `[[headers]]` is the first `[` after the marker, so step past it before scanning again.
  end += 1
  while (end < lines.length && !opensSection(lines[end])) end += 1

  return [...lines.slice(0, start), ...lines.slice(end)].join('\n').replace(/\n{3,}/gu, '\n\n')
}

export function mergeNetlifyToml(
  existing: string | null,
  securityHeaders?: SecurityHeadersConfig,
): string {
  const headersBlock = renderHeadersBlock(securityHeaders)

  if (existing === null || existing.trim().length === 0) {
    return `${THEO_REDIRECT_TARGET}\n\n${headersBlock}\n`
  }

  existing = withoutGeneratedHeaders(existing)

  const blocks = parseRedirectBlocks(existing.split(/\r?\n/))

  // Detect conflict: every `/api/*` block must point at our function.
  for (const b of blocks) {
    if (b.from !== THEO_REDIRECT_FROM) continue
    if (b.to === THEO_REDIRECT_TO) {
      // The redirect is already there. The headers block is regenerated regardless, because it
      // carries configuration and the redirect does not.
      const sep = existing.endsWith('\n') ? '' : '\n'
      return `${existing}${sep}\n${headersBlock}\n`
    }
    throw new NetlifyConflictError(b.from, b.to ?? '(unknown)')
  }

  // No conflict — append target block.
  const sep = existing.endsWith('\n') ? '' : '\n'
  return `${existing}${sep}\n${THEO_REDIRECT_TARGET}\n\n${headersBlock}\n`
}

export async function buildNetlify(
  config: TheoConfig,
  cwd: string,
  deps: NetlifyBuildDeps = {},
  ctx?: AdapterBuildContext,
): Promise<void> {
  // Wave 2 (T2.2) — reject polyglot services on this adapter.
  assertServicesUnsupported('netlify', readManifest(cwd))

  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd, ctx)

  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  const writeFile =
    deps.writeFile ??
    ((p, c) => {
      writeFileSync(p, c)
    })
  const readTomlIfExists =
    deps.readTomlIfExists ??
    (() => {
      const p = resolve(cwd, 'netlify.toml')
      return existsSync(p) ? readFileSync(p, 'utf-8') : null
    })

  const fnDir = resolve(cwd, '.netlify/functions')
  ensureDir(fnDir)
  writeFile(
    resolve(fnDir, 'theo.mjs'),
    renderNetlifyFunction({
      securityHeaders: config.security?.headers,
      csrf: config.security?.csrf,
      disallowed: config.security?.disallowed,
      cors: config.security?.cors,
    }),
  )

  const existingToml = readTomlIfExists()
  const merged = mergeNetlifyToml(existingToml, config.security?.headers)
  writeFile(resolve(cwd, 'netlify.toml'), merged)

  // eslint-disable-next-line no-console -- CLI build progress
  console.log('\n  ✓ Netlify output → .netlify/functions/theo.mjs + netlify.toml')
  // eslint-disable-next-line no-console -- CLI build progress
  console.log(
    `${describeDeployedSecurityHeaders({
      target: 'netlify',
      securityHeaders: config.security?.headers,
      mintsNonce: false,
      documentServedByPlatform: true,
    })}\n`,
  )
}

export const netlifyAdapter: DeployAdapter = {
  name: 'netlify',
  streamsResponses: true,
  // #409 / #410 — the generated entry calls `executeRoute` with routes, loader
  // and serverDir only. CSRF, route policy, file middleware and Zod validation
  // still run because they live inside `executeRoute`; none of the remaining
  // configurable concerns reach it. Declared explicitly rather than omitted so
  // the gap is a statement in the source and not an absence.
  //
  // `securityHeaders` IS applied -- to every response this function returns.
  // The document is served by Netlify's static host and does not pass through
  // it (usetheokit/theokit#412).
  appliesConfig: ['securityHeaders', 'csrf', 'disallowed', 'cors'],
  build(config, cwd, ctx) {
    return buildNetlify(config, cwd, {}, ctx)
  },
}
