import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { DeployAdapter } from './types.js'
import type { TheoConfig } from '../config/schema.js'
import { nodeAdapter } from './node.js'

export class NetlifyConflictError extends Error {
  constructor(path: string, currentTo: string) {
    super(
      `netlify.toml has a conflicting redirect: "${path}" → "${currentTo}". ` +
        `Remove it manually or edit it to point to "/.netlify/functions/theo" ` +
        `before running the Netlify adapter again.`,
    )
    this.name = 'NetlifyConflictError'
  }
}

export interface NetlifyBuildDeps {
  runNodeBuild?: (config: TheoConfig, cwd: string) => Promise<void>
  writeFile?: (path: string, content: string) => void
  ensureDir?: (path: string) => void
  readTomlIfExists?: () => string | null
}

export function renderNetlifyFunction(): string {
  return [
    `// Generated by Theo — Netlify Functions adapter`,
    `import { resolve } from 'node:path'`,
    `import { randomUUID } from 'node:crypto'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    ``,
    `const cwd = process.cwd()`,
    `const serverDir = resolve(cwd, 'server')`,
    `let routesCache = null`,
    `let loaderCache = null`,
    ``,
    `export default async (request, context) => {`,
    `  const url = new URL(request.url)`,
    `  if (!url.pathname.startsWith('/api/')) {`,
    `    return new Response('Not Found', { status: 404 })`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `  const match = matchRoute(url.pathname, routesCache)`,
    `  if (!match) {`,
    `    return new Response(JSON.stringify({ error: { code: 'NOT_FOUND' } }), {`,
    `      status: 404,`,
    `      headers: { 'content-type': 'application/json' },`,
    `    })`,
    `  }`,
    ``,
    `  const { req, res, toResponse } = createWebShim(request)`,
    `  const requestId = randomUUID()`,
    `  const method = request.method.toUpperCase()`,
    `  await executeRoute(match.route, method, match.params, req, res, loaderCache, serverDir, requestId)`,
    `  return toResponse()`,
    `}`,
  ].join('\n')
}

const THEO_REDIRECT_FROM = '/api/*'
const THEO_REDIRECT_TO = '/.netlify/functions/theo'

/**
 * TOML merge (EC-2) — non-destructive.
 *
 * We avoid adding a TOML parser dependency by working at the line level. The
 * supported subset is sufficient for the Netlify use case:
 *   - detect existing `[[redirects]]` blocks
 *   - find a block whose `from = "..."` matches our target
 *   - error if such a block points elsewhere
 *   - otherwise append our block
 *
 * Unknown sections (e.g. `[build]`, `[[headers]]`, `[context.production.environment]`)
 * are preserved as-is.
 */
export function mergeNetlifyToml(existing: string | null): string {
  const target = [
    '[[redirects]]',
    '  from = "/api/*"',
    '  to = "/.netlify/functions/theo"',
    '  status = 200',
    '  force = true',
  ].join('\n')

  if (existing === null || existing.trim().length === 0) {
    return target + '\n'
  }

  // Parse blocks: split on lines, track `[[redirects]]` sections and their
  // `from`/`to` values.
  const lines = existing.split(/\r?\n/)
  type Block = { startLine: number; endLine: number; from?: string; to?: string }
  const blocks: Block[] = []
  let current: Block | null = null

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    const trimmed = line.trim()
    if (trimmed === '[[redirects]]') {
      if (current) {
        current.endLine = i - 1
        blocks.push(current)
      }
      current = { startLine: i, endLine: i }
      continue
    }
    if (current && /^\[(\[|[^[])/.test(trimmed)) {
      // entering another section — close current
      current.endLine = i - 1
      blocks.push(current)
      current = null
    }
    if (current) {
      const fromMatch = trimmed.match(/^from\s*=\s*"([^"]+)"/)
      if (fromMatch) current.from = fromMatch[1]
      const toMatch = trimmed.match(/^to\s*=\s*"([^"]+)"/)
      if (toMatch) current.to = toMatch[1]
      current.endLine = i
    }
  }
  if (current) blocks.push(current)

  // Detect conflict: every `/api/*` block must point at our function.
  for (const b of blocks) {
    if (b.from === THEO_REDIRECT_FROM) {
      if (b.to === THEO_REDIRECT_TO) {
        // Already merged — return existing as-is (idempotent).
        return existing.endsWith('\n') ? existing : existing + '\n'
      }
      throw new NetlifyConflictError(b.from, b.to ?? '(unknown)')
    }
  }

  // No conflict — append target block.
  const sep = existing.endsWith('\n') ? '' : '\n'
  return existing + sep + '\n' + target + '\n'
}

export async function buildNetlify(
  config: TheoConfig,
  cwd: string,
  deps: NetlifyBuildDeps = {},
): Promise<void> {
  const runNodeBuild = deps.runNodeBuild ?? nodeAdapter.build.bind(nodeAdapter)
  await runNodeBuild(config, cwd)

  const ensureDir = deps.ensureDir ?? ((p: string) => mkdirSync(p, { recursive: true }))
  const writeFile = deps.writeFile ?? ((p, c) => writeFileSync(p, c))
  const readTomlIfExists =
    deps.readTomlIfExists ??
    (() => {
      const p = resolve(cwd, 'netlify.toml')
      return existsSync(p) ? readFileSync(p, 'utf-8') : null
    })

  const fnDir = resolve(cwd, '.netlify/functions')
  ensureDir(fnDir)
  writeFile(resolve(fnDir, 'theo.mjs'), renderNetlifyFunction())

  const existingToml = readTomlIfExists()
  const merged = mergeNetlifyToml(existingToml)
  writeFile(resolve(cwd, 'netlify.toml'), merged)

  console.log('\n  ✓ Netlify output → .netlify/functions/theo.mjs + netlify.toml\n')
}

export const netlifyAdapter: DeployAdapter = {
  name: 'netlify',
  build(config, cwd) {
    return buildNetlify(config, cwd)
  },
}
