import { existsSync, mkdirSync, writeFileSync, cpSync } from 'node:fs'
import { resolve, join } from 'node:path'
import type { DeployAdapter } from './types.js'
import type { TheoConfig } from '../config/schema.js'
import { nodeAdapter } from './node.js'

export const vercelAdapter: DeployAdapter = {
  name: 'vercel',

  async build(config: TheoConfig, cwd: string): Promise<void> {
    // 1. Run the standard Node build first
    await nodeAdapter.build(config, cwd)

    const clientDir = resolve(cwd, '.theo/client')
    const outputDir = resolve(cwd, '.vercel/output')

    // 2. Create .vercel/output structure
    mkdirSync(resolve(outputDir, 'static'), { recursive: true })
    mkdirSync(resolve(outputDir, 'functions/api.func'), { recursive: true })

    // 3. Copy static assets
    if (existsSync(clientDir)) {
      cpSync(clientDir, resolve(outputDir, 'static'), { recursive: true })
    }

    // 4. Generate serverless function entry
    // This wraps Theo's production server handler for Vercel's serverless runtime
    const functionEntry = [
      `// Generated by Theo — Vercel Adapter`,
      `// Environment variables are resolved at RUNTIME, not build time (EC-1)`,
      `export default async function handler(req, res) {`,
      `  const { createServer } = await import('node:http');`,
      `  const { resolve } = await import('node:path');`,
      `  const { existsSync } = await import('node:fs');`,
      `  const serverDir = resolve(process.cwd(), 'server');`,
      `  // Lazy-load Theo server modules`,
      `  const { scanServerRoutes } = await import('./theo-server/scan.js');`,
      `  const { matchRoute } = await import('./theo-server/match.js');`,
      `  const { executeRoute, sendError } = await import('./theo-server/execute.js');`,
      `  const { createProductionLoader } = await import('./theo-server/module-loader.js');`,
      `  const loadModule = createProductionLoader();`,
      `  const url = req.url ?? '/';`,
      `  if (url.startsWith('/api/')) {`,
      `    const routes = scanServerRoutes(serverDir);`,
      `    const match = matchRoute(url, routes);`,
      `    if (!match) { sendError(res, 'NOT_FOUND', 'API route not found', 404); return; }`,
      `    const method = (req.method ?? 'GET').toUpperCase();`,
      `    await executeRoute(match.route, method, match.params, req, res, loadModule, serverDir);`,
      `    return;`,
      `  }`,
      `  // SPA fallback — Vercel serves static index.html via routing`,
      `  res.writeHead(200, { 'Content-Type': 'text/html' });`,
      `  res.end('<html><body>SPA fallback</body></html>');`,
      `}`,
    ].join('\n')

    writeFileSync(resolve(outputDir, 'functions/api.func/index.mjs'), functionEntry)

    // 5. Generate .vc-config.json
    const vcConfig = {
      runtime: 'nodejs22.x',
      handler: 'index.mjs',
      launcherType: 'Nodejs',
      shouldAddHelpers: true,
    }
    writeFileSync(
      resolve(outputDir, 'functions/api.func/.vc-config.json'),
      JSON.stringify(vcConfig, null, 2),
    )

    // 6. Generate config.json (routing)
    const routingConfig = {
      version: 3,
      routes: [
        { src: '/api/(.*)', dest: '/api' },
        { handle: 'filesystem' },
        { src: '/(.*)', dest: '/index.html' },
      ],
    }
    writeFileSync(
      resolve(outputDir, 'config.json'),
      JSON.stringify(routingConfig, null, 2),
    )

    console.log('\n  ✓ Vercel output → .vercel/output/\n')
  },
}
