/* eslint-disable security/detect-non-literal-fs-filename --
 * Vercel deploy adapter. All paths derived from `cwd` and a fixed
 * `.theo/vercel/` output layout. Build-time tool — no HTTP input.
 */
import { existsSync, mkdirSync, writeFileSync, cpSync } from 'node:fs'
import { resolve } from 'node:path'

import type { TheoConfig } from '../config/schema.js'

import { nodeAdapter } from './node.js'
import type { DeployAdapter } from './types.js'

/**
 * T2.2 — Vercel adapter rewritten to consume `theokit/adapters/web-shim`
 * instead of emitting an inline plain-object Request/Response shim and
 * lazy-importing internal `theo-server/` paths.
 */

export function renderVercelFunctionEntry(): string {
  return [
    `// Generated by Theo — Vercel Functions adapter`,
    `// Environment variables are resolved at RUNTIME, not build time.`,
    ``,
    `import { randomUUID } from 'node:crypto'`,
    `import { resolve } from 'node:path'`,
    `import { scanServerRoutes, matchRoute, executeRoute, createProductionLoader } from 'theokit/server'`,
    `import { createWebShim } from 'theokit/adapters/web-shim'`,
    ``,
    `// Cold-start cache`,
    `let routesCache = null`,
    `let loaderCache = null`,
    `const serverDir = resolve(process.cwd(), 'server')`,
    ``,
    `// Vercel Functions invoke this default export with a (req, res) pair`,
    `// (Node IncomingMessage-style). We convert it to a Web Request, run the`,
    `// pipeline through the shim, and pipe the Response back.`,
    `export default async function handler(nodeReq, nodeRes) {`,
    `  const url = new URL(nodeReq.url ?? '/', 'http://' + (nodeReq.headers?.host ?? 'localhost'))`,
    ``,
    `  if (!url.pathname.startsWith('/api/')) {`,
    `    nodeRes.statusCode = 404`,
    `    nodeRes.end('Not Found')`,
    `    return`,
    `  }`,
    ``,
    `  if (!routesCache) routesCache = scanServerRoutes(serverDir)`,
    `  if (!loaderCache) loaderCache = createProductionLoader()`,
    ``,
    `  const match = matchRoute(url.pathname, routesCache)`,
    `  if (!match) {`,
    `    nodeRes.statusCode = 404`,
    `    nodeRes.setHeader('Content-Type', 'application/json')`,
    `    nodeRes.end(JSON.stringify({ error: { code: 'NOT_FOUND' } }))`,
    `    return`,
    `  }`,
    ``,
    `  // Convert Node-style req to Web Request for the shim`,
    `  const headers = new Headers()`,
    `  for (const [k, v] of Object.entries(nodeReq.headers ?? {})) {`,
    `    if (typeof v === 'string') headers.set(k, v)`,
    `  }`,
    `  let body`,
    `  const method = (nodeReq.method ?? 'GET').toUpperCase()`,
    `  if (method !== 'GET' && method !== 'HEAD') {`,
    `    const chunks = []`,
    `    await new Promise((resolveProm, rejectProm) => {`,
    `      nodeReq.on('data', (c) => chunks.push(c))`,
    `      nodeReq.on('end', () => resolveProm())`,
    `      nodeReq.on('error', rejectProm)`,
    `    })`,
    `    body = Buffer.concat(chunks)`,
    `  }`,
    `  const webRequest = new Request(url.toString(), { method, headers, body })`,
    ``,
    `  const { req, res, toResponse } = createWebShim(webRequest)`,
    `  const requestId = randomUUID()`,
    `  await executeRoute(`,
    `    match.route, method, match.params,`,
    `    req, res, loaderCache, serverDir, requestId,`,
    `  )`,
    `  const webResponse = await toResponse()`,
    ``,
    `  nodeRes.statusCode = webResponse.status`,
    `  webResponse.headers.forEach((v, k) => nodeRes.setHeader(k, v))`,
    `  const text = await webResponse.text()`,
    `  nodeRes.end(text)`,
    `}`,
  ].join('\n')
}

export interface VercelRoutingRule {
  src?: string
  dest?: string
  handle?: string
}

export function renderVercelConfigJson(): {
  version: number
  routes: VercelRoutingRule[]
} {
  return {
    version: 3,
    routes: [
      { src: '/api/(.*)', dest: '/api' },
      { handle: 'filesystem' },
      { src: '/(.*)', dest: '/index.html' },
    ],
  }
}

export function renderVercelVcConfigJson(): {
  runtime: string
  handler: string
  launcherType: string
  shouldAddHelpers: boolean
} {
  return {
    runtime: 'nodejs22.x',
    handler: 'index.mjs',
    launcherType: 'Nodejs',
    shouldAddHelpers: true,
  }
}

export const vercelAdapter: DeployAdapter = {
  name: 'vercel',

  async build(config: TheoConfig, cwd: string): Promise<void> {
    // 1. Run the standard Node build first
    await nodeAdapter.build(config, cwd)

    const clientDir = resolve(cwd, '.theo/client')
    const outputDir = resolve(cwd, '.vercel/output')

    // 2. Create .vercel/output structure
    mkdirSync(resolve(outputDir, 'static'), { recursive: true })
    mkdirSync(resolve(outputDir, 'functions/api.func'), { recursive: true })

    // 3. Copy static assets
    if (existsSync(clientDir)) {
      cpSync(clientDir, resolve(outputDir, 'static'), { recursive: true })
    }

    // 4. Emit serverless function entry (now uses shared web-shim)
    writeFileSync(resolve(outputDir, 'functions/api.func/index.mjs'), renderVercelFunctionEntry())

    // 5. Emit .vc-config.json
    writeFileSync(
      resolve(outputDir, 'functions/api.func/.vc-config.json'),
      JSON.stringify(renderVercelVcConfigJson(), null, 2),
    )

    // 6. Emit config.json (routing)
    writeFileSync(
      resolve(outputDir, 'config.json'),
      JSON.stringify(renderVercelConfigJson(), null, 2),
    )

    // eslint-disable-next-line no-console -- CLI build progress
    console.log('\n  ✓ Vercel output → .vercel/output/\n')
  },
}
