#!/usr/bin/env node
/**
 * Generate the Tauri externalBin launcher for the Node sidecar.
 *
 * The Rust shell spawns the agent turn via `app.shell().sidecar("theo-sidecar")` (src-tauri/src/lib.rs),
 * which Tauri resolves to `src-tauri/binaries/theo-sidecar-<target-triple>[.exe]`. That file must exist
 * before `tauri dev`/`tauri build` — this script creates it. It is wired into `beforeDevCommand` /
 * `beforeBuildCommand` in `src-tauri/tauri.conf.json`, so it runs automatically and is regenerated
 * (with the current absolute path) on every launch.
 *
 * The launcher is a tiny shim that runs `sidecar/sidecar.ts` via the app's own `tsx` — no bundle/compile
 * step, and the sidecar runs under **Node**, where the ai-sdk streams correctly (a `bun build --compile`
 * self-contained binary drops the token stream). This is the dev path. For a DISTRIBUTABLE desktop app
 * (`tauri build`), ship a real self-contained sidecar binary instead — see README-surface.md § Packaging.
 */
import { execFileSync } from 'node:child_process'
import { chmodSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** The Rust host target triple — Tauri's externalBin filename suffix. */
function targetTriple() {
  try {
    const out = execFileSync('rustc', ['-vV'], { encoding: 'utf-8' })
    const match = out.match(/host:\s*(\S+)/)
    if (!match) throw new Error('could not parse `host:` from `rustc -vV`')
    return match[1]
  } catch (err) {
    throw new Error(
      `[build-sidecar] the Tauri desktop build needs the Rust toolchain (rustc) to resolve the ` +
        `externalBin target triple. Install it: https://v2.tauri.app/start/prerequisites/\n` +
        `Underlying error: ${err instanceof Error ? err.message : String(err)}`,
    )
  }
}

const triple = targetTriple()
const isWindows = process.platform === 'win32'
const binDir = join(appRoot, 'src-tauri', 'binaries')
mkdirSync(binDir, { recursive: true })

const tsxBin = join(appRoot, 'node_modules', '.bin', isWindows ? 'tsx.cmd' : 'tsx')
const entry = join(appRoot, 'sidecar', 'sidecar.ts')

if (isWindows) {
  // Tauri resolves the Windows sidecar as `<name>-<triple>.exe`, which must be a real PE executable —
  // a shell/batch shim cannot satisfy that. Fail loud with the packaging path (Rule 8: fail clear).
  throw new Error(
    `[build-sidecar] Windows desktop dev needs a compiled sidecar binary at ` +
      `src-tauri/binaries/theo-sidecar-${triple}.exe (Tauri requires a real .exe). ` +
      `Compile sidecar/sidecar.ts to a self-contained binary — see README-surface.md § Packaging — ` +
      `then re-run. macOS/Linux dev uses the tsx shim this script writes automatically.`,
  )
}

// macOS/Linux: an executable POSIX shim that execs the app's tsx on the sidecar source. Absolute paths
// keep it valid no matter where Tauri invokes it from; it is regenerated each launch so a moved project
// self-heals on the next `tauri dev`.
const shimPath = join(binDir, `theo-sidecar-${triple}`)
const shim = `#!/bin/sh\n# Generated by scripts/build-sidecar.mjs — do not edit (regenerated each launch).\nexec "${tsxBin}" "${entry}" "$@"\n`
writeFileSync(shimPath, shim)
chmodSync(shimPath, 0o755)

process.stdout.write(`[build-sidecar] wrote ${shimPath}\n`)
