/* eslint-disable security/detect-non-literal-fs-filename --
 * CLI `theo docker`. Writes Dockerfile + .dockerignore under user's `cwd`.
 * Build-time tool. No HTTP input.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function detectPkgManager(cwd: string): 'pnpm' | 'npm' | 'yarn' {
  if (existsSync(resolve(cwd, 'pnpm-lock.yaml'))) return 'pnpm'
  if (existsSync(resolve(cwd, 'yarn.lock'))) return 'yarn'
  return 'npm'
}

function generateDockerfile(pkgManager: 'pnpm' | 'npm' | 'yarn'): string {
  const installCmd = {
    pnpm: 'RUN corepack enable && pnpm install --frozen-lockfile',
    npm: 'RUN npm ci',
    yarn: 'RUN yarn install --frozen-lockfile',
  }[pkgManager]

  const lockfile = {
    pnpm: 'pnpm-lock.yaml',
    npm: 'package-lock.json',
    yarn: 'yarn.lock',
  }[pkgManager]

  const runBuild = {
    pnpm: 'RUN pnpm theo build',
    npm: 'RUN npx theo build',
    yarn: 'RUN yarn theo build',
  }[pkgManager]

  const startCmd = {
    pnpm: 'CMD ["pnpm", "theo", "start"]',
    npm: 'CMD ["npx", "theo", "start"]',
    yarn: 'CMD ["yarn", "theo", "start"]',
  }[pkgManager]

  return [
    '# Generated by Theo',
    '# Multi-stage build for production',
    '',
    '# Stage 1: Build',
    'FROM node:22-alpine AS builder',
    'WORKDIR /app',
    `COPY package.json ${lockfile} ./`,
    installCmd,
    'COPY . .',
    runBuild,
    '',
    '# Stage 2: Production',
    'FROM node:22-alpine AS runner',
    'WORKDIR /app',
    'ENV NODE_ENV=production',
    'COPY --from=builder /app/.theo ./.theo',
    'COPY --from=builder /app/server ./server',
    'COPY --from=builder /app/theo.config.ts ./theo.config.ts',
    'COPY --from=builder /app/package.json ./package.json',
    `COPY --from=builder /app/${lockfile} ./${lockfile}`,
    'COPY --from=builder /app/node_modules ./node_modules',
    '',
    'EXPOSE 3000',
    startCmd,
    '',
  ].join('\n')
}

function generateDockerignore(): string {
  return [
    'node_modules',
    '.git',
    '.theo',
    'dist',
    '.env',
    '.env.*',
    '!.env.example',
    '*.log',
    '.DS_Store',
    '.vscode',
    '.idea',
    'Dockerfile',
    '.dockerignore',
    '',
  ].join('\n')
}

// eslint-disable-next-line @typescript-eslint/require-await -- CLI surface contract is async; sync today is implementation detail
export async function dockerCommand(options?: { force?: boolean }): Promise<void> {
  const cwd = process.cwd()
  const dockerfilePath = resolve(cwd, 'Dockerfile')
  const dockerignorePath = resolve(cwd, '.dockerignore')

  if (existsSync(dockerfilePath) && !options?.force) {
    console.log('\n  ⚠ Dockerfile already exists. Use --force to overwrite.\n')
    return
  }

  const pkgManager = detectPkgManager(cwd)
  writeFileSync(dockerfilePath, generateDockerfile(pkgManager))
  writeFileSync(dockerignorePath, generateDockerignore())

  console.log(`\n  ✓ Generated Dockerfile (${pkgManager})`)
  console.log(`  ✓ Generated .dockerignore`)
  console.log(`\n  Next steps:`)
  console.log(`    docker build -t my-app .`)
  console.log(`    docker run -p 3000:3000 my-app\n`)
}
