/* eslint-disable security/detect-non-literal-fs-filename --
 * CLI `theo generate`. Writes scaffolded files under `cwd` + a generator
 * name from CLI args. Build-time tool. No HTTP input.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

export const VALID_TYPES = ['route', 'action', 'page', 'ws', 'controller', 'agent', 'toolbox'] as const
export type GeneratorType = (typeof VALID_TYPES)[number]

export interface GenerateOptions {
  cwd: string
  type: string
  name: string
}

export type GenerateStatus =
  | 'created'
  | 'already_exists'
  | 'invalid_kind'
  | 'invalid_name'
  | 'not_a_project'

export interface GenerateResult {
  status: GenerateStatus
  filePath?: string
  kind?: GeneratorType
  name?: string
  message?: string
}

function toKebabCase(name: string): boolean {
  return /^[a-z][a-z0-9/-]*$/.test(name)
}

/**
 * Reserved JS identifier names that conflict with object prototype machinery
 * or would shadow built-in module shapes if used as action/route names.
 * Mirrors action-scan's RESERVED_NAMES (T1.4).
 */
const RESERVED_BASENAMES = new Set([
  'index',
  'constructor',
  '__proto__',
  'prototype',
  'hasOwnProperty',
])

/**
 * Validate that a name segment doesn't hit the reserved-identifier list.
 * Checks the BASENAME (last `/` segment) — nested `admin/constructor` still
 * rejected because the file `constructor.ts` would be the conflict.
 */
function hasReservedSegment(name: string): boolean {
  const basename = name.includes('/') ? (name.split('/').pop() ?? name) : name
  return RESERVED_BASENAMES.has(basename)
}

/**
 * EC-4: validate that resolving `targetSubpath` under `cwd` stays inside `cwd`.
 * Returns `true` when path is safe (stays inside), `false` when it escapes via
 * `..`, absolute path, null byte, or similar traversal vector.
 */
function isPathInside(cwd: string, targetSubpath: string): boolean {
  if (targetSubpath.includes('\x00')) return false
  if (targetSubpath.startsWith('/') || targetSubpath.startsWith('\\')) return false
  const resolved = resolve(cwd, targetSubpath)
  const cwdResolved = resolve(cwd)
  const sep = process.platform === 'win32' ? '\\' : '/'
  return resolved === cwdResolved || resolved.startsWith(cwdResolved + sep)
}

function toPascalCase(name: string): string {
  return name
    .split(/[-/]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

function toCamelCase(name: string): string {
  const pascal = toPascalCase(name)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function generateRouteTemplate(name: string): string {
  return [
    `import { defineRoute } from 'theokit/server'`,
    `import { z } from 'zod'`,
    ``,
    `export const GET = defineRoute({`,
    `  handler: ({ ctx }) => {`,
    `    return { message: 'TODO: implement ${name} GET' }`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

function generateControllerTemplate(name: string): string {
  const className = toPascalCase(name) + 'Controller'
  const baseName = name.split('/').pop() ?? name
  return [
    `// AUTO-GENERATED by \`theokit generate controller ${name}\``,
    `import { Controller, Get } from '@theokit/http'`,
    ``,
    `@Controller('${baseName}')`,
    `export class ${className} {`,
    `  @Get()`,
    `  findAll(): string {`,
    `    return 'This action returns all ${baseName}'`,
    `  }`,
    `}`,
    ``,
  ].join('\n')
}

function generateActionTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { defineAction } from 'theokit/server'`,
    `import { z } from 'zod'`,
    ``,
    `export const ${camel} = defineAction({`,
    `  input: z.object({}),`,
    `  handler: ({ input, ctx }) => {`,
    `    return { message: 'TODO: implement ${name}' }`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

/**
 * Co-located test template for `theokit generate action <name>` (T5.2 +
 * plan Q4 cenário 1: roundtrip serialize). Skeleton uses vitest BDD shape
 * per testing.md.
 */
function generateAgentTemplate(name: string): string {
  const pascal = toPascalCase(name)
  return [
    `import 'reflect-metadata'`,
    `import { Agent, MainLoop } from '@theokit/agents'`,
    `import { UseGuards } from '@theokit/http'`,
    ``,
    `@Agent({`,
    `  name: '${name}',`,
    `  route: '/api/agents/${name}',`,
    `  model: 'openai/gpt-4o-mini',`,
    `  systemPrompt: 'You are a helpful ${name} assistant.',`,
    `})`,
    `export class ${pascal}Agent {`,
    `  @MainLoop({ strategy: 'react', maxIterations: 5 })`,
    `  async run() {}`,
    `}`,
    ``,
  ].join('\n')
}

function generateToolboxTemplate(name: string): string {
  const pascal = toPascalCase(name)
  return [
    `import 'reflect-metadata'`,
    `import { z } from 'zod'`,
    `import { Toolbox, Tool } from '@theokit/agents'`,
    ``,
    `@Toolbox({ namespace: '${name}' })`,
    `export class ${pascal}Tools {`,
    `  @Tool({`,
    `    name: 'hello',`,
    `    description: 'Say hello',`,
    `    input: z.object({ name: z.string() }),`,
    `  })`,
    `  async hello(input: { name: string }) {`,
    `    return \`Hello, \${input.name}!\``,
    `  }`,
    `}`,
    ``,
  ].join('\n')
}

function resolveTemplate(
  cwd: string,
  type: GeneratorType,
  name: string,
): { filePath: string; content: string } | null {
  switch (type) {
    case 'route':
      return {
        filePath: resolve(cwd, 'server/routes', `${name}.ts`),
        content: generateRouteTemplate(name),
      }
    case 'action':
      return {
        filePath: resolve(cwd, 'server/actions', `${name}.ts`),
        content: generateActionTemplate(name),
      }
    case 'page':
      return { filePath: resolve(cwd, `app/${name}/page.tsx`), content: generatePageTemplate(name) }
    case 'ws':
      return {
        filePath: resolve(cwd, 'server/ws', `${name}.ts`),
        content: generateWsTemplate(name),
      }
    case 'controller':
      return {
        filePath: resolve(cwd, 'server/controllers', `${name}.controller.ts`),
        content: generateControllerTemplate(name),
      }
    case 'agent':
      return {
        filePath: resolve(cwd, 'server/agents', `${name}.agent.ts`),
        content: generateAgentTemplate(name),
      }
    case 'toolbox':
      return {
        filePath: resolve(cwd, 'server/toolboxes', `${name}.tools.ts`),
        content: generateToolboxTemplate(name),
      }
    default:
      return null
  }
}

function generateActionTestTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { describe, it, expect } from 'vitest'`,
    ``,
    `import { ${camel} } from './${name.split('/').pop()}.js'`,
    ``,
    `describe('${name} action', () => {`,
    `  it('should accept a valid input shape', () => {`,
    `    expect(${camel}.input).toBeDefined()`,
    `    expect(typeof ${camel}.handler).toBe('function')`,
    `  })`,
    ``,
    `  it('should reject invalid input via zod schema', () => {`,
    `    const parsed = ${camel}.input.safeParse({ __invalid: true })`,
    `    // Empty object schema accepts {}; tighten this assertion when adding fields.`,
    `    expect(parsed.success).toBe(true)`,
    `  })`,
    `})`,
    ``,
  ].join('\n')
}

function generatePageTemplate(name: string): string {
  const pascal = toPascalCase(name)
  return [`export default function ${pascal}Page() {`, `  return <h1>${pascal}</h1>`, `}`, ``].join(
    '\n',
  )
}

function generateWsTemplate(_name: string): string {
  return [
    `import { defineWebSocket } from 'theokit/server'`,
    ``,
    `export default defineWebSocket({`,
    `  onMessage(ws, data) {`,
    `    ws.send(\`echo: \${data}\`)`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

/**
 * Programmatic generate. Returns a structured result instead of throwing —
 * Studio (`theokit_generate` tool) consumes this directly. The CLI wrapper
 * below maps the structured result to console output + exit code semantics.
 */
// eslint-disable-next-line @typescript-eslint/require-await
export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  const { cwd, type, name } = opts

  if (!existsSync(resolve(cwd, 'theo.config.ts')) && !existsSync(resolve(cwd, 'theo.config.js'))) {
    return {
      status: 'not_a_project',
      message: 'Not a Theo project. cwd has no theo.config.ts or theo.config.js',
    }
  }

  if (!VALID_TYPES.includes(type as GeneratorType)) {
    return {
      status: 'invalid_kind',
      message: `Invalid generator type "${type}". Available: ${VALID_TYPES.join(', ')}`,
    }
  }

  if (!name || !toKebabCase(name)) {
    return {
      status: 'invalid_name',
      message: `Invalid name "${name}". Use kebab-case: lowercase letters, numbers, hyphens.`,
    }
  }

  // EC-2-related: reject reserved JS identifier basenames (would shadow
  // built-in prototype machinery in virtual module emit or scan).
  if (hasReservedSegment(name)) {
    return {
      status: 'invalid_name',
      message: `Reserved name "${name}" — basename collides with built-in identifier (index/constructor/__proto__/prototype/hasOwnProperty).`,
    }
  }

  const resolved = resolveTemplate(cwd, type as GeneratorType, name)
  if (resolved === null) {
    return { status: 'invalid_kind', message: `Unknown type: ${type}` }
  }
  const { filePath, content } = resolved

  // EC-4: confirm the resolved filePath stays inside cwd. `toKebabCase`
  // already rejects most traversal vectors but a defense-in-depth check
  // against `..` slipping in via valid-looking segments is cheap.
  const relativeFromCwd = filePath.startsWith(resolve(cwd))
    ? filePath.slice(resolve(cwd).length + 1)
    : filePath
  if (!isPathInside(cwd, relativeFromCwd)) {
    return {
      status: 'invalid_name',
      message: `Path traversal denied: "${name}" would escape project root.`,
    }
  }

  if (existsSync(filePath)) {
    return { status: 'already_exists', filePath, kind: type as GeneratorType, name }
  }

  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, content)

  // T5.2 + plan Q4: emit co-located test file alongside actions (only
  // for action type; routes/pages/ws keep prior single-file behavior).
  // Skip if existing test file present (preserve user-customized tests).
  if (type === 'action') {
    const testPath = filePath.replace(/\.ts$/, '.test.ts')
    if (!existsSync(testPath)) {
      writeFileSync(testPath, generateActionTestTemplate(name))
    }
  }

  return { status: 'created', filePath, kind: type as GeneratorType, name }
}

/**
 * CLI entry point — preserves the original surface (throws + console.log).
 * Wraps the programmatic `generate` function.
 */
export async function generateCommand(type: string, name: string): Promise<void> {
  const result = await generate({ cwd: process.cwd(), type, name })
  switch (result.status) {
    case 'not_a_project':
      throw new Error('Not a Theo project. Run this from a project root with theo.config.ts')
    case 'invalid_kind':
      throw new Error(result.message ?? 'Invalid kind')
    case 'invalid_name':
      throw new Error(
        `Invalid name "${name}". Use kebab-case: lowercase letters, numbers, hyphens. Example: my-route`,
      )
    case 'already_exists':
      console.log(`\n  ⚠ ${result.filePath} already exists. Skipping.\n`)
      return
    case 'created':
      console.log(`\n  ✓ Created ${type}: ${result.filePath}\n`)
      return
  }
}
