import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

import type { GenerateResult } from './generate.js'

// --- Field parsing ---

const ALLOWED_FIELD_TYPES = new Set(['string', 'text', 'number', 'boolean'])
const RESERVED_FIELDS = new Set(['id', 'createdAt', 'created_at'])

export interface ResourceField {
  name: string
  type: 'string' | 'text' | 'number' | 'boolean'
  drizzleColumn: string
  zodType: string
}

export function parseResourceFields(args: string[]): ResourceField[] {
  if (args.length === 0) {
    throw new Error(
      'Resource requires at least one field. Example: theokit generate resource posts title:string',
    )
  }
  return args.map((arg) => {
    const parts = arg.split(':')
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      throw new Error(`Invalid field "${arg}". Use name:type format (e.g. title:string)`)
    }
    const [name, type] = parts
    if (!ALLOWED_FIELD_TYPES.has(type)) {
      throw new Error(
        `Unknown field type "${type}" in "${arg}". Valid types: ${[...ALLOWED_FIELD_TYPES].join(', ')}`,
      )
    }
    if (RESERVED_FIELDS.has(name)) {
      throw new Error(`Field "${name}" is reserved (auto-generated by the framework)`)
    }
    const fieldType = type as ResourceField['type']
    return {
      name,
      type: fieldType,
      drizzleColumn: mapDrizzleColumn(name, fieldType),
      zodType: mapZodType(fieldType),
    }
  })
}

// --- Column / type mapping ---

function mapDrizzleColumn(name: string, type: ResourceField['type']): string {
  switch (type) {
    case 'string':
    case 'text':
      return `text('${name}').notNull()`
    case 'number':
      return `integer('${name}').notNull()`
    case 'boolean':
      return `integer('${name}', { mode: 'boolean' }).notNull().default(false)`
  }
}

function mapZodType(type: ResourceField['type']): string {
  switch (type) {
    case 'string':
    case 'text':
      return 'z.string()'
    case 'number':
      return 'z.number()'
    case 'boolean':
      return 'z.boolean()'
  }
}

// --- Template generators ---

function generateSchemaEntry(resourceName: string, fields: ResourceField[]): string {
  const cols = [
    `  id: integer('id').primaryKey({ autoIncrement: true }),`,
    ...fields.map((f) => `  ${f.name}: ${f.drizzleColumn},`),
    `  createdAt: text('created_at')`,
    `    .notNull()`,
    `    .$defaultFn(() => new Date().toISOString().split('T')[0]),`,
  ]
  return [
    ``,
    `export const ${resourceName} = sqliteTable('${resourceName}', {`,
    ...cols,
    `})`,
    ``,
  ].join('\n')
}

function generateRouteIndex(resourceName: string, fields: ResourceField[]): string {
  const bodyFields = fields.map((f) => `    ${f.name}: ${f.zodType},`).join('\n')
  return [
    `import { defineRoute } from 'theokit/server/define'`,
    `import { z } from 'zod'`,
    `import { db } from '../../db/index.js'`,
    `import { ${resourceName} } from '../../db/schema.js'`,
    ``,
    `export const GET = defineRoute({`,
    `  handler: () => db.select().from(${resourceName}).all(),`,
    `})`,
    ``,
    `export const POST = defineRoute({`,
    `  body: z.object({`,
    bodyFields,
    `  }),`,
    `  status: 201,`,
    `  handler: ({ body }) => {`,
    `    const result = db.insert(${resourceName}).values(body).returning().get()`,
    `    return result`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

function generateRouteId(resourceName: string, fields: ResourceField[]): string {
  const updateFields = fields.map((f) => `    ${f.name}: ${f.zodType}.optional(),`).join('\n')
  return [
    `import { defineRoute } from 'theokit/server/define'`,
    `import { z } from 'zod'`,
    `import { db } from '../../db/index.js'`,
    `import { ${resourceName} } from '../../db/schema.js'`,
    `import { eq } from 'drizzle-orm'`,
    ``,
    `export const GET = defineRoute({`,
    `  params: z.object({ id: z.coerce.number() }),`,
    `  handler: ({ params }) => {`,
    `    const item = db.select().from(${resourceName}).where(eq(${resourceName}.id, params.id)).get()`,
    `    if (!item) return new Response(JSON.stringify({ error: 'Not found' }), { status: 404 })`,
    `    return item`,
    `  },`,
    `})`,
    ``,
    `export const PUT = defineRoute({`,
    `  params: z.object({ id: z.coerce.number() }),`,
    `  body: z.object({`,
    updateFields,
    `  }),`,
    `  handler: ({ params, body }) => {`,
    `    const result = db.update(${resourceName}).set(body).where(eq(${resourceName}.id, params.id)).returning().get()`,
    `    if (!result) return new Response(JSON.stringify({ error: 'Not found' }), { status: 404 })`,
    `    return result`,
    `  },`,
    `})`,
    ``,
    `export const DELETE = defineRoute({`,
    `  params: z.object({ id: z.coerce.number() }),`,
    `  status: 204,`,
    `  handler: ({ params }) => {`,
    `    db.delete(${resourceName}).where(eq(${resourceName}.id, params.id)).run()`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

function generateTestTemplate(resourceName: string): string {
  return [
    `import { describe, it, expect } from 'vitest'`,
    ``,
    `describe('${resourceName} API', () => {`,
    `  it('should have a schema defined', async () => {`,
    `    const schema = await import('../server/db/schema.js')`,
    `    expect(schema.${resourceName}).toBeDefined()`,
    `  })`,
    ``,
    `  it('should have route handlers', async () => {`,
    `    const index = await import('../server/routes/${resourceName}/index.js')`,
    `    expect(index.GET).toBeDefined()`,
    `    expect(index.POST).toBeDefined()`,
    `  })`,
    `})`,
    ``,
  ].join('\n')
}

// --- Orchestrator ---

export function generateResource(cwd: string, name: string, fieldArgs: string[]): GenerateResult {
  let fields: ResourceField[]
  try {
    fields = parseResourceFields(fieldArgs)
  } catch (err) {
    return { status: 'invalid_name', message: err instanceof Error ? err.message : String(err) }
  }

  const schemaPath = resolve(cwd, 'server/db/schema.ts')
  const routeIndexPath = resolve(cwd, `server/routes/${name}/index.ts`)
  const routeIdPath = resolve(cwd, `server/routes/${name}/[id].ts`)
  const testPath = resolve(cwd, `tests/${name}.test.ts`)

  if (!existsSync(schemaPath)) {
    return {
      status: 'not_a_project',
      message:
        'server/db/schema.ts not found. Run this from a TheoKit project with database setup.',
    }
  }

  if (existsSync(routeIndexPath)) {
    return { status: 'already_exists', filePath: routeIndexPath, kind: 'resource', name }
  }

  const existingSchema = readFileSync(schemaPath, 'utf-8')
  if (existingSchema.includes(`export const ${name} =`)) {
    return {
      status: 'already_exists',
      filePath: schemaPath,
      kind: 'resource',
      name,
      message: `Table "${name}" already exists in schema.ts`,
    }
  }

  // 1. Append schema entry
  appendFileSync(schemaPath, generateSchemaEntry(name, fields))

  // 2. Create route files
  mkdirSync(dirname(routeIndexPath), { recursive: true })
  writeFileSync(routeIndexPath, generateRouteIndex(name, fields))
  writeFileSync(routeIdPath, generateRouteId(name, fields))

  // 3. Create test file
  mkdirSync(dirname(testPath), { recursive: true })
  if (!existsSync(testPath)) {
    writeFileSync(testPath, generateTestTemplate(name))
  }

  return { status: 'created', filePath: routeIndexPath, kind: 'resource', name }
}
