import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

import { generateResource } from './generate-resource.js'
import {
  VALID_TYPES,
  type GeneratorType,
  type GenerateOptions,
  type GenerateResult,
} from './generate-types.js'

export {}

function toKebabCase(name: string): boolean {
  return /^[a-z][a-z0-9/-]*$/.test(name)
}

/**
 * Reserved JS identifier names that conflict with object prototype machinery
 * or would shadow built-in module shapes if used as action/route names.
 * Mirrors action-scan's RESERVED_NAMES (T1.4).
 */
const RESERVED_BASENAMES = new Set([
  'index',
  'constructor',
  '__proto__',
  'prototype',
  'hasOwnProperty',
])

/**
 * Validate that a name segment doesn't hit the reserved-identifier list.
 * Checks the BASENAME (last `/` segment) — nested `admin/constructor` still
 * rejected because the file `constructor.ts` would be the conflict.
 */
function hasReservedSegment(name: string): boolean {
  const basename = name.includes('/') ? (name.split('/').pop() ?? name) : name
  return RESERVED_BASENAMES.has(basename)
}

/**
 * EC-4: validate that resolving `targetSubpath` under `cwd` stays inside `cwd`.
 * Returns `true` when path is safe (stays inside), `false` when it escapes via
 * `..`, absolute path, null byte, or similar traversal vector.
 */
function isPathInside(cwd: string, targetSubpath: string): boolean {
  if (targetSubpath.includes('\x00')) return false
  if (targetSubpath.startsWith('/') || targetSubpath.startsWith('\\')) return false
  const resolved = resolve(cwd, targetSubpath)
  const cwdResolved = resolve(cwd)
  const sep = process.platform === 'win32' ? '\\' : '/'
  return resolved === cwdResolved || resolved.startsWith(cwdResolved + sep)
}

function toPascalCase(name: string): string {
  return name
    .split(/[-/]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

function toCamelCase(name: string): string {
  const pascal = toPascalCase(name)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function generateRouteTemplate(name: string): string {
  return [
    `import { route } from 'theokit/server'`,
    `import { z } from 'zod'`,
    ``,
    `export const GET = route()`,
    `  .handler(({ ctx }) => {`,
    `    return { message: 'TODO: implement ${name} GET' }`,
    `  })`,
    `  .build()`,
    ``,
  ].join('\n')
}

function generateControllerTemplate(name: string): string {
  const className = toPascalCase(name) + 'Controller'
  const baseName = name.split('/').pop() ?? name
  return [
    `// AUTO-GENERATED by \`theokit generate controller ${name}\``,
    `import { Controller, Get } from '@theokit/http'`,
    ``,
    `@Controller('${baseName}')`,
    `export class ${className} {`,
    `  @Get()`,
    `  findAll(): string {`,
    `    return 'This action returns all ${baseName}'`,
    `  }`,
    `}`,
    ``,
  ].join('\n')
}

function generateActionTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { action } from 'theokit/server'`,
    `import { z } from 'zod'`,
    ``,
    `export const ${camel} = action()`,
    `  .input(z.object({}))`,
    `  .handler(({ input, ctx }) => {`,
    `    return { message: 'TODO: implement ${name}' }`,
    `  })`,
    `  .build()`,
    ``,
  ].join('\n')
}

/**
 * Co-located test template for `theokit generate action <name>` (T5.2 +
 * plan Q4 cenário 1: roundtrip serialize). Skeleton uses vitest BDD shape
 * per testing.md.
 */
function generateAgentTemplate(name: string): string {
  return [
    `import { agent } from '@theokit/agents'`,
    `import { z } from 'zod'`,
    ``,
    `// Zero-config: this file is auto-served at POST /api/agents/${name}.`,
    `// Add tools with tool('name')...build() and chain them via .tool(...).`,
    `export default agent()`,
    `  .input(z.object({ message: z.string() }))`,
    `  .model('openai/gpt-4o-mini')`,
    `  .system('You are a helpful ${name} assistant.')`,
    `  .build()`,
    ``,
  ].join('\n')
}

function generateToolboxTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { tool } from 'theokit/server'`,
    `import { z } from 'zod'`,
    ``,
    `export const ${camel}Hello = tool('${name}_hello')`,
    `  .describe('Say hello')`,
    `  .input(z.object({ name: z.string() }))`,
    `  .execute(({ name }) => \`Hello, \${name}!\`)`,
    `  .build()`,
    ``,
  ].join('\n')
}

function generateWorkflowTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { Workflow, fn } from '@theokit/sdk/workflow'`,
    ``,
    `/**`,
    ` * A minimal workflow — a typed, multi-step pipeline (@theokit/sdk). Each \`fn(...)\` step is a pure`,
    ` * function; a step can also run an agent via \`agentStep(name, agent, mapInput)\`. Import + run it from`,
    ` * a route, action, cron job, or tool:`,
    ` *`,
    ` *   const run = await ${camel}Workflow.run({ name: 'Ada' })`,
    ` *   console.log(run.status, run.output)   // 'completed'  'Hello, Ada!'`,
    ` */`,
    `export const ${camel}Workflow = Workflow.create({ name: '${name}' })`,
    `  .then(fn('normalize', (input: { name: string }) => ({ name: input.name.trim() })))`,
    `  .then(fn('greet', (step: { name: string }) => \`Hello, \${step.name}!\`))`,
    `  .commit()`,
    ``,
  ].join('\n')
}

function generateEvalTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { Eval, Scorers } from '@theokit/sdk/eval'`,
    ``,
    `/**`,
    ` * An eval for your agent (@theokit/sdk) — runs the model over a dataset and scores each output.`,
    ` * To score the REAL agent, mirror its config: point \`agent.model\` (and, ideally, a \`systemPrompt\`)`,
    ` * at the same values your \`agents/chat.ts\` uses. Run it (needs a provider key in the environment):`,
    ` *`,
    ` *   const run = await ${camel}Eval.run()`,
    ` *   console.log(run.aggregate.meanScore)`,
    ` */`,
    `export const ${camel}Eval = Eval.create({`,
    `  name: '${name}',`,
    `  dataset: [{ input: 'Say ok', expected: 'ok' }],`,
    `  scorers: [Scorers.containsExpected({ caseSensitive: false })],`,
    `  // Mirror your agent: same model (+ systemPrompt) so this evaluates the agent your users talk to.`,
    `  agent: { apiKey: process.env.OPENROUTER_API_KEY ?? '', model: { id: 'openai/gpt-4o-mini' } },`,
    `})`,
    ``,
  ].join('\n')
}

function generateSandboxTemplate(name: string): string {
  const camel = toCamelCase(name)
  const base = name.split('/').pop() ?? name
  const snake = base.replace(/-/g, '_')
  return [
    `import { tool } from 'theokit/server'`,
    `import { LocalSandbox } from '@theokit/sdk/sandbox'`,
    `import { z } from 'zod'`,
    ``,
    `/**`,
    ` * A sandbox-backed agent tool. \`LocalSandbox\` (@theokit/sdk) runs a shell command with a timeout +`,
    ` * output cap, isolated from your app process — so the agent can run commands SAFELY. This IS an agent`,
    ` * capability: connect it to your agent with \`.tool(...)\`:`,
    ` *`,
    ` *   // agents/chat.ts`,
    ` *   import { ${camel}Tool } from './sandbox/${base}.js'`,
    ` *   agent().model(...).tool(${camel}Tool).build()`,
    ` */`,
    `export const ${camel}Tool = tool('${snake}')`,
    `  .describe('Run a shell command in an isolated sandbox and return its output.')`,
    `  .input(z.object({ command: z.string().describe('The shell command to run, e.g. "ls -la"') }))`,
    `  .execute(async ({ command }) => {`,
    `    const sandbox = new LocalSandbox({ timeoutMs: 5_000 })`,
    `    const { stdout, stderr, exitCode } = await sandbox.execute(command)`,
    `    return exitCode === 0 ? stdout : \`exit \${exitCode}: \${stderr}\``,
    `  })`,
    `  .build()`,
    ``,
  ].join('\n')
}

function generateScheduleTemplate(name: string): string {
  const base = name.split('/').pop() ?? name
  return [
    `import { defineCron } from 'theokit/server/cron'`,
    ``,
    `/**`,
    ` * A scheduled agent run — a first-class TheoKit cron. \`theokit build\` discovers it automatically and`,
    ` * translates the schedule to your deploy target's native cron (Vercel / Cloudflare / AWS). No manual`,
    ` * scheduler to start. The handler is where you invoke your agent — POST to \`/api/agents/chat\`, or use`,
    ` * \`@theokit/sdk\`'s \`Agent\` with the same model + system prompt as \`agents/chat.ts\`.`,
    ` *`,
    ` * Schedules are UTC (https://crontab.guru). \`signal\` aborts when the scheduler stops.`,
    ` */`,
    `export default defineCron('${base}', {`,
    `  schedule: '0 9 * * *', // every day at 09:00 UTC`,
    `  async handler({ traceId, scheduledAt, signal }) {`,
    `    void signal`,
    `    // Invoke your agent here — e.g. fetch your own \`/api/agents/chat\` endpoint, or call the SDK Agent.`,
    `    console.log(\`[${base}] fired at \${scheduledAt.toISOString()} (trace \${traceId})\`)`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

function generateMemoryTemplate(_name: string): string {
  return [
    `/**`,
    ` * Conversation memory — nothing to wire.`,
    ` *`,
    ` * Since @theokit/sdk 4.0, every agent session persists AUTOMATICALLY to a native Claude-shaped`,
    ` * transcript. TheoKit roots it at your app under \`.data/agent-sessions/projects/<cwd>/<agentId>.jsonl\`,`,
    ` * keyed by the conversation's session id — a same-session follow-up request resumes prior turns with`,
    ` * zero setup. There is no storage adapter to construct or pass to the agent anymore.`,
    ` *`,
    ` * Keep these transcripts out of git — add \`.data/\` to your \`.gitignore\`.`,
    ` *`,
    ` * Advanced: to change WHERE sessions are written (e.g. \`~/.claude\` so the Claude Code CLI can`,
    ` * \`--continue\` them), set the SDK's \`local.baseDir\` where you create the agent. Most apps never need to.`,
    ` */`,
    `export {}`,
    ``,
  ].join('\n')
}

function resolveTemplate(
  cwd: string,
  type: GeneratorType,
  name: string,
): { filePath: string; content: string } | null {
  switch (type) {
    // Agent-capability generators. These live UNDER `agents/` — they are facets of the agent domain,
    // not standalone top-level concerns — and the folder-semantic scanner treats each as composition
    // (never a phantom route). See docs/ARCHITECTURE.md.
    case 'workflow':
      return {
        filePath: resolve(cwd, 'agents/workflows', `${name}.ts`),
        content: generateWorkflowTemplate(name),
      }
    case 'eval':
      return {
        filePath: resolve(cwd, 'agents/evals', `${name}.ts`),
        content: generateEvalTemplate(name),
      }
    case 'sandbox':
      return {
        filePath: resolve(cwd, 'agents/sandbox', `${name}.ts`),
        content: generateSandboxTemplate(name),
      }
    case 'schedule':
      return {
        filePath: resolve(cwd, 'agents/schedules', `${name}.ts`),
        content: generateScheduleTemplate(name),
      }
    case 'memory':
      return {
        filePath: resolve(cwd, 'agents/memory', `${name}.ts`),
        content: generateMemoryTemplate(name),
      }
    case 'route':
      return {
        filePath: resolve(cwd, 'server/routes', `${name}.ts`),
        content: generateRouteTemplate(name),
      }
    case 'action':
      return {
        filePath: resolve(cwd, 'server/actions', `${name}.ts`),
        content: generateActionTemplate(name),
      }
    case 'page':
      return { filePath: resolve(cwd, `app/${name}/page.tsx`), content: generatePageTemplate(name) }
    case 'ws':
      return {
        filePath: resolve(cwd, 'server/ws', `${name}.ts`),
        content: generateWsTemplate(name),
      }
    case 'controller':
      return {
        filePath: resolve(cwd, 'server/controllers', `${name}.controller.ts`),
        content: generateControllerTemplate(name),
      }
    case 'agent':
      return {
        filePath: resolve(cwd, 'server/agents', `${name}.agent.ts`),
        content: generateAgentTemplate(name),
      }
    case 'toolbox':
      return {
        filePath: resolve(cwd, 'server/toolboxes', `${name}.tools.ts`),
        content: generateToolboxTemplate(name),
      }
    default:
      return null
  }
}

function generateActionTestTemplate(name: string): string {
  const camel = toCamelCase(name)
  return [
    `import { describe, it, expect } from 'vitest'`,
    ``,
    `import { ${camel} } from './${name.split('/').pop()}.js'`,
    ``,
    `describe('${name} action', () => {`,
    `  it('should accept a valid input shape', () => {`,
    `    expect(${camel}.input).toBeDefined()`,
    `    expect(typeof ${camel}.handler).toBe('function')`,
    `  })`,
    ``,
    `  it('should reject invalid input via zod schema', () => {`,
    `    const parsed = ${camel}.input.safeParse({ __invalid: true })`,
    `    // Empty object schema accepts {}; tighten this assertion when adding fields.`,
    `    expect(parsed.success).toBe(true)`,
    `  })`,
    `})`,
    ``,
  ].join('\n')
}

function generatePageTemplate(name: string): string {
  const pascal = toPascalCase(name)
  return [`export default function ${pascal}Page() {`, `  return <h1>${pascal}</h1>`, `}`, ``].join(
    '\n',
  )
}

function generateWsTemplate(_name: string): string {
  return [
    `import { defineWebSocket } from 'theokit/server'`,
    ``,
    `export default defineWebSocket({`,
    `  onMessage(ws, data) {`,
    `    ws.send(\`echo: \${data}\`)`,
    `  },`,
    `})`,
    ``,
  ].join('\n')
}

/**
 * Programmatic generate. Returns a structured result instead of throwing —
 * Studio (`theokit_generate` tool) consumes this directly. The CLI wrapper
 * below maps the structured result to console output + exit code semantics.
 */
// eslint-disable-next-line @typescript-eslint/require-await
export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  const { cwd, type, name } = opts

  if (!existsSync(resolve(cwd, 'theo.config.ts')) && !existsSync(resolve(cwd, 'theo.config.js'))) {
    return {
      status: 'not_a_project',
      message: 'Not a Theo project. cwd has no theo.config.ts or theo.config.js',
    }
  }

  if (!VALID_TYPES.includes(type as GeneratorType)) {
    return {
      status: 'invalid_kind',
      message: `Invalid generator type "${type}". Available: ${VALID_TYPES.join(', ')}`,
    }
  }

  if (!name || !toKebabCase(name)) {
    return {
      status: 'invalid_name',
      message: `Invalid name "${name}". Use kebab-case: lowercase letters, numbers, hyphens.`,
    }
  }

  // EC-2-related: reject reserved JS identifier basenames (would shadow
  // built-in prototype machinery in virtual module emit or scan).
  if (hasReservedSegment(name)) {
    return {
      status: 'invalid_name',
      message: `Reserved name "${name}" — basename collides with built-in identifier (index/constructor/__proto__/prototype/hasOwnProperty).`,
    }
  }

  // Resource generates multiple files — handle separately
  if (type === 'resource') {
    return generateResource(cwd, name, opts.fields ?? [])
  }

  const resolved = resolveTemplate(cwd, type as GeneratorType, name)
  if (resolved === null) {
    return { status: 'invalid_kind', message: `Unknown type: ${type}` }
  }
  const { filePath, content } = resolved

  // EC-4: confirm the resolved filePath stays inside cwd. `toKebabCase`
  // already rejects most traversal vectors but a defense-in-depth check
  // against `..` slipping in via valid-looking segments is cheap.
  const relativeFromCwd = filePath.startsWith(resolve(cwd))
    ? filePath.slice(resolve(cwd).length + 1)
    : filePath
  if (!isPathInside(cwd, relativeFromCwd)) {
    return {
      status: 'invalid_name',
      message: `Path traversal denied: "${name}" would escape project root.`,
    }
  }

  if (existsSync(filePath)) {
    return { status: 'already_exists', filePath, kind: type as GeneratorType, name }
  }

  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, content)

  // T5.2 + plan Q4: emit co-located test file alongside actions (only
  // for action type; routes/pages/ws keep prior single-file behavior).
  // Skip if existing test file present (preserve user-customized tests).
  if (type === 'action') {
    const testPath = filePath.replace(/\.ts$/, '.test.ts')
    if (!existsSync(testPath)) {
      writeFileSync(testPath, generateActionTestTemplate(name))
    }
  }

  return { status: 'created', filePath, kind: type as GeneratorType, name }
}

/**
 * CLI entry point — preserves the original surface (throws + console.log).
 * Wraps the programmatic `generate` function.
 */
export async function generateCommand(
  type: string,
  name: string,
  fields?: string[],
): Promise<void> {
  const result = await generate({ cwd: process.cwd(), type, name, fields })
  switch (result.status) {
    case 'not_a_project':
      throw new Error('Not a Theo project. Run this from a project root with theo.config.ts')
    case 'invalid_kind':
      throw new Error(result.message ?? 'Invalid kind')
    case 'invalid_name':
      throw new Error(
        `Invalid name "${name}". Use kebab-case: lowercase letters, numbers, hyphens. Example: my-route`,
      )
    case 'already_exists':
      console.log(`\n  ⚠ ${result.filePath} already exists. Skipping.\n`)
      return
    case 'created':
      console.log(`\n  ✓ Created ${type}: ${result.filePath}\n`)
      return
  }
}
