/**
 * TheoKit polyglot agent service — Hono sidecar.
 *
 * Conforms to the Like-Vercel runtime contract (ADR-0015):
 *   - Fetch-handler entry (native fetch handler from Hono)
 *   - GET /health convention (200 / 503)
 *   - JSON-line stdout logs
 *   - W3C traceparent propagation
 *   - Env vars at runtime
 *
 * Generated by `create-theokit --backend node`.
 */
import { Hono } from 'hono'
import { serve } from '@hono/node-server'

const SERVICE_NAME = process.env.THEOKIT_SERVICE_NAME ?? 'agent-node'
const SERVICE_PORT = Number.parseInt(process.env.THEOKIT_SERVICE_PORT ?? '8002', 10)

function log(
  level: 'info' | 'warn' | 'error',
  message: string,
  extra: Record<string, unknown> = {},
) {
  // eslint-disable-next-line no-console -- structured stdout per ADR-0015 invariant #5
  console.log(
    JSON.stringify({
      timestamp: new Date().toISOString(),
      level,
      message,
      service: SERVICE_NAME,
      ...extra,
    }),
  )
}

const app = new Hono()

// ADR-0015 invariant #6 — W3C traceparent propagation
app.use(async (c, next) => {
  const tp = c.req.header('traceparent')
  if (tp) {
    log('info', 'request', { traceparent: tp, path: c.req.path })
  }
  await next()
})

// ADR-0015 invariant #4 — healthcheck convention
app.get('/health', (c) => c.json({ status: 'ok' }))

// Example endpoint — TheoKit proxies /api/worker/* to this service.
app.post('/echo', async (c) => {
  const body = (await c.req.json()) as { message: string }
  return c.json({ echo: body.message })
})

serve({ fetch: app.fetch, port: SERVICE_PORT }, () => {
  log('info', `agent-node listening on :${String(SERVICE_PORT)}`)
})
