#!/usr/bin/env -S node --experimental-strip-types
/**
 * Regenerate golden fixtures for the T3.1 OpenAPI emit tests.
 *
 * Run via `pnpm openapi:regen-fixtures`. Captures the current
 * `emitOpenApi` + `zodToOpenApiSchema` output as the expected JSON
 * checked into `tests/fixtures/openapi-emit/`.
 *
 * NEVER call this automatically from a test runner. Goldens MUST be
 * explicitly regenerated by a human reviewing the diff (per ADR D4 +
 * encore convention).
 */
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { emitOpenApi } from '../packages/theo/src/vite-plugin/openapi-emit/emit.js'
import { DISCRIMINATED_UNION_MANIFEST } from '../tests/fixtures/openapi-emit/source/discriminated-union-app.js'
import { FULL_APP_MANIFEST } from '../tests/fixtures/openapi-emit/source/full-app.js'
import { buildRecursiveFixture } from '../tests/fixtures/openapi-emit/source/recursive-type-app.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const FIXTURES_DIR = resolve(__dirname, '../tests/fixtures/openapi-emit')

const BASE_CONFIG = {
  servers: [{ url: 'http://localhost:3000', description: 'Local development' }],
  specVersion: '3.1.0' as const,
  title: 'TheoKit Golden Fixture',
  version: '0.0.0',
}

function regenManifestFixture(
  name: string,
  manifest: Parameters<typeof emitOpenApi>[0]['manifest'],
): void {
  const tmp = mkdtempSync(join(tmpdir(), 'theokit-regen-golden-'))
  try {
    const { document } = emitOpenApi({
      manifest,
      config: { ...BASE_CONFIG, outDir: tmp },
    })
    const out = join(FIXTURES_DIR, name)
    writeFileSync(out, `${JSON.stringify(document, null, 2)}\n`, 'utf-8')
    console.log(`  ✓ ${name}`)
  } finally {
    rmSync(tmp, { recursive: true, force: true })
  }
}

function regenRecursiveFixture(): void {
  const result = buildRecursiveFixture()
  const out = join(FIXTURES_DIR, 'expected_recursive_type_components.json')
  writeFileSync(out, `${JSON.stringify(result, null, 2)}\n`, 'utf-8')
  console.log('  ✓ expected_recursive_type_components.json')
}

console.log('\nRegenerating OpenAPI golden fixtures...\n')
regenManifestFixture('expected_full_openapi.json', FULL_APP_MANIFEST)
regenManifestFixture('expected_discriminated_union_openapi.json', DISCRIMINATED_UNION_MANIFEST)
regenRecursiveFixture()
console.log('\n  Done. Review the diff before committing.\n')
