"""
TheoKit polyglot agent service — FastAPI sidecar.

Conforms to the Like-Vercel runtime contract (ADR-0015):
  - Fetch-handler entry (ASGI via uvicorn)
  - GET /health convention (200 / 503)
  - JSON-line stdout logs
  - W3C traceparent propagation
  - Env vars at runtime (not bundled)

Generated by `create-theokit --backend python`.
"""
import json
import logging
import os
import sys
from datetime import datetime, timezone

from fastapi import FastAPI, Request
from pydantic import BaseModel


SERVICE_NAME = os.environ.get("THEOKIT_SERVICE_NAME", "agent-python")
SERVICE_PORT = os.environ.get("THEOKIT_SERVICE_PORT", "8001")


class JsonFormatter(logging.Formatter):
    """ADR-0015 invariant #5 — JSON-line stdout logging."""

    def format(self, record: logging.LogRecord) -> str:
        log_obj = {
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            "level": record.levelname.lower(),
            "message": record.getMessage(),
            "service": SERVICE_NAME,
        }
        if hasattr(record, "traceparent"):
            log_obj["traceparent"] = getattr(record, "traceparent")
        return json.dumps(log_obj)


handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(JsonFormatter())
logging.basicConfig(level=logging.INFO, handlers=[handler])
log = logging.getLogger("theokit.service")


app = FastAPI(title=f"{SERVICE_NAME} agent service")


@app.middleware("http")
async def trace_middleware(request: Request, call_next):
    """ADR-0015 invariant #6 — W3C traceparent propagation."""
    traceparent = request.headers.get("traceparent")
    if traceparent:
        log.info(
            "request",
            extra={"traceparent": traceparent, "path": request.url.path},
        )
    response = await call_next(request)
    return response


@app.get("/health")
async def health() -> dict[str, str]:
    """ADR-0015 invariant #4 — healthcheck convention."""
    return {"status": "ok"}


class EchoRequest(BaseModel):
    message: str


@app.post("/echo")
async def echo(req: EchoRequest) -> dict[str, str]:
    """Example endpoint — TheoKit proxies /api/agent/* to this service."""
    return {"echo": req.message}
