import { createSourceFile as tsCreateSourceFile, ScriptTarget } from 'typescript'
import { describe, expect, it } from 'vitest'

import { generateClientDts } from '../../packages/theo/src/vite-plugin/app-typed-client.js'
import type { TheoManifest } from '../../packages/theo/src/server/scan/manifest.js'

const tsLatest = ScriptTarget.Latest

function mkManifest(routes: TheoManifest['routes']): TheoManifest {
  return {
    version: 1,
    generatedAt: '2026-06-01T00:00:00.000Z',
    routes,
    actions: [],
    websockets: [],
  }
}

const DTS_OUT = '/proj/.theokit/client.d.ts'
const SERVER_DIR = '/proj/server'

describe('generateClientDts', () => {
  it('emits the AUTO-GENERATED header + eslint-disable + declared module', () => {
    const out = generateClientDts({
      manifest: mkManifest([]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('AUTO-GENERATED by theokit')
    expect(out).toContain('/* eslint-disable */')
    expect(out).toContain("declare module '@theo/client'")
    expect(out).toContain('export const client: AppClient')
  })

  it('generates an empty stub when no routes are present', () => {
    const out = generateClientDts({
      manifest: mkManifest([]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('No routes detected')
  })

  it('renders a single GET route as `users.get`', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        { filePath: 'routes/users.ts', routePath: '/api/users', paramNames: [], methods: ['GET'] },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('users:')
    // The route export is named INLINE, not through an alias declared at the top of the block.
    // The alias form was pinned here for months and silently produced `any` (#469) — a string
    // assertion cannot tell a type that works from one that collapses, which is why
    // `generated-client-types-survive.test.ts` compiles the output instead of matching it.
    expect(out).toMatch(/get:.+typeof import\('\.\.\/server\/routes\/users'\)\.GET/)
    expect(out).not.toContain('import type { GET as')
  })

  it('renders GET + POST on the same route as `users.get` + `users.post`', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/users.ts',
          routePath: '/api/users',
          paramNames: [],
          methods: ['GET', 'POST'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toMatch(/get:.+typeof import\([^)]+\)\.GET/)
    expect(out).toMatch(/post:.+typeof import\([^)]+\)\.POST/)
  })

  it('renders dynamic params with proper `params: { id: string }` type', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/users.[id].ts',
          routePath: '/api/users/:id',
          paramNames: ['id'],
          methods: ['GET', 'DELETE'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('params: { id: string }')
  })

  // Regression — theokit 0.2.2 fix: the previous codegen emitted
  // `(opts: params: { id: string } & TheoFetchOptions<...>)` which is invalid
  // TypeScript syntax (parser reads `params:` as a parameter label, then `{...}`
  // as the type — combination invalid). Result: dogfood-app typecheck failed
  // with TS1005/TS1359/TS1138 when consuming the published theokit@0.2.1.
  // Fix wraps the intersection in `{ params: {...} }` so the signature is
  // `(opts: { params: { id: string } } & TheoFetchOptions<...>)`.
  it('regression: dynamic-param signature uses `(opts: { params: ... } & ...)` wrap (not `opts: params:` flat)', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/users.[id].ts',
          routePath: '/api/users/:id',
          paramNames: ['id'],
          methods: ['GET', 'DELETE'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    // Must contain the wrapped form
    expect(out).toContain('(opts: { params: { id: string } } & import')
    // Must NOT contain the broken flat form
    expect(out).not.toContain('(opts: params: {')
    // Parse with ts.createSourceFile to catch any syntax error globally —
    // this catches future regressions in other intersection points.
    // parseDiagnostics is attached to the SourceFile when set==true.
    const sf = tsCreateSourceFile('out.d.ts', out, tsLatest, true)
    const diags = (sf as unknown as { parseDiagnostics?: ReadonlyArray<{ messageText: string }> })
      .parseDiagnostics
    if (diags && diags.length > 0) {
      throw new Error(
        `Generated client.d.ts has ${diags.length} parse error(s): ${diags.map((d) => d.messageText).join(' | ')}`,
      )
    }
  })

  // Regression — theokit 0.2.2 fix: multi-param routes (`.:user/:id` etc) must
  // also wrap correctly. Catch double-param edge case.
  it('regression: multi-param route also uses `{ params: {...} }` wrap', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/users.[user]/posts.[id].ts',
          routePath: '/api/users/:user/posts/:id',
          paramNames: ['user', 'id'],
          methods: ['GET'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('(opts: { params: { user: string; id: string } } & import')
    expect(out).not.toMatch(/\(opts: params:/)
  })

  it('uses relative import paths from the .d.ts location (no aliases assumed)', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        { filePath: 'routes/posts.ts', routePath: '/api/posts', paramNames: [], methods: ['GET'] },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    // The path still has to be relative to the `.d.ts`; it just travels inside `import('...')`
    // now rather than in a separate import line.
    expect(out).toContain("import('../server/routes/posts')")
  })

  it('EC-2: keeps a kebab-case segment literal, as a bracket key', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/user-profiles.ts',
          routePath: '/api/user-profiles',
          paramNames: [],
          methods: ['GET'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    // It camelCased until #470. The runtime Proxy builds the URL from the key it is handed, so
    // `userProfiles` requested `/api/userProfiles` while the route was served at
    // `/api/user-profiles` — the call compiled and answered 404. The key mirrors the URL now;
    // `generated-client-reaches-its-routes.test.ts` is what holds the two together.
    expect(out).toContain("'user-profiles':")
    expect(out).not.toContain('userProfiles:')
  })

  it('EC-2: unsafe segments (digit-leading) emit as bracket-access key', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        { filePath: 'routes/2fa.ts', routePath: '/api/2fa', paramNames: [], methods: ['POST'] },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toMatch(/'2fa':/)
  })

  it('EC-3: collision method vs sub-namespace renames sub-namespace with `_` suffix', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        // GET /api/posts — declares method `get`
        { filePath: 'routes/posts.ts', routePath: '/api/posts', paramNames: [], methods: ['GET'] },
        // POST /api/posts/get — collides with method name `get` from above
        {
          filePath: 'routes/posts/get.ts',
          routePath: '/api/posts/get',
          paramNames: [],
          methods: ['POST'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('// WARNING (EC-3)')
    expect(out).toContain('get_:')
    expect(out).toMatch(/posts:[\s\S]*get:/)
  })

  it('EC-8: Windows path separators are normalized in import paths', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes\\posts.ts',
          routePath: '/api/posts',
          paramNames: [],
          methods: ['GET'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).not.toContain('\\\\')
    expect(out).toMatch(/import\('\.\.\/server\/routes\/posts'\)/)
  })

  it('skips routes whose methods array is empty', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        { filePath: 'routes/util.ts', routePath: '/api/util', paramNames: [], methods: [] },
        { filePath: 'routes/x.ts', routePath: '/api/x', paramNames: [], methods: ['GET'] },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('x:')
    expect(out).not.toMatch(/util:.+get/)
  })

  it('routes without methods declared (legacy manifest) are skipped silently', () => {
    const out = generateClientDts({
      manifest: mkManifest([{ filePath: 'routes/x.ts', routePath: '/api/x', paramNames: [] }]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toContain('No routes detected')
  })

  it('nested route paths produce nested namespaces (posts.id.comments.get)', () => {
    const out = generateClientDts({
      manifest: mkManifest([
        {
          filePath: 'routes/posts.[id].comments.ts',
          routePath: '/api/posts/:id/comments',
          paramNames: ['id'],
          methods: ['GET', 'POST'],
        },
      ]),
      dtsOutPath: DTS_OUT,
      serverDir: SERVER_DIR,
    })
    expect(out).toMatch(/posts:[\s\S]*id:[\s\S]*comments:/)
  })
})
