#!/usr/bin/env python3
"""Promote a validated candidate skill from generated/ to .claude/skills/ (first-class).

Workflow:
  1. Re-validate (always — no skipping)
  2. Refuse if verdict != PASS
  3. Refuse if target path already exists (name collision)
  4. Move generated/{name}/ → .claude/skills/{name}/
  5. Write audit file at .claude/knowledge-base/reviews/skill-register-{name}-{date}.md

Exit codes:
  0 — Registered
  1 — Refused (validator did not return PASS, or other policy refusal)
  2 — Error (path not found, malformed)
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


SKILL_VALIDATOR_SCRIPT = ".claude/skills/skill-validator/scripts/validate_skill.py"


def _find_project_root(start: Path) -> Path:
    current = start.resolve()
    for _ in range(20):
        if (current / ".claude").exists() or (current / ".git").exists():
            return current
        if current == current.parent:
            break
        current = current.parent
    return start.resolve()


def _read_source_blueprint(marker: Path) -> dict[str, str]:
    if not marker.exists():
        return {}
    lines = marker.read_text(encoding="utf-8").strip().split("\n")
    keys = ["blueprint_slug", "blueprint_verdict", "blueprint_score", "generation_timestamp"]
    return {k: v for k, v in zip(keys, lines + [""] * (len(keys) - len(lines)))}


def _read_description(skill_md: Path) -> str:
    if not skill_md.exists():
        return "(no description)"
    content = skill_md.read_text(encoding="utf-8-sig")
    m = re.search(r"^description:\s*(.+?)(?:\n[a-z\-]+:|\n---)", content, re.MULTILINE | re.DOTALL)
    if m:
        return m.group(1).strip().replace("\n", " ")
    return "(description not parsed)"


def _revalidate(candidate_skill_dir: Path, project_root: Path) -> dict:
    """Run the validator script as a subprocess. Returns parsed JSON output."""
    validator = project_root / SKILL_VALIDATOR_SCRIPT
    if not validator.exists():
        return {"verdict": "ERROR", "reason": f"Validator script missing at {validator}"}

    result = subprocess.run(
        ["python3", str(validator), str(candidate_skill_dir / "SKILL.md")],
        capture_output=True,
        text=True,
    )
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"verdict": "ERROR", "reason": f"Validator emitted non-JSON: {result.stderr or result.stdout}"}


def _write_audit(audit_dir: Path, name: str, source_info: dict, description: str) -> Path:
    audit_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    audit_file = audit_dir / f"skill-register-{name}-{today}.md"

    body = f"""# Skill Registration: {name}

**Date:** {today}
**Source blueprint:** {source_info.get('blueprint_slug', 'unknown')}
**Blueprint verdict at generation:** {source_info.get('blueprint_verdict', 'unknown')}
**Blueprint score at generation:** {source_info.get('blueprint_score', 'unknown')}
**Validator verdict:** PASS (verified at registration time)
**Registered from:** .claude/skills/generated/{name}/
**Registered to:** .claude/skills/{name}/

## Skill description (verbatim from frontmatter)

{description}

## Audit chain

This skill was generated by `/skill-writer` from a `/discover-execute` blueprint, passed `/skill-validator` checks (frontmatter + citations + no-duplication + description-clarity + no-forbidden-patterns), and was promoted by `/skill-register` on the date above.

The `.source-blueprint` marker file inside the skill dir preserves the audit chain after registration.

## How /to-plan now consumes this skill

Step 0 of `/to-plan` scans `.claude/skills/*/SKILL.md` frontmatter `description` fields for relevant trigger phrases. When the user invokes `/to-plan` with a topic that matches the trigger phrases above, this skill is loaded into context.

To verify: invoke `/to-plan` with a prompt matching the trigger phrases. The plan should cite the Patterns / Recommendations from this skill.

## Rollback

```
mv .claude/skills/{name}/ .claude/skills/generated/{name}/
# Optionally delete this audit entry.
# Optionally revert any .claude/settings.json patches (none expected for read-only skills).
```

"""
    audit_file.write_text(body, encoding="utf-8")
    return audit_file


def main() -> int:
    parser = argparse.ArgumentParser(description="Promote a candidate skill from generated/ to first-class.")
    parser.add_argument("--candidate", required=True, help="candidate skill name (dir under .claude/skills/generated/)")
    parser.add_argument("--dry-run", action="store_true", help="report what would happen without moving")
    args = parser.parse_args()

    project_root = _find_project_root(Path.cwd())
    source = project_root / ".claude" / "skills" / "generated" / args.candidate
    target = project_root / ".claude" / "skills" / args.candidate
    audit_dir = project_root / ".claude" / "knowledge-base" / "reviews"

    # Sanity checks
    if not source.exists():
        print(json.dumps({"error": f"Candidate not found at {source}"}), file=sys.stderr)
        return 2

    if target.exists():
        print(
            json.dumps({"error": f"Refused: target already exists (collision): {target}"}),
            file=sys.stderr,
        )
        return 1

    # Re-validate
    validator_result = _revalidate(source, project_root)
    verdict = validator_result.get("verdict", "ERROR")

    if verdict != "PASS":
        out = {
            "error": "Refused: validator did not return PASS",
            "validator_verdict": verdict,
            "validator_checks": validator_result.get("checks", {}),
        }
        print(json.dumps(out, indent=2), file=sys.stderr)
        return 1

    # Read source-blueprint marker + description for audit
    source_info = _read_source_blueprint(source / ".source-blueprint")
    description = _read_description(source / "SKILL.md")

    if args.dry_run:
        out = {
            "candidate": args.candidate,
            "source": str(source),
            "target": str(target),
            "validator_verdict": "PASS",
            "source_blueprint": source_info,
            "description": description,
            "dry_run": True,
        }
        print(json.dumps(out, indent=2))
        return 0

    # Write audit BEFORE the move — honors SKILL.md "Hard rule 2" (audit MUST be
    # written before the move completes). If the move fails, the audit is an orphan
    # discoverable in git history; if we did move-then-audit and audit failed, we'd
    # have a registered skill with no trail — the worse failure mode.
    audit_file = _write_audit(audit_dir, args.candidate, source_info, description)

    # Move
    shutil.move(str(source), str(target))

    out = {
        "candidate": args.candidate,
        "registered_at": str(target),
        "audit_file": str(audit_file),
        "verdict": "REGISTERED",
        "validator_verdict": "PASS",
        "source_blueprint": source_info,
    }
    print(json.dumps(out, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
